### ISSUE TITLE
Can I use super tabs in a normal tabs page?

### ISSUE THREAD

**Issue by yanxiaodi** [zyra/ionic2-super-tabs#101]
I would like to appreciate you for this excellent component. 

Now I have a normal tabs layout. I want to user super tabs in one of these tab pages, but it has something wrong. The headers of the root normal tabs disappear, and  the headers of the super tabs are not in the right position.

If I put super tabs in a simple page, it works fine.

Could you help me to solve this problem? Thanks!

**Comment by yanxiaodi** [comment]
By the way, I mean that I put a normal tabs on the bottom of the page, and this page has a header bar. but the headers of the super tabs are covered by the page header bar, and the normal tabs on the bottom are disappeared.

**Comment by ihadeed** [comment]
Could you please provide steps to reproduce this issue? steps or an example project would work. Screenshots would help too.

**Comment by yanxiaodi** [comment]
First, create a new ionic tabs project, with version 3.5.0.
Then create 3 pages by CLI, which named as NewsList1Page, NewsList2Page, NewsList3Page.
Install super tabs as shown in ReadMe.md.

I want to modify the Home page and put super tabs in it.
Update home.html, delete "ion-content" section and replace it with these code:
`<super-tabs>
    <super-tab [root]="page1" title="First page"></super-tab>
    <super-tab [root]="page2" title="Second page"></super-tab>
    <super-tab [root]="page3" title="Third page"></super-tab>
</super-tabs>`

Update home.ts:
`import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { NewsList1Page } from "../news-list1/news-list1";
import { NewsList2Page } from "../news-list2/news-list2";
import { NewsList3Page } from "../news-list3/news-list3";

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  page1 = NewsList1Page;
  page2 = NewsList2Page;
  page3 = NewsList3Page;
  constructor(public navCtrl: NavController) {

  }

}
`
So it is a simple demo, but the difference is that I put super tabs in one of the normal tab page, so it has something wrong, as shown in this image:
![super tabs](http://images2015.cnblogs.com/blog/352913/201707/352913-20170703193611956-889439465.png)

Thanks!

**Comment by yanxiaodi** [comment]
@ihadeed Hi! Could you help me to check this issue? Thank you very much!

**Comment by ihadeed** [comment]
Oh I see.

I think this is happening because the tabs component is designed to align the sub page's header at the top of the page, so that it appears above the tab buttons.

If you place the tab buttons (ion-tabs) at the bottom, your problem will probably be fixed.

**Comment by yanxiaodi** [comment]
The default ion-tabs's tab buttons are placed at the bottom, like the samples on the ionic websites: http://ionicframework.com/docs/components/#tabs

I am confused because the super-tabs works fine in the simple page, but it can't run correctly in the ion-tab page.

**Comment by yanxiaodi** [comment]
OK I got it. I must place super-tabs in the ion-content section. It works now.
Thanks!
