### ISSUE TITLE
Error: goToRoot needs to be implemented by child class

### ISSUE THREAD

**Issue by icharge** [zyra/ionic2-super-tabs#102]
This happened when me click back button from page that has been set root from Deeplinks

![image](https://user-images.githubusercontent.com/1619007/27851582-a020aa24-6185-11e7-8eab-e2526312d6c9.png)

"ionic-angular": "^3.5.0"
"ionic2-super-tabs": "^3.0.1"

**Comment by ihadeed** [comment]
Thanks for reporting this.

Please install `ionic2-super-tabs@3.0.2` and let me know if you're still experiencing this issue.
