### ISSUE TITLE
tabSelect only fires when changing tab

### ISSUE THREAD

**Issue by robobobo** [zyra/ionic2-super-tabs#103]
The `tabSelect` event only seems to fire when a user switches to a new tab.

It is quite a common user experience that tapping a tab will scroll back to the top of the page or bring you back to the root page of that tab (I push pages into a tab and it would make sense that by tapping the tab you would pop all the pages back to the root)

Something similar was discussed for `ion-tab` here https://forum.ionicframework.com/t/capturing-ion-tab-click-on-active-tab-event/56594/34

Would be great to be able to listen to that event regardless if the tab is changing or not

**Comment by robobobo** [comment]
I found a work around for this, you can add a `tap` event which will fire every time the tab is tapped.

`<super tabs (tap)="tapped()" (tabSelect)="onTabSelect($event)"> </super-tabs>`

**Comment by ihadeed** [comment]
Yeah I noticed that Ionic Framework's tabs component fires the event everytime. It sends out an object similar to the following:
```js
{
  index: 1,
  changed: false
}
```

I will add this in upcoming releases.
