### ISSUE TITLE
ionic-app-scripts 2.0.0 compatibility?

### ISSUE THREAD

**Issue by SteveKennedy** [zyra/ionic2-super-tabs#105]
Just recently updated to ionic-app-scripts 2.0.0.  When the main tabs container renders, the page doesn't render correctly.  Is this just me?

![untitled](https://user-images.githubusercontent.com/12101125/27980438-44a8a21c-6344-11e7-864f-1e3cd1d90457.png)

**Comment by ihadeed** [comment]
Did you include `<script src="build/vendor.js"></script>` in your `index.html` file?

**Comment by SteveKennedy** [comment]
@ihadeed yep.

**Comment by ihadeed** [comment]
Ok I'll take a look soon. For now just revert to older version of app-scripts. I will update you once this is fixed.

Thanks for reporting the issue!

**Comment by SteveKennedy** [comment]
@ihadeed Thank you.

**Comment by edotassi** [comment]
https://github.com/ionic-team/ionic-app-scripts/issues/1090

**Comment by SteveKennedy** [comment]
I believe 2.0.1 of ionic scripts has fixed the issue. The latest versions of everything (ionic, native, scripts, angular, npm, etc.) all seem to work together to have eliminated this specific issue now.

**Comment by ihadeed** [comment]
Thanks for the update @SteveKennedy
