### ISSUE TITLE
How can I have the tabs included in the Header of my app ? 

### ISSUE THREAD

**Issue by opicciotto** [zyra/ionic2-super-tabs#106]
I managed to use super-tabs in my app by adding the &lt;super-tabs&gt; tag under the &lt;ion-content&gt; tag without padding.

This works ok, but I have a separation line between the header and the tabs. I would like to have the tabs included in the header without the separation line.

I tried to add the &lt;super-tabs&gt; under the &lt;ion-header&gt;, the tabs are displayed correctly, but the pages are not displayed when a tab is selected...

Any Idea why?

**Comment by ihadeed** [comment]
I can't understand what you mean. Please include some screenshots.

**Comment by opicciotto** [comment]
Hello,

![super-tab](https://user-images.githubusercontent.com/1043988/27995598-9322c9c0-64d1-11e7-8488-c1d4d239d04e.JPG)

How can I get rid of the highlighted in Yellow line between the header and the tabs?

Attached is the HTML code .

![image](https://user-images.githubusercontent.com/1043988/27995729-87dc0584-64d3-11e7-82f9-fee17897c2aa.png)


Thank you.

**Comment by ihadeed** [comment]
Oh, just add `no-shadow` to the `ion-header`

**Comment by opicciotto** [comment]
Soooo simple 👍 

Thank you.

**Comment by opicciotto** [comment]
Actually, it's no-border in Ionic3
It works thanks
