### ISSUE TITLE
setBadge ERROR ...

### ISSUE THREAD

**Issue by abdellahx01** [zyra/ionic2-super-tabs#107]
hi there ..

i have a problem using setBadge i got error below when i use it in other page ... it's work fine only in one page in others i got error like below ...

**ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'setBadge' of undefined
TypeError: Cannot read property 'setBadge' of undefined
    at SuperTabs.setBadge (super-tabs.js:217)
    at SuperTabsController.setBadge (super-tabs-controller.js:8)**

**Comment by ihadeed** [comment]
How are you trying to use it?

**Comment by abdellahx01** [comment]
i found a solution for that i use **badge**
