### ISSUE TITLE
Property 'getActiveChildNavs' is missing in type 'SuperTabs'.

### ISSUE THREAD

**Issue by giscafer** [zyra/ionic2-super-tabs#109]
`npm install ionic-angular@nightly --save`
https://github.com/ionic-team/ionic/issues/12238

```
Typescript Error
Class 'SuperTabs' incorrectly implements interface 'NavigationContainer'. Property 'getActiveChildNavs' is missing in type 'SuperTabs'.
```
![qq 20170712153246](https://user-images.githubusercontent.com/8676711/28106688-64b0789c-6717-11e7-896b-497d8255d007.png)

**Comment by wstidolph** [comment]
I was OK on Angular 3.5.0, but just hit this on upgrading from Angular 3.5.0 to 3.5.2 (and upgrading app-scripts, too, but I don't think that's relevant)

**Comment by giscafer** [comment]
@wstidolph thks,i had cloned the source code and fixed the error,now it work fine on ionic-angular@nightly

**Comment by ihadeed** [comment]
Closing in favour of #117

**Comment by danielehrhardt** [comment]
https://forum.ionicframework.com/t/ionic-3-6-0-getactivechildnavs-of-undefined/100810

**Comment by jtushar53** [comment]
Hi,

https://forum.ionicframework.com/t/ionic-3-6-0-ionic-supertabs-getactivechildnavs-of-undefined/100810/7

getting above issue with latest version of ionic-angular and super tabs

currently trying to make it work using  npm install ionic-angular@3.5.0 ionic2-super-tabs@3.0.2  

please reopen the issue.

Thanks

**Comment by jtushar53** [comment]
Hi @danielehrhardt ,

Never knew it works with normal Ionic tabs. Can you please share a sample code for that.

Thanks

**Comment by danielehrhardt** [comment]
@jtushar53 https://github.com/danielehrhardt/ionic2-super-tabs-example
