### ISSUE TITLE
Not working on ionic 3.4

### ISSUE THREAD

**Issue by sminhaj28** [zyra/ionic2-super-tabs#112]
can not find module on ionic 3.4.
i am also installing super tabs varsion 2.6.3

**Comment by SteveKennedy** [comment]
@sminhaj28 Can you provide a lot more information?  What error are you getting exactly? Details. Version numbers.

**Comment by sminhaj28** [comment]
It shows error in app.module.
 SuperTabModule not found
I run this command **npm i --save ionic2-super-tabs**.
I referred this example - https://forum.ionicframework.com/t/ionic-swipeable-tabs-are-now-here/84266

**Comment by ihadeed** [comment]
@sminhaj28 the example on the forum is just a quick example to show how easy it is to use the module.

Please follow the instructions provided in the home page (or README.md file) of this repository: https://github.com/zyra/ionic2-super-tabs

You need to import `SuperTabsModule` into your app's module (and child modules, if you use lazy loading).
