### ISSUE TITLE
this._renderer.setElementClass is not a function

### ISSUE THREAD

**Issue by pablogarciamiranda** [zyra/ionic2-super-tabs#114]
I am facing the following issue only in Ios:

## **Error Message**

`ERROR: ERROR TypeError: this._renderer.setElementClass is not a function. (In 'this._renderer.setElementClass(this._elementRef.nativeElement, className, isAdd)', 'this._renderer.setElementClass' is undefined)

ERROR: ERROR TypeError: undefined is not an object (evaluating 'this.indicator.nativeElement')
`

## **Environment**
Super-Tabs: 3.0.2
global packages:
    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0
local packages:
    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0
System:
    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : not installed
    npm        : 5.2.0

**Comment by ihadeed** [comment]
Please check the compatibility table here: https://github.com/zyra/ionic2-super-tabs#compatibility

Super-Tabs 3.0.2 isn't compatible with Ionic Framework 3.3.0
