### ISSUE TITLE
super tabs doesn't work on ionic 3.5.2

### ISSUE THREAD

**Issue by flyhuang** [zyra/ionic2-super-tabs#117]
Today I update ionic to 3.5.2,  it breaks super-tab

Exception:

[15:07:04]  typescript: node_modules/ionic2-super-tabs/dist/components/super-tabs.d.ts, line: 39 
            Class 'SuperTabs' incorrectly implements interface 'NavigationContainer'. Property 'getActiveChildNavs' is 
            missing in type 'SuperTabs'. 

      L39:  export declare class SuperTabs implements OnInit, AfterContentInit, AfterViewInit, OnDestroy, RootNode, Navi
      L40:      viewCtrl: ViewController;

Could u help to look this issue?

**Comment by pablogarciamiranda** [comment]
I have the same issue.

`Class 'SuperTabs' incorrectly implements interface 'NavigationContainer'. Property 'getActiveChildNavs' is missing in type 'SuperTabs'.`

Ionic Framework: 3.5.2

**Comment by dkd051** [comment]
![Issue](http://imgur.com/17660c52-bdba-4aa4-b0ca-dd3756441974)

I have the same issue.

**Comment by danielehrhardt** [comment]
```
[15:47:29]  typescript: node_modules/ionic2-super-tabs/dist/components/super-tabs.d.ts, line: 39
            Class 'SuperTabs' incorrectly implements interface 'NavigationContainer'. Property 'getActiveChildNavs' is
            missing in type 'SuperTabs'.

      L39:  export declare class SuperTabs implements OnInit, AfterContentInit, AfterViewInit, OnDestroy, RootNode, Navi
      L40:      viewCtrl: ViewController;

```

**Comment by mhartington** [comment]
Can someone run `npm ls typescript`

**Comment by danielehrhardt** [comment]
```
contacts-app@0.0.1 /Users/danielehrhardt/projekte/Contacts/contacts-app
└── typescript@2.3.4
```

**Comment by mhartington** [comment]
We'll be fixing this in a new release. It was a small regression

**Comment by danielehrhardt** [comment]
https://forum.ionicframework.com/t/ionic-3-6-0-getactivechildnavs-of-undefined/100810
