### ISSUE TITLE
Project failed to run

### ISSUE THREAD

**Issue by eddyng8** [zyra/ionic2-super-tabs#119]
I got the following error after trying to use super tabs in my ionic project.

![image](https://user-images.githubusercontent.com/21133343/28224916-13322a24-688e-11e7-9a6f-706f7fa1b1eb.png)

**Comment by eddyng8** [comment]
One more question. Do you support horizontal scrolling if I have many icons in the tab? I might have up to 9 icons in the tab and currently the out of the box ionic tab does not support it. Does your tab support it?

**Comment by ihadeed** [comment]
What version of `ionic2-super-tabs` are you using? 

Please refer to the [Compatibility](https://github.com/zyra/ionic2-super-tabs#compatibility) table to make sure you're using the right versions.

**Comment by ihadeed** [comment]
@eddyng8 yes you can scroll between tabs, you will need to add the [scrollTabs](https://github.com/zyra/ionic2-super-tabs#scrolltabs) attribute to your `super-tabs` component. [See here](https://github.com/zyra/ionic2-super-tabs-example/blob/master/src/pages/home/home.html#L10) for example code.

**Comment by eddyng8** [comment]
I ran "npm i --save ionic2-super-tabs" and I got version 4.0. I will upgrade my ionic version to 3.5.2 now. Thanks.
