### ISSUE TITLE
can swipe beyond first tab

### ISSUE THREAD

**Issue by justiceo** [zyra/ionic2-super-tabs#12]
It is possible to swipe into an empty space - if you swipe hard enough :)
I was just curious as to how far the whitespace at the end would go, then realized that beyond a certain point the slide gets locked in to the right.

![swipe](https://cloud.githubusercontent.com/assets/7328691/24840059/175be5d6-1d34-11e7-9523-61e14440a5c4.png)

> The content seems locked in to the right and does not return. It is still scrollable and below is a second screenshot after a scroll:

![swipe 2](https://cloud.githubusercontent.com/assets/7328691/24840082/a3484aee-1d34-11e7-823a-d7cd974b7e1a.png)

**Comment by ihadeed** [comment]
This will be fixed in the next release, subscribe to #14 to stay tuned.
