### ISSUE TITLE
Loading indicator in the first page does not close

### ISSUE THREAD

**Issue by eddyng8** [zyra/ionic2-super-tabs#120]
I just tried super tabs v3.0.2. I have a loading indicator in my first page that I displayed using LoadingController before I started my async operation and dismissed after the data is retrieved. This works fine with the out of the box ion-tabs. But after switching to super tabs, the loading indicator cannot be dismissed. I think my Loading indicator conflicted with super tabs' loading indicator. If I remove the loading indicator, super tabs work fine. Also, loading indicator in 2nd page, 3rd page, etc work fine. Only the loading indicator in 1st page caused issue.

**Comment by ihadeed** [comment]
Is this the same as #113 ?

**Comment by eddyng8** [comment]
I don't think it's the same thing. Let me try to illustrate it. Here is my super tabs configuration:

`<super-tabs tabsPlacement="bottom" toolbarColor="light" [config]="{ sideMenu: 'left' }">
    <super-tab [root]="tabAnnouncements" title="Announcements" icon="information-circle"></super-tab>
    <super-tab [root]="tabLinks" title="Links" icon="link"></super-tab>
    <super-tab [root]="tabVesselInfo" title="Vessels" icon="boat"></super-tab>
    <super-tab [root]="tabCaptainInfo" title="Captain" icon="person"></super-tab>
</super-tabs>`

In the ionViewDidLoad in the Announcement page, which is the first page, I have something like:

`ionViewDidLoad() {
   loading = this.loadingCtrl.create({
                content: 'Please wait...',
                spinner: 'circles'
            });
   loading.present();

   this.http.get(url)..subscribe(
                res => {
                         // do something
                         loading.dismiss();
                },
                err => {
                        // do something
                         loading.dismiss();      
                });
}`

In the above case, my loading indicator will never get dismissed. I think what happened was before your loading indicator got dismissed, mine is shown. When that happens, since ionic 3, the 2nd loading indicator will not get dismissed. I had seen this in my project. I think the good solution for this is to add an option in the supertabs to not use the loading indicator if the user knows that their first page will have its own loading indicator.

**Comment by eddyng8** [comment]
I figured out the cause of this issue. It has nothing to do with the Loading indicator of the super tabs. The root cause is because super tabs pre-load the next tab as mentioned in the other issue in the forum. So, what happened in my case was super tabs loaded the Announcements and Links page at the same time. Both pages pops up loading indicator when retrieving data from back end. As I mentioned, since ionic 3 if you pops up more than one loading indicators, it won't get dismissed properly when calling loading.dismiss(). 

Hopefully you will address the issue with preloading the adjacent tab soon because it breaks many things in my project since I assume the page will be loaded one page at a time. Fixing the issue will make it easier for people who are replacing the ion-tabs with your SUPER tabs  :-)
