### ISSUE TITLE
when tabs do not exceed the screen width, distribute the width of the tab evenly.

### ISSUE THREAD

**Issue by longdw** [zyra/ionic2-super-tabs#125]
when I add two or three super-tabs, and the tabs width do not exceed the screen width, I want to make all tab's width equal. but the actual situation is the right will leave a large blank.

I want to do that auto, not added or removed attribute scrollTabs.

**Comment by longdw** [comment]
i solved it, i removed `scrollTabs`.

**Comment by longdw** [comment]
I want to do that auto, not added or removed attribute `scrollTabs`.

**Comment by ihadeed** [comment]
You can achieve this by not using the `scrollTabs` attribute.

**Comment by ihadeed** [comment]
It's not possible to do this automatically. You have to choose whether you want the tabs to be scroll-able or not.
