### ISSUE TITLE
ion-item-sliding issue

### ISSUE THREAD

**Issue by eddyng8** [zyra/ionic2-super-tabs#127]
One of my tabs contains an ion-list with ion-item-sliding in the list. When I tried to slide the item to reveal the option, it will slide the super tab also. If I return to the previous tab again, I can see that the options for the ion-item-sliding are revealed. Is there anything I can do to prevent super tab from sliding when I'm trying to reveal the options for my ion-item-sliding?

**Comment by aPinix** [comment]
Go see my solution on the issue [#139](https://github.com/zyra/ionic2-super-tabs/issues/139).

**Comment by ihadeed** [comment]
Will be fixed in next release with the new `allowElementScroll` config. https://github.com/zyra/ionic2-super-tabs#config
