### ISSUE TITLE
How to get dynamic number of tabs

### ISSUE THREAD

**Issue by Topiya** [zyra/ionic2-super-tabs#129]
Hello, 
How can I use forLoop (*ngFor) in ionic2-super-tabs tag to get Tabs based on the data ? I do not have fixed number of tabs so that need for loop here to get dynamic tabs.

Is there any way to implement the same?

**Comment by ihadeed** [comment]
You have to create the component AFTER you have all the data figured out. You can't add/remove tabs after the component has been created.

See https://github.com/zyra/ionic2-super-tabs/issues/46
