### ISSUE TITLE
swiping to reset to parent tab instead going to the child tabs

### ISSUE THREAD

**Issue by parkbroom** [zyra/ionic2-super-tabs#131]
Is It possible to swipe only to the parent page even when we select a child pages on the parent page?

**Comment by ihadeed** [comment]
Are you talking about the Swipe To Go Back feature on iOS?

**Comment by parkbroom** [comment]
hi ihadeed no

I pretty much have 2 tabs HomePage and AccountPage.

AccountPage has a lot of subpages - ChangePasswordPage, ChangePhonePage

I want the following scenario:

We are at AccountPage and go to ChangePasswordPage
ChangePasswordPage swipeleft goes to HomePage,
HomePage swiperight should go to AccountPage and NOT ChangePasswordPage. 

The only way I can think of is replacing the <super-tab> onTabSelect since changing pages just changes <super-tab>.  Here's what I have so far

tabs.html
<super-tabs scrollTabs (tabSelect)="onTabSelect($event)">
  <super-tab [root]="HomePage" title=""></super-tab>
  <super-tab [root]="AccountPage" title="" id='account'></super-tab>
</super-tabs>

tabs.ts
  ngOnInit() {
    this.accountPageHtml = this.el.nativeElement.querySelector('#account');
    console.log(this.accountPageHtml);
  }

  onTabSelect(ev: any) {
    console.log('Tab selected', 'Index: ' + ev.index, 'Unique ID: ' + ev.id);
    if(ev.id != 'account') {
      // I need to replace the dom <super-tab [root]="AccountPage" title="" id='account'></super-tab> with this.accountPageHtml
    }
  }

**Comment by ihadeed** [comment]
You should push the child pages through `rootNavCtrl`
