### ISSUE TITLE
Infinite non-passive event listener warnings

### ISSUE THREAD

**Issue by nicoNaN** [zyra/ionic2-super-tabs#132]
```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v8.1.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : not installed
    npm        : 4.6.1 
```

When the page with SuperTabs is pushed to the Navigation stack, the view never loads, and console infinitely prints errors like the following:

`[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.`

**Comment by ihadeed** [comment]
Thanks I'll look into it.

I recall seeing this warning in the console before, but it only shows if the log level is set to verbose. So IIRC this should have no effect on the component being rendered, you must be encountering another issue.

I might have used non-passive event listeners on purpose, but I will double check to make sure this library is fully optimized.

**Comment by ihadeed** [comment]
Did some quick reading... passive listeners are used if you know that you're not going to call `e.preventDefault()`. In our case, we might call it since we do want to prevent scrolling in some scenarios. 

You can set your logger to ignore `Verbose` level logs to stop seeing these messages.
