### ISSUE TITLE
Super Tabs Titles Changing Order on *ngIF attribute

### ISSUE THREAD

**Issue by Rkuro** [zyra/ionic2-super-tabs#137]
Hi,

I'm having an issue where after I add an *ngIF attribute to a super tab element, the order of the titles on the pages switches.

Code:

```
<ion-content class="profileSuperTabs profileContent" no-bounce (swipe)="closeGroupProfile($event,null)">
  <super-tabs [ngClass]="{'halves': group['events'].length == 0 && hasNewsFeed, 'single': group['events'].length == 0 && !hasNewsFeed}" (tabSelect)="onTabSelect($event)">
    <super-tab [root]="groupInfoPage" [rootParams]="feedData" title="FEED" *ngIf="hasNewsFeed"></super-tab>
    <super-tab [root]="groupInfoPage" [rootParams]="aboutData" title="ABOUT"></super-tab>
  </super-tabs>
</ion-content>
```

Ideally, the ABOUT tab should show up second and on the right. However, instead I am getting the ABOUT tab first with the newsfeed html underneath, and the FEED tab second, with the about html underneath. If I remove the *nfIF, then it behaves properly, however I need it because some things don't have a feed

<img width="392" alt="screen shot 2017-08-02 at 5 07 26 pm" src="https://user-images.githubusercontent.com/13005003/28895142-3dca8120-77a5-11e7-9681-138c3669699f.png">

**Comment by ihadeed** [comment]
Once the `super-tabs` component is rendered, you cannot alter the child `super-tab` components. This is related to some other issues that are mentioned here. 

There are no plans yet to implement this. For now, gather all the data you need before rendering `super-tabs`. This means that you need to have an `ngIf` on the `super-tabs` component that makes sure that you have all the data ready.

**Comment by davideas** [comment]
Or simply load your data in the single pages! :+1: as I do.
