### ISSUE TITLE
Super tab placed over header and not under it

### ISSUE THREAD

**Issue by xCap1** [zyra/ionic2-super-tabs#138]
Hi ! 

I think this issue was mentioned long ago when asking about the possibility of positioning the tabs either on the top or bottom. When I use super-tabs on bottom the positioning is correct, but if I put then on top they go over the header instead of under it, any clue? 

![sin titulo](https://user-images.githubusercontent.com/10884913/28911783-f691daf0-7831-11e7-8fd0-7d6045120f11.png)

**Comment by ihadeed** [comment]
No, it's not possible.

You need to use one header in the main page (that contains `<super-tabs>`, and remove the headers from the child pages. 

I don't intend to implement this feature as it will reduce the performance, and it doesn't match the material design specs that this project tries to follow.
