### ISSUE TITLE
enableTabsSwipe(false) but horizontal scroll on page

### ISSUE THREAD

**Issue by aPinix** [zyra/ionic2-super-tabs#139]
Great job on **ionic2-super-tabs**

Can I have the possibility to have a page with a normal **vertical scroll (this I'm able to do already)** and have segmented buttons with **swipable horizontal scroll** without having the prevent swipe?

Note that I'm using:

```javascript
ngAfterViewInit() {
  this.superTabsCtrl.enableTabsSwipe(false);
}
```

I would really appreciate this :)

Here's my **page.html** code:

```html
<ion-header>
  <ion-toolbar>
      <!-- this must be horizontally scrollable -->
      <!-- segment buttons are bigger because I have set them via SCSS -->
      <ion-segment [(ngModel)]="segmentBtns" color="primary">
        <ion-segment-button value="seg1">Segment 01</ion-segment-button>
        <ion-segment-button value="seg2">Segment 02</ion-segment-button>
        <ion-segment-button value="seg3">Segment 03</ion-segment-button>
        <ion-segment-button value="seg4">Segment 04</ion-segment-button>
        <ion-segment-button value="seg5">Segment 05</ion-segment-button>
      </ion-segment>
  </ion-toolbar>
</ion-header>
```

And here is my declared `enableTabsSwipe(false)` on my **page.ts** code:

```javascript
ngAfterViewInit() {
  this.superTabsCtrl.enableTabsSwipe(false);
}
```

Here's an image to represent what I want marked with red:

![horizontal-scroll problem](https://user-images.githubusercontent.com/698523/29428488-4f7537f8-8385-11e7-8631-acc4238cccd7.jpg)

**Comment by aPinix** [comment]
I got it to work by **commenting** two lines in the `super-tabs-pan-gesture.js` that is inside of `node_modules/ionic2-super-tabs/dist/`.

```javascript
// stop anything else from capturing these events, to make sure the content doesn't slide
// ev.stopPropagation();
// ev.preventDefault();
```

If anyone wants to know this is how I got it.

**Comment by tsebvaan** [comment]
Working. Thanks !

**Comment by ihadeed** [comment]
@aPinix 

does your fix have any side effects? or is everything working as expected?

**Comment by aPinix** [comment]
The fix has no side effects so far. I used it for a while but I had to stop using this plugin because it uses the ionic **Slider** component and when I use a list inside, the scroll is slow and unresponsive, even with the virtual scroll applied to it. And that's a pitty

**Comment by ihadeed** [comment]
`ionic2-super-tabs` doesn't use `ion-slider` anymore. 

What device(s) are you using to test the app?

**Comment by aPinix** [comment]
I'm testing in iPhone 6 and iPhone SE. When i use a list on a simple page or with the default tabs component it works smoothly but when I use Super Tabs plugin, even the latest, the scroll lags.

**Comment by KevinFu** [comment]
got the same problem

**Comment by ihadeed** [comment]
Will be fixed in next release with the new `allowElementScroll` config. https://github.com/zyra/ionic2-super-tabs#config
