### ISSUE TITLE
Swipe doesn't work when drag the page.

### ISSUE THREAD

**Issue by aasongWang** [zyra/ionic2-super-tabs#140]
Hello.
My ionic version is 3.7.0 and version of ionic-supertabs is  4.01.
When I press the tab button , page swiping works well.
But when i drag the page, page swiping doesn't work.
Please help.
Thanks.

**Comment by ihadeed** [comment]
Thanks for reporting this. I haven't tested the module with 3.7.0 yet, it should work with 3.6.0 though. 

I will take a look and fix this when I get a chance.

**Comment by aasongWang** [comment]
Hello.
I am sorry, It was my fault.
I tested on the device and it works.
Regards.
