### ISSUE TITLE
Hiding Tabs on Subpages

### ISSUE THREAD

**Issue by mohpra** [zyra/ionic2-super-tabs#141]
Is there a way to hide Tabs on Subpages?

When using <ion-tabs> I was using tabsHideOnSubPages: "True" to hide tabs. Is there something like that?

**Comment by mohpra** [comment]
I have done it in the following way:

My tabs.html is 

<super-tabs tabsPlacement="bottom" selectedTabIndex="0"  id="tabs">
  <super-tab [root]="tab1Root" [rootParams]="fooId" title="Page1" icon="fa-street-view"></super-tab>
  <super-tab [root]="tab2Root" [rootParams]="fooId" title="Page2" icon="fa-rss"></super-tab>
  <super-tab [root]="tab3Root" [rootParams]="fooId" title="Page3" icon="fa-comments"></super-tab>
  <super-tab [root]="tab4Root" [rootParams]="fooId" title="Page4" icon="fa-coffee"></super-tab>
</super-tabs>

In the root pages I have done

this.tabBarElement = document.querySelector('super-tabs-toolbar');

ionViewWillLeave() {
 this.tabBarElement.style.display = 'none';  
}

ionViewWillEnter() {
 this.tabBarElement.style.display = 'block';  
}

And finally in the supertabs css make height as 100% as by default it sets height as calc(100% - 72px), which pushes the page down, when the tab bar is hidden.

So make the changes as 

super-tabs {
  height: 100%;
}

**Comment by rravindranaik111** [comment]
Hello,

I have also same issue while using super-tabs. Instead of customization is there any way to hide this tabs on subpages ?????

Instead of "tabsHideOnSubPages" tag for normal ionic tab is there any other option to do that in super-tabs ?

**Comment by ihadeed** [comment]
Just use `rootNavCtrl` to push pages..

**Comment by dilanfdo** [comment]
@ihadeed thanks for the solution. was looking for this solution for days. Just to summarize following is the way to open subpages without tabs

//import App to tabs view component
import { App } from 'ionic-angular';

//add App to constructor
public appCtrl: App

//call the other page from tabs page
this.appCtrl.getRootNav().push( 'OtherPage', {}, { animate: true } );
