### ISSUE TITLE
SuperTabs Hide Toolbar

### ISSUE THREAD

**Issue by monichols** [zyra/ionic2-super-tabs#142]
Hello,

I'm trying to hide my super tabs from the tabs.ts page. I am using ionic3 and I am not utilizing lazy loading. 

For some reason I can't get this code to work:

import { Component, ViewChild } from '@angular/core';
import { AboutPage } from '../about/about';
import { ContactPage } from '../contact/contact';
import { HomePage } from '../home/home';
import { SuperTabsController } from 'ionic2-super-tabs';

@Component({
  templateUrl: 'tabs.html'
})
export class TabsPage {

 

page1 = HomePage;
  page2 = AboutPage;
  page3 = ContactPage;

  constructor(private superTabsCtrl: SuperTabsController) {
    
 this.superTabsCtrl.showToolbar(false);

  }
    hideToolbar() {
    this.superTabsCtrl.showToolbar(false);
  }
} 

I also tried the example from the repo here:

import { Component, ViewChild } from '@angular/core';
import { AboutPage } from '../about/about';
import { ContactPage } from '../contact/contact';
import { HomePage } from '../home/home';
import { SuperTabsController } from 'ionic2-super-tabs';

@Component({
  templateUrl: 'tabs.html'
})
export class TabsPage {

 @ViewChild(SuperTabs) superTabs: SuperTabsController;

page1 = HomePage;
  page2 = AboutPage;
  page3 = ContactPage;

  constructor() {

  }
   hideToolbar() {
    this.superTabs.showToolbar(false);
  }
}
and I'm getting the error cannot find name superTabs.

**Comment by monichols** [comment]
Hey Everyone figured it out...here is the code from my tabs page if anyone also ran into the same issue.


import { Component, ViewChild } from '@angular/core';
import { SuperTabsModule, SuperTabsConfig, SuperTabs } from 'ionic2-super-tabs';
import { AboutPage } from '../about/about';
import { ContactPage } from '../contact/contact';
import { HomePage } from '../home/home';

@Component({
  templateUrl: 'tabs.html'
})
export class TabsPage {

  @ViewChild(SuperTabs) superTabs: SuperTabs;

  tab1Root = HomePage;
  tab2Root = AboutPage;
  tab3Root = ContactPage;

  constructor() {

  }
   ionViewDidLoad(){
    this.hideToolbar();
  }
  hideToolbar() {
    this.superTabs.showToolbar(false);
  }
}

**Comment by usm4nq** [comment]
Hello there, 
how to do the same from the HomePage.

**Comment by heidji** [comment]
@usm4nq i didn't test is but i think you should be able to pass the mentioned superTabs element as a reference in the html like so:
```
<super-tabs>
    <super-tab title="home" [root]="tab1" [rootParams]="superTabs"></super-tab>
    ...
</super-tabs>
```
otherwise you can resort to other methods to notify the tabs page of any changes you want such as events.publish and events.subscribe. There is no other direct way to change the superTabs element from anywhere else without reference to the instance in the tabs.ts file ..

**Comment by VlnRbn** [comment]
I use @monichols sloution, but i'm getting this error... Cannot read property 'showToolbar' of undefined.. Can somebody help please....
