### ISSUE TITLE
How to use custom icons (like fontawesome)

### ISSUE THREAD

**Issue by belavenuto** [zyra/ionic2-super-tabs#143]
Hi super-tabs team, thanks for this plug-in, it's really helpful. 

Is there a way of using other icons than just ionic icons?
I need to use fontawesome icons in the Tabs, but I couldn't find a way to achieve that.

Thank you!

**Comment by migueldonaire** [comment]
hi, this is the right way: https://yannbraga.com/2017/06/28/how-to-use-custom-icons-on-ionic-3/

**Comment by belavenuto** [comment]
Hi @migueldonaire, thanks for the link.
That is exactly what I was looking for!

**Comment by gujtesting** [comment]
> hi, this is the right way: https://yannbraga.com/2017/06/28/how-to-use-custom-icons-on-ionic-3/

The Link you posted isn't working anymore can you please Add the solution here?

**Comment by aditbharadwaj** [comment]
> Hi @migueldonaire, thanks for the link.
> That is exactly what I was looking for!

hi can u please post how u used custom icons on tab
