### ISSUE TITLE
List slow scroll inside Super Tab

### ISSUE THREAD

**Issue by aPinix** [zyra/ionic2-super-tabs#144]
Well, the **lists** inside of **Super Tabs** are very slow and unresponsive when scrolled. Even using **Virtual Scroll** implemented.

I seems it's because of the implementation of the **Slider Component** itself and as Super Tabs uses it so there's no escaping to it.

Is there a way of having list **vertical scroll** fast as they are outside of the **Slider Component**?

Thanks in advance ;)

**Comment by ihadeed** [comment]
Super tabs doesn't use Slider component anymore.
