### ISSUE TITLE
How to make tabs scrollable ?

### ISSUE THREAD

**Issue by daemswibowo** [zyra/ionic2-super-tabs#145]
Can I add an overflow-x on a tab?
I hope so, so this can be like native android

**Comment by aPinix** [comment]
Can you specify a little bit more? Maybe I can help you.

**Comment by belavenuto** [comment]
Are you referring to scrollTabs property?

[https://github.com/zyra/ionic2-super-tabs#scrolltabs](url)

**Comment by daemswibowo** [comment]
Thanks @belavenuto . You save me :)
That's the one I want
