### ISSUE TITLE
How to make the tabs move up along with the content when scrolling?

### ISSUE THREAD

**Issue by izamorar** [zyra/ionic2-super-tabs#146]
Good morning I need the scroll to move along with the content, that is to say when under the scroll the tabs must go up as if of a content it was and when lower the scroll this returns to its normality

**Comment by tsebvaan** [comment]
+1

**Comment by Topiya** [comment]
@izamorar 
Did you get any solution for this?

**Comment by ihadeed** [comment]
To scroll the tab content -> scroll inside the tab
To scroll the page -> scroll outside the tab

**Comment by FIDELIX07** [comment]
@ihadeed Please can you help with any CSS or JS hack to achieve this, I'm trying to implement the instagram like tab with this supertabs, but the content of each tab keep scrolling beneath the SuperTabs. Please help in any way you can i'm stucked. Thank you
