### ISSUE TITLE
There are some minor issues with the Android system

### ISSUE THREAD

**Issue by longdw** [zyra/ionic2-super-tabs#148]
I simply describe the problem first.
I run app in Android.
When I scroll to the last tab, and then I push a page from the last page, the pushed page have some ion-input, when I click the ion-input and the keyboard is showing, and then I click other blank space the keyboard has gone, then I click back, here comes the problem, the last tab has a blank space from the far right. following pic shows the problem. I create a [gitub example](https://github.com/longdw/TestSuperTab)

![top1](https://user-images.githubusercontent.com/4987178/29602993-f9dd2032-8814-11e7-86ee-4fe04c07b668.gif)

**Comment by vinay13** [comment]
@longdw @ihadeed i'm also facing same issue. Any solution for this issue ?

**Comment by longdw** [comment]
@vinay13  I have no idea also... , I've been waiting for the original author.
