### ISSUE TITLE
iOS only: Tab-icon partially cut off when inactive

### ISSUE THREAD

**Issue by JaneDawson** [zyra/ionic2-super-tabs#149]
Hi @ihadeed,

thank you for this plugin and your great work!

Using the current version (4.0.1) I have an issue on iOS. One of the tab-icons (icon="time") is partially cut off at the left side, when the tab is inactive. As soon as the tab becomes active, everything is fine. The issue only occurs on an iOS devices (tested on both, iPhone and iPad). It does not occur on either Android nor Browser.

Inactive tab:
![Image Inactive tab:](http://i.imgur.com/vZG78IB.png)

Active tab:
![Image Active tab:](http://i.imgur.com/ayEd4bU.png)

I know, this may seem as a minor thing. However, coming to production this is quite ugly. Do you have any idea what could cause the issue?

Thank you!

**Comment by JaneDawson** [comment]
Some more infos: As far as I have tested, the issue only occurs with ionicons-icon "time" (no matter if it's ios-time, ios-time-outline or md-time). It doesn't matter which tab's icon it is. I tried to put time as icon for all four tabs, and all of them showed the issue of the inactive icon beeing cut off at the left side.

I will have to use another icon for now, but it would be interesting to know, where this comes from.

**Comment by ihadeed** [comment]
Since this seems to be an issue with one icon, I won't fix it for now.. I can think of a proper solution if this become a more common issue. 

You can fix by applying adding custom css:
```scss
ion-icon.ion-ios-time {
  width: 40px; // adjust as necessary
}
```

**Comment by ihadeed** [comment]
Changed the title so it's easier to find.
