### ISSUE TITLE
How to use rootParams

### ISSUE THREAD

**Issue by cafej** [zyra/ionic2-super-tabs#157]
How do I retrieve the information pass to the super tabs using the rootParams input.
This is my code.

`<super-tabs tabsPlacement="bottom">
    <super-tab [root]="page1" icon="pricetags" title="Promociones" [rootParams]="id"></super-tab>
    <super-tab [root]="page2" icon="basket" title="Productos" [rootParams]="id"></super-tab>
    <super-tab [root]="page3" icon="archive" title="Mis compras" [rootParams]="id"></super-tab></super-tabs>`

And this is how I'm trying to access it

`this.id = this.navParams.get('id');`

But it doesn't work as regular navParams. Can someone provide some directions?

**Comment by ihadeed** [comment]
You need to pass an object with a property `id`, then you can retrieve it that way.

**Comment by yanxiaodi** [comment]
Be careful, you must pass an object as a param, instead of a string. If you use a simple string as a param, it doesn't work. I recommend the author should emphasize this issue.

**Comment by karimessouabni** [comment]
Try navParams.data to get your object ! You'd better debug your code on chrome using F12…

**Comment by krushn** [comment]
`[rootParams]="{ uuid: _params.get('uuid') }"`
