### ISSUE TITLE
aot build error

### ISSUE THREAD

**Issue by R0muald** [zyra/ionic2-super-tabs#159]
When building with the new angular-cli, aot compilation is activated by default. The problem is that ionic2-super-tabs does not compile correctly:
`SuperTabs.html (10,70): Expected 0 arguments, but got 1.`

I think it's related the the `(onDrag)="onDrag($event)"`. The function does not accept any argument so the build fail. Removing $event `(onDrag)="onDrag()"` should fix the aot issue.

**Comment by ihadeed** [comment]
Closing in favour of #254  .. update to latest version & post any issues you're having on that thread.
