### ISSUE TITLE
Error in use super-tabs

### ISSUE THREAD

**Issue by Smoke1987** [zyra/ionic2-super-tabs#16]
I try to use super-tabs as described, but I get an error:

ERROR Error: Uncaught (in promise): Error: No provider for Tabs!

Tried to add super-tabs to providers, this did not solve the problem.

**Comment by ihadeed** [comment]
Can you provide steps to reproduce this? or maybe a minimal project with your code in it.

**Comment by karlvd** [comment]
Make sure you added super-tabs under imports in your app.module file
```
@NgModule({
  declarations: [
    MyApp  
  ],
  imports: [
    SuperTabsModule.forRoot()
```
Not sure if you have to add it to page modules as well if you use lazy loading of pages.

**Comment by ihadeed** [comment]
@karlvd if you use lazy loading, then you need to add `SuperTabsModule` without `.forRoot()` to the page(s) that contain a `<super-tabs>` element.

**Comment by karlvd** [comment]
Thanks for clarifying!
