### ISSUE TITLE
[4.1.0] - Brief white screen when click header back button 

### ISSUE THREAD

**Issue by flyhuang** [zyra/ionic2-super-tabs#162]
Today I update version to 4.1.0.

It has a brief white screen when I click back button on ion-header, 4.0.1 works fine.

4.0.1:
![4-0-1](https://user-images.githubusercontent.com/1689430/30205151-95abffcc-94ba-11e7-81e2-da38c8cb9964.gif)

4.1.0
![4-1-0](https://user-images.githubusercontent.com/1689430/30205157-9b7d5dba-94ba-11e7-824d-544560e62318.gif)

Demo Project: 
https://github.com/flyhuang/ionic2-super-tabs-issue

When I remove these code in super-tabs.ts, it also works fine.

` viewCtrl._setContent(this);
  viewCtrl._setContentRef(el);`

Could u give me some suggestion about it?

Thanks,
Wade Huang

**Comment by ihadeed** [comment]
Thanks. I have to take that line out. I forgot why I removed it in the first place and I re-added it. It causes a few issues.

**Comment by flyhuang** [comment]
same issue like #191. close it.
