### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by sabarinathen** [zyra/ionic2-super-tabs#171]
when i was run on ionic serve contains an error in console like failed to load resources: the server responded with a status of 404 (Not Found)  and contains an error **Cannot find module '../ionic2-super-tabs/src'.**

**Comment by ihadeed** [comment]
I'm assuming you're talking about the example project. You need to run the git commands provided in the README.md to restore the Git submodules. Then you will be able to run the app.
