### ISSUE TITLE
hello,how to use this in ionic2.0beta?

### ISSUE THREAD

**Issue by zhoupIT** [zyra/ionic2-super-tabs#172]
I can use it in ionic2.0 well now,but  an old project is ionic2.0beta. I don't know how to import it in my app's module(s).My app just has a app.ts file.It has no app.module.ts file.

**Comment by ihadeed** [comment]
The current version of this module doesn't support Ionic 2.x ... You have to update your app, or use version 1.x of this plugin.

The first version of this module worked differently and is missing lots of the current features.
