### ISSUE TITLE
When entering a tab for the first time, the next tab is also loaded

### ISSUE THREAD

**Issue by abervoet** [zyra/ionic2-super-tabs#175]
Hello,
Thanks for this cool component. 
I noticed a questionable behavior and wanted to check if this is intended or not.

### Versions
```
    "@angular/common": "4.4.3",
    "@angular/core": "4.4.3",
    "ionic-angular": "3.7.1",
    "ionic2-super-tabs": "^4.1.0",
```

### Scenario
When you enter a page that contains the following code:
```
<super-tabs>
 <super-tab [root]="tab1"></super-tab>
 <super-tab [root]="tab2"></super-tab>
 <super-tab [root]="tab3"></super-tab>
</super-tabs>
```
- Standard page lifecycle is fired (`didLoad, willEnter, didEnter`)
- tab1 lifecycle is fired (`didLoad, willEnter, didEnter`)
- **tab2 lifecycle is fired (`didLoad, willEnter, didEnter`)**

**When selecting a tab for the first time, the next tab's lifecycle events are fired. Is this intended ?**
This is an issue when tabs code is relatively heavy and if you do not want your tab to be rendered and your data to be loaded before actually entering the tab, as you usually want to load your data on `didLoad, willEnter or didEnter`.

### Sample for reproducing
Clone the following, then run `npm install`, then run `ionic serve` and check the lifecycle traced on your browser's console.
[https://github.com/abervoet/ionic2-super-tabs-issue](https://github.com/abervoet/ionic2-super-tabs-issue)

In [the following screenshot](https://imgur.com/a/eV9UP), i served the app, then selected tab3 by clicking the toolbar. I did not interact with tab2 or tab4.

### Related code 
[SuperTabs.refreshTabStates()](https://github.com/zyra/ionic2-super-tabs/blob/master/src/components/super-tabs.ts#L541)
Fired from [ngAfterViewInit](https://github.com/zyra/ionic2-super-tabs/blob/1d7825daeb90e81c4171c5bacfe882a433e8c953/src/components/super-tabs.ts#L337) and [onTabChange](https://github.com/zyra/ionic2-super-tabs/blob/1d7825daeb90e81c4171c5bacfe882a433e8c953/src/components/super-tabs.ts#L512): the **< 2** condition makes `tab.load(true)` for the current and next tab.
```
  private refreshTabStates() {
    this._tabs.forEach((tab, i) => {
      tab.setActive(i === this.selectedTabIndex);
      tab.load(Math.abs(this.selectedTabIndex - i) < 2);
    });
  }
```
[SuperTab.load](https://github.com/zyra/ionic2-super-tabs/blob/1d7825daeb90e81c4171c5bacfe882a433e8c953/src/components/super-tab.ts#L142)
```
load(load: boolean) {
    if (load && !this.loaded) {
      this.init.then(() => {
        this.push(this.root, this.rootParams, { animate: false });
        this.loaded = true;
      });
    }
  }
```

### Work around: 
In my tab components code, do nothing in `ionViewDidLoad, willEnter, didEnter`. Use instead the super-tabs `tabSelect()` event to trigger a custom `onEnter` event.

View html code:
```
<super-tabs #tabs (tabSelect)="onTabChange($event)">
 ...
</super-tabs>
```
View code-behind:
```
@ViewChild('tabs') tabsContainer: SuperTabs;
protected onTabChange(event: any): void {
    console.info('onTabChange', event);
    this.tabsContainer.getActiveTab().getActive().instance.onEnter();
  }
```

Tab component code:
 ```
public onEnter(): void {
    console.info('Workaround: Tab1Component -> onEnter. Loaded state:', this.loaded);
    if (!this.loaded) {
      this.initView();
    }
  }

private initView(): void {
    //load data from api
    this.loaded = true;
  }
```

**Comment by ihadeed** [comment]
This is intentional. `willLoad` and `didLoad` are supposed to fire. `willEnter` and `didEnter` aren't supposed to fire.

We load the neighbour tabs so when the user partially swipes into the second page, they will be able to see some content, instead of a blank page.

I remember fixing this issue earlier, but I'll take another look when I get a chance and make sure the lifecycle events behaviour makes sense.

**Comment by KevinFu** [comment]
Got the same question, In my project different tabs load the same root page with different params 
the root page show loading component before load data from server 
then will got two **loading components**...

how to fix it

**Comment by abervoet** [comment]
Thank you for the fix!
In case you did not notice: console.log were included in the commitsupertabs.ts, doesn't matter.

**Comment by saihanuman73** [comment]
Even now I'm facing this issue now, But in a different manner. The thing is I have created two components for two super tabs. and when I call the parent <super-tabs> component only the first tab is getting called. Even though I clicked on second tab, the component is not getting called.
