### ISSUE TITLE
swipe process

### ISSUE THREAD

**Issue by ehdwns980416** [zyra/ionic2-super-tabs#176]
First of all, thanks to developers who created such a good plug-in.

I feel somewhat uncomfortable when I swipe the tab.
Each tab has an image of the product.
I know that the image is invoked when the tap is swiped.
Is there any way to get the image after tab swiped? (use spinner)

I mean, I hope it will soften.

**Comment by harshkhandelwalcs** [comment]
tabs are lagging on swiping in android device ....Please give me solution for this!

**Comment by harshkhandelwalcs** [comment]
Whats going on....Please help me

**Comment by dreindoRT** [comment]
I got same issue, anyone can show me how to fix it?

**Comment by ihadeed** [comment]
@eduardoRoth Not sure what is the issue you're having .. try making a sample project.

@harshkhandelwalcs If you're not getting the performance you were hoping for, then don't use this module. It's not meant to fit every single need. These kind of animations aren't easy to handle in a webview, specially on older devices. 

Revise your code, look for any memory leaks or excessive change detection triggers and fix those. If you're still not happy with the performance, then stick with regular tabs or `ion-segment`. 


-- 

Closing this issue. Feel free to re-open or create new one when you have a sample project for me to look at .
