### ISSUE TITLE
supertabs without root

### ISSUE THREAD

**Issue by ehdwns980416** [zyra/ionic2-super-tabs#177]
I'd like to use supertabs in supertabs without root. But it occured this error message.
'invalid views to insert'
What should I do?

**Comment by almogk012** [comment]
me too have the same problem .
i do tab for logout for pop up confirm only without HTML

**Comment by ihadeed** [comment]
So, you want to be able to add a tab button that performs an action instead of changing the active view?

**Comment by ehdwns980416** [comment]
Yes, That's what I said.

**Comment by almogk012** [comment]
anyone?

**Comment by ehdwns980416** [comment]
@ihadeed How's it going?

**Comment by ihadeed** [comment]
Out of scope of this project, won't implement. Feel free to fork & do what you want with the code.
