### ISSUE TITLE
Disabling Refreshing state for tabs

### ISSUE THREAD

**Issue by icsvortex666** [zyra/ionic2-super-tabs#178]
@ihadeed you should consider disabling this log messages.
<img width="837" alt="screen shot 2017-10-10 at 11 15 41 am" src="https://user-images.githubusercontent.com/4429087/31391251-6504628c-adac-11e7-9a66-3078aa60dbd4.png">

**Comment by icsvortex666** [comment]
Commenting lines 332, 336, 345 and 373 solved the issue.

**Comment by ihadeed** [comment]
Sorry I forgot to take them out
