### ISSUE TITLE
Issue in existing Project 

### ISSUE THREAD

**Issue by anujmpec** [zyra/ionic2-super-tabs#18]
It is working fine on new project but what is the steps to use it in my existing project with version 2.2.1.
I  did following steps :- 

1. Import in app.module.ts 
import { SuperTabsModule } from 'ionic2-super-tabs';
in   **imports:** [ SuperTabsModule.forRoot() ..]
 2. in home.ts and home.html
In both file i did same as git file . 

My error is as following :- 

 **Warning :-** 

npm WARN ionic2-super-tabs@2.1.0 requires a peer of ionic-angular@^3.0.0 but none was installed.

**Typescript Error**
Module '"/opt/lampp/htdocs/VendorIonic2/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
node_modules/ionic2-super-tabs/dist/components/super-tabs/super-tabs.d.ts
import { AfterViewInit, ElementRef, OnInit, OnDestroy, Renderer2, AfterContentInit, EventEmitter } from '@angular/core';

********************* My configuration is as following **************

Ionic Framework: 2.3.0
Ionic App Scripts: 1.1.4
Angular Core: 2.4.8
Angular Compiler CLI: 2.4.8
Node: 6.9.4
OS Platform: Linux 4.4
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by ihadeed** [comment]
The new version of this module (v2.0) is designed to work with Ionic 3. It uses `Renderer2` class which was introduced in Angular 4. 

I'm not sure, but I think you can upgrade your Angular version to `4.0.0` without having to upgrade `ionic-angular` to `^3.0.0`. If you have Angular 4 installed, you can ignore the unmet peer dependency warning and everything should work fine.

**Comment by anujmpec** [comment]
Ok I will try your solution but i have merge my project in ur project so it is working fine .
