### ISSUE TITLE
ionViewDidEnter is not triggered the first time in 4.1.1

### ISSUE THREAD

**Issue by adriendomoison** [zyra/ionic2-super-tabs#180]
Since update to 4.1.1 the elements loaded via ionViewDidEnter are not loaded anymore on the default page loaded by ionic2-super-tabs. ionViewDidEnter is then properly called when swiping to an other tab and swiping back.
I rolled back to 4.1.0 and the expected behavior works properly.

Thanks!

**Comment by ihadeed** [comment]
Thanks.. fixed in 4.1.3
