### ISSUE TITLE
Blank page in iOS

### ISSUE THREAD

**Issue by HyperNovax** [zyra/ionic2-super-tabs#181]
Hi,

I have a problem and I wanted to know if I'm the only one.

On iOS, (I tested on 9.3, 8.3 and 8.1) I have a blank page, except 11.0 where everything is ok.
<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="https://img15.hostingpics.net/pics/168059ios.png" border="0" alt="Hebergeur d'image" /></a>

I dowloading versions between 9.3 and 11.0 to test.

`@ionic/app-scripts : 3.0.0`
`Cordova Platforms  : android 6.1.2 ios 4.3.1`
`Ionic Framework    : ionic-angular 3.7.0`
`ionic (Ionic CLI) : 3.12.0`
`"ionic2-super-tabs": "4.0.1"`

**Comment by abervoet** [comment]
Have you checked https://github.com/zyra/ionic2-super-tabs/issues/174 ?
(i am not a contributor, just an user browsing there)

**Comment by HyperNovax** [comment]
Yep ! Is not the same problem.

I solved my problem. It's me. 

WIth blank screen on iOS
`<div *ngFor="let journee of listJournee">
      <super-tab *ngFor="let journee of listJournee" [root]="pageJournee" [rootParams]="{idEvenement: evenement.idEvenement, journee: journee}" title="{{journee.dateDisplay}}"></super-tab>
    </div> `

And the solution
`<super-tabs *ngIf="!tooMuchTab; else elseSuperTabs" toolbarColor="primary"indicatorColor="secondary" selectedTabIndex="{{selectedJournee}}"><super-tab *ngFor="let journee of listJournee" [root]="pageJournee" title="{{journee.dateDisplay}}"></super-tab>
  </super-tabs>`
