### ISSUE TITLE
Scroll Issue (all view is moving)

### ISSUE THREAD

**Issue by tompap** [zyra/ionic2-super-tabs#183]
On IOS, with buttons at the bottom of the screen.
when scroll from bottom to top inside a tab, it's working if the finger is inside the tab.
If I start scroll with my finger on the "buttons" => the full view is moving

**Comment by allanpoppe** [comment]
I'm also having this issue. @tompap did you find a solution?

**Comment by ihadeed** [comment]
If you scroll outside the tab, the page will start listening to scroll events and will scroll ..
