### ISSUE TITLE
Open new page within super tabs

### ISSUE THREAD

**Issue by ZhenweiZhang1995** [zyra/ionic2-super-tabs#184]
So I have a question about opening new pages within the super tabs.
<img width="367" alt="test" src="https://user-images.githubusercontent.com/19428188/31474838-46e2b6bc-aecb-11e7-8fd3-2907e24d60f0.png">

I want the sports detail page to be in the full screen but not under the header. What should I do?

**Comment by lukawal-miller** [comment]
Add on the first page:
`

import { NavController, NavParams } from 'ionic-angular';

export class HomePage {
rootNavCtrl: NavController;
  constructor(private navParams: NavParams) {
    this.rootNavCtrl = this.navParams.get('rootNavCtrl');
  }
}`

Then open new page with:
`  onNewPage() {
    this.rootNavCtrl.push('new-page');
  }`

**Comment by imadbakir** [comment]
why is this closed, the answer does not answer the question!
