### ISSUE TITLE
_willEnter on Page Load

### ISSUE THREAD

**Issue by danielehrhardt** [zyra/ionic2-super-tabs#186]
Hi,

i get this error on page Load
```

ERROR Error: Uncaught (in promise): TypeError: Cannot read property '_willEnter' of undefined
TypeError: Cannot read property '_willEnter' of undefined
    at super-tabs.js:429
```

**Comment by ihadeed** [comment]
What version of `ionic-angular` and `ionic2-super-tabs`?

**Comment by danielehrhardt** [comment]
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node  : v8.1.3
    npm   : 5.5.1
    OS    : macOS High Sierra
    Xcode : Xcode 9.0 Build version 9A235

Misc:

    backend : legacy
```

`"ionic2-super-tabs": "4.1.3"`

**Comment by danielehrhardt** [comment]
This Problem happens when i add this:
```
  ionViewWillEnter() {
    
  }
```
to the first Page

**Comment by ihadeed** [comment]
I haven't done any tests with `ionViewCanEnter` and `ionViewCanLeave`. My assumption is that the user should be able to enter/exit anything at anytime since the tabs are already available and rendered.

I will revisit this once I implement functionality to dynamically add/remove tabs in run-time.

**Comment by ihadeed** [comment]
Decided not to work with `canEnter`/`canLeave` lifecycles. Feel free to use https://github.com/zyra/ionic2-super-tabs#enabletabswipe to achieve required functionality.

**Comment by Eraldo** [comment]
I have the exact same error. It started showing when I added a `ionViewCanEnter` check returning false to the first page in the tabs page. Please reopen this issue.
