### ISSUE TITLE
Problem generating apk output

### ISSUE THREAD

**Issue by misterpalma** [zyra/ionic2-super-tabs#189]
Good morning my friend, I would like to report a problem that only occurs in production.

This only occurs in production: "ionic cordova run android --prod"

![yes production](https://user-images.githubusercontent.com/15263929/31615688-1facdd2e-b269-11e7-82ec-dfaf9bd58801.png)

otherwise "ionic cordova run android"
![not production](https://user-images.githubusercontent.com/15263929/31615753-5eac23cc-b269-11e7-83e3-c6579d7ba359.png)

Any idea how I can fix the problem?

Thank you!

**Comment by misterpalma** [comment]
ionic info

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1
 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v8.5.0
    npm  : 5.3.0 
    OS   : Windows 10

Misc:

    backend : pro

**Comment by dollieexloo** [comment]
I got the same problem

**Comment by chandumunna** [comment]
i got the same problem also...

**Comment by ihadeed** [comment]
Thanks.. I'll investigate this soon.

**Comment by ihadeed** [comment]
This is probably related to #174

**Comment by tomavic** [comment]
@ihadeed I had same problem 

![image](https://user-images.githubusercontent.com/17650005/32790128-3df97d00-c966-11e7-8e52-f415d5b5c895.png)


i am using super ionic template 

```
<super-tabs>
    <super-tab [root]="tab1Root" title="Home" icon="home"></super-tab>
    <super-tab [root]="tab2Root" title="Search" icon="search"></super-tab>
    <super-tab [root]="tab3Root" title="Settings" icon="cog"></super-tab>
</super-tabs>
```

I suspect it's css conflict but I have no idea how to solve it.

**Comment by ihadeed** [comment]
Closing in favour of #254  .. update to latest version & post any issues you're having on that thread.
