### ISSUE TITLE
TODO: Integrate deeplinking

### ISSUE THREAD

**Issue by ihadeed** [zyra/ionic2-super-tabs#19]
**Update**: deep linking essentially works now, but it doesn't let you automatically push pages inside one of the tabs, it just selects the tab for you automatically.

**Comment by ihadeed** [comment]
Closing this since the current deep linking works just like regular tabs.

**Comment by lesrpo** [comment]
Hello there!, I have exactly the same issue with the url on the tabs page,  localhost:8100/#//tab-1.
This problem is mentioned here https://github.com/ionic-team/ionic/issues/9012
is there any solution?

Thank you!
