### ISSUE TITLE
Ionic 3 Lazy loading not refreshing the url (always load the first tab)

### ISSUE THREAD

**Issue by vagabon** [zyra/ionic2-super-tabs#195]
Hello,

I'm using ionic2-super-tabs@4.1.3 and the the Lazy Loading !
I really enjoy it but when i want to refresh the url from my navigator, it just go to the first tab without refreshing it.

When i load my app i have the url : /tabs-page/nav/n6/theschool (someone can explain me how to change nav/n6 plz ?), then i push a new page /tabs-page/nav/n6/lessons, then F5 and the app goes to /tabs-page/nav/n6/theschool...

If i use ion-tabs i don't have this problem (just need to change the segment @IonicPage({segment: 'tabs-page'}))

Can somebody help me plz ?

**Comment by vagabon** [comment]
Hi,

Nobody is using Ionic 3 Lazy Loading and super-tabs plz ?

**Comment by Unkn0wn0x** [comment]
Can You provide us a video of the wanted / unwanted behaviour? That would be very helpful.

**Comment by ihadeed** [comment]
Deep linking is broken in Ion Tabs too .. this is an issue with the fraemwork and not supertabs.
