### ISSUE TITLE
Problem with popToRoot tab page

### ISSUE THREAD

**Issue by lukawal-miller** [zyra/ionic2-super-tabs#196]
Hi,

I'm having an issue trying to go back to the tab root page.

I've got a home page, then using navPush to go to IssuesTabs page with 3 tabs. From the root tab page I move forward to the next page using rootNavCtrl and from that page onto another one by navPush.
On finished action on that page I want to go back to IssuesTabs root page by using 
``
this.navCtrl.popTo(this.navCtrl.getByIndex(this.navCtrl.length() - 3));
``
and that works fine in the web browser but while running an app on Android device, I'm missing tabs.
I've noticed that rotating phone brings the tabs back.
Same issue hapens when I'm using: 
``
this.navCtrl.popToRoot();
``
How can I fix this issue?

EDIT: It's not only a SuperTab issue, same problem happens when using Ionic Tabs.

**Comment by ihadeed** [comment]
Not really sure what the issue is here..
But if you find the same problem with `ion-tabs`, then don't expect it to be fixed here since it's most likely an internal Ionic Framework issue that's out of my reach.
