### ISSUE TITLE
Add ability to turn tab swiping on and off

### ISSUE THREAD

**Issue by benharpers** [zyra/ionic2-super-tabs#2]
Similar to ion-menu:

```
import { SuperTabsController } from 'ionic2-super-tabs';
@Component({
  selector: 'page-some',
  template: 'hello',
})
export class SomePage {

  constructor(private tabsCtrl: SuperTabsController) {}

  ionViewDidEnter() {

    this.tabsCtrl.swipeEnable(false, 'optional tab ID to disable swiping on');
  }
  ionViewWillLeave() {

    this.tabsCtrl.swipeEnable(true, 'optional tab ID to disable swiping on');
  }
}
```

The tab ID would be set in the HTML:

`<super-tab [tabRoot]="page1" title="First page" id="mySettingsTab"></super-tab>
`

This way you can refer to it by ID rather than tab index.

**Comment by ihadeed** [comment]
Did you mean that the `id` would be passed to the `super-tabs` component instead of `super-tab`?

**Comment by benharpers** [comment]
I was thinking that an ID attribute would be better to use for referring to a tab rather than the tab index. Like if you built an app with 2 tabs and then one day you want to add a third tab to the left side, all the places you had referred to tabs by their index would now be broken. Doesn't have to be named "ID", could be like "tabName", to be consistent with "tabRoot". Either that or it could be consistent with the ion-menu, see docs here:

https://ionicframework.com/docs/v2/api/components/menu/MenuController
(see the part about "Multiple Menus on the Same Side")

**Comment by bhagwans** [comment]
im getting error "Property 'swipeEnable' does not exist on type 'SuperTabsController'." Pease help

**Comment by ihadeed** [comment]
@bhagwans please read the main documentation. If you're having trouble then you can open a new issue.
