### ISSUE TITLE
IOS problem

### ISSUE THREAD

**Issue by samuelgjabel** [zyra/ionic2-super-tabs#200]
I found some plugin bug or wtf. 
Iam using this plugin with my project and it works in browser / android as good as well. But when i build it on real IOS it has bug-y scroll (Obviously coused of ngFor loop). 
Somebody has this problem? Or some ideas how to solve it? Or just leave this plugin? Couse i cant go with this version to production. 
Thanks for advices :) 

Ionic 3.5.2

**Comment by ihadeed** [comment]
Closing this due to insufficient info. Please resubmit with code + detailed description of the issue.
