### ISSUE TITLE
Ionic 3.8.0 breaking changes

### ISSUE THREAD

**Issue by tgensol** [zyra/ionic2-super-tabs#203]
Since the new version of Ionic, I am getting these error 

`This.getContent().resize is not a function `

**Related code:**

![capture d ecran 2017-10-27 a 10 16 00](https://user-images.githubusercontent.com/7864896/32094378-dace6a02-baff-11e7-997a-93bfcd5c33a7.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v6.11.4
    npm        : 2.15.12 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004 

Environment Variables:

    ANDROID_HOME : /usr/local/opt/android-sdk

Misc:

    backend : legacy
```

Thanking you in advance,
Regards

**Comment by trytuna** [comment]
I am having the same exact error
