### ISSUE TITLE
How can I change font-size of title in super-tab

### ISSUE THREAD

**Issue by natthaphongmee** [zyra/ionic2-super-tabs#206]
I don't know how to increasing font-size of title in super-tab.

**Comment by ehdwns980416** [comment]
try this.
```
super-tabs {
    &.mainTabs>super-tabs-toolbar span.title.text {
        font-size: 14px;
    }
}
```

**Comment by ihadeed** [comment]
^

**Comment by steelhawk97** [comment]
not working

**Comment by pexlex93** [comment]
super-tabs-toolbar {
    > ion-toolbar.toolbar {
      .tab-buttons-container {
        .tab-buttons {
          super-tab-button {
            font-size: 12px;
            ion-icon {
              font-size: 29px;
            }
          }
        }
      }
    }
  }

**Comment by pexlex93** [comment]
Solution
```
  super-tabs-toolbar {
    > ion-toolbar.toolbar {
      .tab-buttons-container {
        .tab-buttons {
          super-tab-button {
            font-size: 12px;
            ion-icon {
              font-size: 29px;
            }
          }
        }
      }
    }
  }
```

**Comment by ManoMahe** [comment]
Both  are Not working in my case too

**Comment by ehdwns980416** [comment]
@ManoMahe I think it's probably a version problem. Run the app on Chrome, then check the structure through a inspect. Try to configure css according to structure, from parent to child.
