### ISSUE TITLE
Super-tabs  + google maps

### ISSUE THREAD

**Issue by xyboox** [zyra/ionic2-super-tabs#207]
Hi,
I've been trying to load a google map into one of the super-tabs but it never shows up completely, although there's no error. However, I noticed there are a lot of gmaps classes and attributes injected into super-tabs elements, in DOM. For gmaps, I'm using ionic documentation of Google Maps plugin, nothing more. 
Is the same for Android as for iOS.

Here's my system info:

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.1 
    Node       : v6.11.4
    npm        : 5.4.2 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004

**Comment by Biromain** [comment]
No problem to display native google map.
But you can have a problem with div height.

Probably can be fixed by:
```css
#map {
    height: 100%;
}
```

**Comment by ihadeed** [comment]
^
