### ISSUE TITLE
Segment buttons don't take full width and tab content height is zero.

### ISSUE THREAD

**Issue by uzumakinaruto123** [zyra/ionic2-super-tabs#209]
I am trying to test super tabs by simply copying example. But, Super tabs does not seem to work at all.

**Observations:**

1. Segment button not taking full width.
2. Tab content height is zero
3. The indicator does not show up.
4. If the 3rd tab is clicked, 1st tab content is shown. Content for rest tabs is blank.

<img src="https://user-images.githubusercontent.com/15323421/32393073-2d88cc5c-c0fe-11e7-9591-d58c185b11b7.png" width="300">

**ionic2-super-tabs -** ^4.1.4

```
ionic info

cli packages: (C:\Users\sd\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.9.0
    npm  : 5.5.1
    OS   : Windows 10
```

**Comment by christianschweiger** [comment]
Any updates on this?

**Comment by uzumakinaruto123** [comment]
Actually removing and reinstalling npm modules solved it. I don't know what was wrong. This can be closed.

**Comment by agrinko** [comment]
Just had the same issue again. Reinstalling node_modules helped. Strange issue...
