### ISSUE TITLE
I'd like to toggle of the child tabs(superTab) swipe function.

### ISSUE THREAD

**Issue by Bandcy** [zyra/ionic2-super-tabs#211]
first of all, very thank you for your work. It's really nice. :)

I'd like to give swipe-able right only under some condition.

for example.
tab has some input control and that is necessary field.
so until the control filled, user can't leave it.

I tried extends SuperTab. (add some @Output to EmitEvent) but failed.

How can I do?
thanks.

**Comment by ihadeed** [comment]
https://github.com/zyra/ionic2-super-tabs#enabletabsswipe
