### ISSUE TITLE
Toolbar titles are superimposing on each other 

### ISSUE THREAD

**Issue by ajinkyaaj23** [zyra/ionic2-super-tabs#212]
I have total 5 tabs ... 5 pages are there for each tab ... i have problem with the titles only which are one over the other ...   my code is below and i am attaching a screenshot also.

Please help me.

<ion-content>
    <super-tabs 
       scrollTabs toolbarColor="light" selectedTabIndex="0"  toolbarBackground="dark" 
     indicatorColor="light">

        <super-tab class="super-tabs-toolbar" [root]="callRecordingsRoot" title="Call Recordings"></super-tab>
        <super-tab class="super-tabs-toolbar" [root]="offlineLeadsRoot" title="Offline Leads"></super-tab>
        <super-tab class="super-tabs-toolbar" [root]="previousLeadsRoot" title="Previous Leads"></super-tab>
        <super-tab class="super-tabs-toolbar" [root]="todaysLeadsRoot" title="Todays Leads"></super-tab>
        <super-tab class="super-tabs-toolbar" [root]="upcomingLeadsRoot" title="Upcoming Leads"></super-tab>

    </super-tabs>
</ion-content>

![screenshot_20171109-180039](https://user-images.githubusercontent.com/33453476/32605730-9251c9f8-c578-11e7-9ed4-d541aa562847.png)
![screenshot_20171109-180046](https://user-images.githubusercontent.com/33453476/32605731-92963d0e-c578-11e7-9fe5-e5a244edfb59.png)

**Comment by wilson0506** [comment]
same issue here, appear on android

**Comment by leoruhland** [comment]
https://github.com/zyra/ionic2-super-tabs/issues/199#issuecomment-338765548

**Comment by ihadeed** [comment]
Will be fixed in the next release, tonight.
