### ISSUE TITLE
Pushing a page inside super-tabs causes it to stay within the tabs

### ISSUE THREAD

**Issue by Simbaclaws** [zyra/ionic2-super-tabs#213]
Greetings,

I have a situation where I want to push the navigation of specific pages to take full width and height of the entire application. (This is for some specific pages only).

Currently when I push any page on top of the stack that is inside of super-tabs, it will stay inside of the super tabs making the page still swipeable to other super-tabs. I would like to have specific pages to be pushed to a fullscreen layout rather then having it stay inside the super-tabs. Is there any way I can accomplish this?

Suppose for example that I have a page with google maps opening from the navigation stack. Whenever this page is inside of super-tabs, it would make it impossible to use swipe gestures on the google maps page because it would swipe to the next super-tabs tab.

Here is an example of what I mean:

<img width="433" alt="schermafbeelding 2017-11-09 om 16 17 59" src="https://user-images.githubusercontent.com/12895506/32612909-c0c98636-c569-11e7-9fb3-f8f0c77a887a.png">

I would like this "kaart" page to be pushed on top of the root page containing the super-tabs, so that swiping won't be an issue...

Any idea how I could accomplish this without losing the navigation stack? Like pop?

EDIT: I fixed it by using: `this.app.getRootNavs()[0].push` this issue can be closed. It now works as intended...
Example:
<img width="431" alt="schermafbeelding 2017-11-09 om 16 52 15" src="https://user-images.githubusercontent.com/12895506/32614841-6aa2ec70-c56e-11e7-97a0-20301bdcfa0c.png">

**Comment by trytuna** [comment]
Are you able to use the "swipeBack" gesture?

**Comment by ihadeed** [comment]
Use `rootNavCtrl` https://github.com/zyra/ionic2-super-tabs#rootparams

**Comment by senturkzuhtu11** [comment]
@ihadeed  how to ?? use rootNavCtrl

**Comment by Geraldojrcg** [comment]
@senturkzuhtu11 try this `this.appCtrl.getRootNav().push(page);`

**Comment by danielfelipe113** [comment]
How do you solve this in Ionic 4?
