### ISSUE TITLE
Tabs titles alignment changed since upgrade to Chrome62

### ISSUE THREAD

**Issue by clementcontet** [zyra/ionic2-super-tabs#214]
It's very strange, since I upgraded to Chrome62, the alignment of my titles went slightly wrong.
If I revert to old Chrome version, everything goes back to normal.
Looks like the WebView engine of Chrome62 deals differently with some CSS of super tabs.

Old Chrome:
![before chrome62](https://user-images.githubusercontent.com/7261426/32617057-4532ecb4-c574-11e7-917d-c9d0c8d2bb33.jpg)

New Chrome62:
![after chrome62](https://user-images.githubusercontent.com/7261426/32617062-48635130-c574-11e7-8aee-a43c3dd4c15d.jpg)

For information, here are all my modules:

- "angular/common": "4.4.4",
- "angular/compiler": "4.4.4",
- "angular/compiler-cli": "4.4.4",
- "angular/core": "4.4.4",
- "angular/forms": "4.4.4",
- "angular/http": "4.4.4",
- "angular/platform-browser": "4.4.4",
- "angular/platform-browser-dynamic": "4.4.4",
- "ionic-native/core": "4.3.3",
- "ionic-native/firebase-analytics": "4.3.3",
- "ionic-native/splash-screen": "4.3.3",
- "ionic-native/status-bar": "4.3.3",
- "ionic/storage": "2.1.3",
- "cordova-android": "6.3.0",
- "cordova-ios": "4.5.3",
- "cordova-plugin-device": "1.1.6",
- "cordova-plugin-firebase-analytics": "0.12.0",
- "cordova-plugin-splashscreen": "4.0.3",
- "cordova-plugin-statusbar": "2.2.3",
- "cordova-plugin-whitelist": "1.3.2",
- "cordova-support-google-services": "1.0.0",
- "ionic-angular": "3.8.0",
- "ionic-plugin-keyboard": "2.2.1",
- "ionic2-super-tabs": "4.1.4",
- "ionicons": "3.0.0",
- "moment": "2.19.1",
- "ng-elastic": "1.0.0-beta.3",
- "rxjs": "5.4.3",
- "sw-toolbox": "3.6.0",
- "zone.js": "0.8.18",
- "cordova-plugin-console": "1.0.5"

**Comment by italorio** [comment]
here too :(

**Comment by matthildenbrand** [comment]
I had the same issue, see css fix here:

https://github.com/zyra/ionic2-super-tabs/issues/199#issuecomment-338765548

**Comment by clementcontet** [comment]
Yes thanks!

**Comment by ihadeed** [comment]
Will be fixed in the next release, tonight.
