### ISSUE TITLE
Tab Indicator does not move when using onSwipe event

### ISSUE THREAD

**Issue by abaginski** [zyra/ionic2-super-tabs#215]
hi guys, 

I have discovered a weird bug when using the slideTo Method at an onSwipe event, where the Tab indicator does not move away from the current Tab. Please have a look at my code:
`<super-tabs (swipe)="onSwipe($event)">`

```
  onSwipe(event) {
    let currentTabIndex = this.superTabs.selectedTabIndex;
    let lastIndex = 3;
    if(currentTabIndex == 0 && event.direction == 4) {
      this.superTabsCtrl.slideTo(lastIndex);
    }
    else if(currentTabIndex == lastIndex && event.direction == 2)
      this.superTabsCtrl.slideTo(0);
  }
```

so at this point, everything works accordingly, but it only slides the content and not the blue border indicator on the super-tabs. I am sure that this is some kind of behind the curtains issue. Here you can see the result: [http://i.imgur.com/MerbYjsr.png](http://i.imgur.com/MerbYjsr.png) . Although the current Page is "Arbeit 4.0", the red border is still at "Home".

If I use `this.superTabsCtrl.slideTo(3)` somewhere else, it works properly (I tried a function call after clicking on a link), so this issue is only related to the onSwipe event of SuperTabs.

kind regards and thanks in advance for the help
Adrian

**Comment by Unkn0wn0x** [comment]
I hope I understood your problem correctly.

Did You tried to use `(tabSelect)="onTabSelect($event)"` like it's documented in the `README.md`?

In the function You should be able to get the required data for Your case.

```
onTabSelect(ev: any) {
    console.log('Tab selected', 'Index: ' + ev.index, 'Unique ID: ' + ev.id);
  }
```

Cheers
Unkn0wn0x
