### ISSUE TITLE
super-tabs.scss is missing from npm install

### ISSUE THREAD

**Issue by ejaz47** [zyra/ionic2-super-tabs#218]
Just tried to follow installation instruction,
got everything except the style was missing.

Reproduce steps : 
1. **npm i --save ionic2-super-tabs**
2. look into **node_modules/ionic2-super-tabs/dist/components**  here **unfortunately missing super-tabs.scss**.

**$ ionic -v
3.12.0**

**$ cordova -v
7.0.1**

**$ npm -v
3.10.10**

**$ node -v
v6.11.3**

For the hack i am creating one manually.

Thanks.

**Comment by niinortey** [comment]
This indeed is whats causing issue #217 
Manually copying [https://raw.githubusercontent.com/zyra/ionic2-super-tabs/master/src/components/super-tabs.scss](url) into **node_modules/ionic2-super-tabs/dist/components** solves it.

**Comment by ejaz47** [comment]
Should i manually copy the source or **revert to Version 4.1.4**?

**Comment by scalpel4k** [comment]
Hi, it seems only an issue with the published package. When I build it manually from source the css file gets transpiled and copied into the dist package.

**Comment by riverbridgeventures** [comment]
Thanks @niinortey, @scalpel4k  closing...

**Comment by ejaz47** [comment]
Closing it...

**Comment by elmartino** [comment]
Why are you closing it? The problem still persists.. Manually copying the css file in the node_modules folder fixes the issue..

**Comment by ejaz47** [comment]
Already there's an opened issue #217 regarding the same as this issue so opening this issue not makes sense.
