### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by italorio** [zyra/ionic2-super-tabs#220]
Last original version , presents error in tab and in text

![captur1e](https://user-images.githubusercontent.com/2882342/32842170-88578804-ca03-11e7-8e21-48be267473c2.PNG)
![capture](https://user-images.githubusercontent.com/2882342/32842188-8f22ff4c-ca03-11e7-8684-acfc94eb3288.PNG)

**Comment by Unkn0wn0x** [comment]
A bit more debug information would be helpful.

I think this issue is related to #218 or #217 

If You stay with v4.1.4, You should be fine.

Cheers
Unkn0wn0x

**Comment by ejaz47** [comment]
@Unkn0wn0x, even V4.1.4 has the same issue,

I have resolved this issue by editing the css styles of **super-tab-button**,
Just add the following scss,

```
ion-toolbar.toolbar{
	.tab-buttons-container{
		.tab-buttons{
			super-tab-button{
				flex: none;
			}
		} 
	} 
}
```

**Comment by ihadeed** [comment]
Will be fixed in the next release, tonight.
