### ISSUE TITLE
page cannot be loaded when using lazy loading (blank)

### ISSUE THREAD

**Issue by amanjazari** [zyra/ionic2-super-tabs#221]
i have tried the sample code but still not work.

<super-tabs id="mainTabs" selectedTabIndex="1" toolbarColor="light" toolbarBackground="dark" indicatorColor="light" badgeColor="light" [config]="{ sideMenu: 'left' }" (tabSelect)="onTabSelect($event)">
  <super-tab [root]="page1" title="First page" icon="home" id="homeTab"></super-tab>
  <super-tab [root]="page2" title="Second page" icon="pin" id="locationTab"></super-tab>
  <super-tab [root]="page3" title="Third page" icon="heart" id="favouritesTab"></super-tab>
</super-tabs>

**Comment by Unkn0wn0x** [comment]
This code snippet is not very useful, You should give us a few lines more so that we can help you.

**Comment by lukawal-miller** [comment]
Did you import SuperTabsModule in your tabs module page?

**Comment by phantoxe** [comment]
I have the same problem... :-( And i already import SuperTabsModulo... can you help me please?

**Comment by ihadeed** [comment]
Works in the example project..
