### ISSUE TITLE
Single Tab Icon and Text color dynamically

### ISSUE THREAD

**Issue by leobenini** [zyra/ionic2-super-tabs#223]
Hi, 
first of all, thank you for your great work!

I'm wondering if there is the possibility to color the single tab by code, for example a red color if the corresponding tab-page has a problem, or green color if the data in the relative page are all ok.

Another interesting features would be to block the swipe or access with click for some pages, in order to make a guided entry data by tabs, where the next tab is accessible only if all data are correct in the current.

Regards, 
Leonardo Benini

**Comment by ihadeed** [comment]
- No it's not possible to set the color for a single tab. However, you can achieve that by using custom CSS selectors. 

- Interesting feature, I'm open to adding it. Most likely I'll make the `super-tabs` element respect the `ionViewCanEnter` and `ionViewCanLeave` methods of child tabs.

**Comment by ihadeed** [comment]
Decided not to respect Ionic's `ionViewCanLeave` and `ionViewCanEnter`. It will cause issues & confusion for some users. This module preloads tabs when they're next in line, so when the user swipes right/left they will be able to see some content. 

You can use https://github.com/zyra/ionic2-super-tabs#enabletabswipe to disable swiping until the required info is filled out.
