### ISSUE TITLE
Maximum number of tabs

### ISSUE THREAD

**Issue by sevekim** [zyra/ionic2-super-tabs#224]
Hi.

I have been enjoying yours alot! I just have a quick question. 

In my application, I have unlimited tabs as. For performance perspective, I am trying to delete or remove previous tabs that are not "current tab", "previous tab" and "next tab" (Meaning, only three at any given time).

Would you have any suggestion how I can go about?

Thanks!

**Comment by ihadeed** [comment]
This is not possible at the moment but it's on the road map.

**Comment by sevekim** [comment]
Okay Thanks bud!
