### ISSUE TITLE
ios navigation bar problem

### ISSUE THREAD

**Issue by LtotheWT** [zyra/ionic2-super-tabs#226]
Hi ihadeed, i am really thankful for ur swiping tabs. 
Here i notice a problem when i implement this swiping tabs on ios emulator.
<img width="296" alt="screen shot 2017-11-24 at 10 20 19 pm" src="https://user-images.githubusercontent.com/13746657/33214247-0ba93cca-d166-11e7-8d1d-df33d0d7ec80.png">

**Comment by silverio** [comment]
same problem here, have you been able to fix it?

**Comment by ihadeed** [comment]
Unable to reproduce with latest Ionic + Super tabs versions.
