### ISSUE TITLE
super tabs not working properly

### ISSUE THREAD

**Issue by Gurudathputankar** [zyra/ionic2-super-tabs#230]
i am getting page like this
![image](https://user-images.githubusercontent.com/25527242/33594408-abd96da4-d9b9-11e7-8fd7-93f1ddeac8f3.png)

my code is <ion-content no-bounce>
  <super-tabs scrollTabs selectedTabIndex="1" toolbarColor="light" toolbarBackground="dark" indicatorColor="light" (tabSelect)="onTabSelect($event)">
    <super-tab [root]="page1" title="First page" icon="home" id="homeTab"></super-tab>
    <super-tab [root]="page2" title="Second page" icon="pin" id="locationTab"></super-tab>
    <super-tab [root]="page3" title="Third page" icon="heart" id="favouritesTab"></super-tab>
  </super-tabs>
</ion-content>

import { Component, ViewChild } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Page1Page } from '../page1/page1';
import { Page2Page } from '../page2/page2';
import { Page3Page } from '../page3/page3';
import { SuperTabs, SuperTabsController } from 'ionic2-super-tabs';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  @ViewChild(SuperTabs) superTabs: SuperTabs;

  page1: any = Page1Page;
  page2: any = Page2Page;
  page3: any = Page3Page;

  constructor(public navCtrl: NavController, private superTabsCtrl: SuperTabsController) {

  }
  slideToIndex(index: number) {
    this.superTabs.slideTo(index);
  }

  hideToolbar() {
    this.superTabs.showToolbar(false);
  }
  ngAfterViewInit() {
    // this.superTabsCtrl.increaseBadge('page1', 10);
    // this.superTabsCtrl.enableTabSwipe('page3', false);
    this.superTabsCtrl.enableTabsSwipe(true);
    // Test issue #122
    setTimeout(() => {
      this.superTabs.slideTo(2);
    }, 2000);
  }
  onTabSelect(ev: any) {
    console.log('Tab selected', 'Index: ' + ev.index, 'Unique ID: ' + ev.id);
  }
}

please provide proper example

**Comment by jasonz1987** [comment]
+1 meet  the same isuue when i update to 4.5.1

**Comment by Gurudathputankar** [comment]
hai i solved this by using ionic2-super-tabs@4.0.0  and used css 
 super-tabs {
        super-tab-button {
            flex: 0 0 auto !important;
        }
    }


but only issue i am facing is when i go to some page from super tab page and come back  tabs went left and content will not show.

any suggestion ?

thanks in advance

**Comment by vinigg2** [comment]
Thanks @Gurudathputankar
