### ISSUE TITLE
How to scroll root page content from the super tabs(parent) page

### ISSUE THREAD

**Issue by Topiya** [zyra/ionic2-super-tabs#231]
Hello,
Currently super-tabs are fix and not able to scroll along with the root page content scroll.
As an alternative way we will be able to move tabs up if the root page contents are scrolling from parent page(super-tabs page).
So can anyone please provide any solution that how to scroll root page content from the parent(super-tabs) page?

**Comment by jonathan1138** [comment]
Or vice versa, how to notify the super tabs page / parent template of a scroll event at the child "root" level. Thanks.

**Comment by ihadeed** [comment]
Root page will only listen to scroll event if (1) you've already scrolled all the way to the top/bottom of the `super-tab` page,, or (2) you scroll outside the `super-tabs` component. This is the case with any other HTML element.. not just super tabs.

**Comment by DokunCodes** [comment]
What's the work around this; that ensure when the super tabs is scrolled; it pushes the root page also
