### ISSUE TITLE
Hide Tab On Sub Pages, Please!

### ISSUE THREAD

**Issue by lightyaer** [zyra/ionic2-super-tabs#232]
I am in the process of developing an multilayered application which requires tab inside tab inside tab and so on for at least 5 layers, and wasn't impressed with ion-tabs appearance and no swipe feature, and thought of using super tabs, but super-tabs has no remedy to use the above mentioned, and I'm not inclined to use the CSS display: none and block, so can you please add the HideTabsOnSubPage=true feature, Since the new Version(4.1.5) has some bug for not displaying the tabs properly, can you please implement the above feature also.
Thanks in Advance,
Regards.

**Comment by lightyaer** [comment]
So Sorry, The issue was with my architecture, Fixed it, Don't need the hideTabsonSubPage Thank You Anyways!

**Comment by heidji** [comment]
could please say how you fixed it?

**Comment by anandraj9497** [comment]
Hi, Is there any way to fix it? Facing the same issue

**Comment by lightyaer** [comment]
2 things, the navcontroller is a bit fishy, each page has a separate navcontroller, Google about navcontroller to know more, what you need to do is access the rootnavcontroller of the starting page, let's say dashboard page, and push tabspages to it 

2nd thing. You can't have one tabs page, and dynamically change it whenever, you need to have separate tabs page for wherever it's required..

**Comment by anandraj9497** [comment]
@lightyaer So How can we navigate back to the previous menu? `this.naVctrl.pop()`,`this.naVctrl.parent.parent.popToRoot()` is not working

**Comment by lightyaer** [comment]
Access the root nav controller by using app(lib in ionic-angular ) in the constructor in each page and just do push or pop to it

**Comment by anandraj9497** [comment]
Can you share the code please?
