### ISSUE TITLE
the modal window over the super tabs is only showed a part of the all.

### ISSUE THREAD

**Issue by cloudswhere** [zyra/ionic2-super-tabs#233]
when I create the modal window over the super tabs, it only show a part of the modal window.

**Comment by Unkn0wn0x** [comment]
@cloudswhere I don't think this is a bug. You just need to open the modal on the correct navController.

If You take a look at the documentation, there is mentioned, that the super-tab component passes `rootNavCtrl` as a parameter on `rootParams`. 

You need to get this `rootNavCtrl` inside Your opened page (super-tabs child page) and open there the modal on this (`rootNavCtrl`) navController.

Something like this: 

```
protected _navCtrl = this.navParamCtrl.get('rootNavCtrl');

this._navCtrl.openModal(); <- Or whatever You want to do here.
```

**Comment by ihadeed** [comment]
^
