### ISSUE TITLE
issues with updated version of ionic 3.18.0

### ISSUE THREAD

**Issue by tejas008** [zyra/ionic2-super-tabs#234]
when i updated ionic-cli to 3.18.0 .This great plugin is not supporting the newer version of ionic.please work on it.otherwise i have to change my whole  project structure and it will be very complex to do..so please solve these problem. This is screenshot of errors.Thank you for your great work..

**Comment by chrisweight** [comment]
No screenshot?

**Comment by tejas008** [comment]
sorry for my mistake.....@chrisweight

![screenshot 3](https://user-images.githubusercontent.com/34152354/33701401-9a369f90-db44-11e7-81ef-e51c9f4ea740.png)

**Comment by tejas008** [comment]
sorry for my mistake..
these are screenshot..
![screenshot 3](https://user-images.githubusercontent.com/34152354/33701461-d67253f0-db44-11e7-9d07-fdb0a5f0a5f2.png)
![screenshot 4](https://user-images.githubusercontent.com/34152354/33701462-d6985e9c-db44-11e7-99e7-69af295a5320.png)
