### ISSUE TITLE
super tabs have some issue in ionic 3

### ISSUE THREAD

**Issue by Gurudathputankar** [zyra/ionic2-super-tabs#236]
i am facing issue  when i go to some page from super tab page and come back tabs went left and content will not show.

any suggestion ?

thanks in advance

![screenshot_20171214-114249](https://user-images.githubusercontent.com/25527242/34026553-e9952ce4-e17c-11e7-8a9f-5b72e8bd17e1.png)

**Comment by gokujy** [comment]
where is example or a code to know what error and why coming error?
