### ISSUE TITLE
page contents can't load & tabs are left-justified

### ISSUE THREAD

**Issue by YamanSehzade** [zyra/ionic2-super-tabs#237]
## page contents can not load and tabs are left-justified
Could you help me please ?

**ionic info**
cli packages: (C:\Users\user\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

local packages:

    @ionic/app-scripts : 3.1.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.3
    npm  : 5.6.0
    OS   : Windows 10`

**package.json**
` {
  "name": "super-tab",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "5.1.1",
    "@angular/compiler": "5.1.1",
    "@angular/compiler-cli": "5.1.1",
    "@angular/core": "5.1.1",
    "@angular/forms": "5.1.1",
    "@angular/http": "5.1.1",
    "@angular/platform-browser": "5.1.1",
    "@angular/platform-browser-dynamic": "5.1.1",
    "@ionic-native/core": "4.5.2",
    "@ionic-native/splash-screen": "4.5.2",
    "@ionic-native/status-bar": "4.5.2",
    "@ionic/storage": "2.1.3",
    "ionic-angular": "3.9.2",
    "ionic2-super-tabs": "^4.1.5",
    "ionicons": "3.0.0",
    "rxjs": "5.5.5",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.5",
    "typescript": "2.6.2"
  },
  "description": "An Ionic project"
}`

**github:** https://github.com/YamanSehzade/supertabs-test
**overview:**
![image](https://user-images.githubusercontent.com/22771125/34040777-9278bf16-e195-11e7-95be-4e6036c95052.png)

**Comment by YamanSehzade** [comment]
"ionic2-super-tabs": "^4.1.5" **did not work**
"ionic2-super-tabs": "^4.1.4" **worked**

**Comment by deltamish** [comment]
Hey!
I have exact same issue and i tried changing  from 4.1.5 to 4.1.4 in packages.json
but nothing happened
Do help me find a solution

**Comment by YamanSehzade** [comment]
it's ridiculous, but it's not working with `npm install` 
**after** `npm install` **finished**

I just did this and app worked
```
npm uninstall --save ionic2-super-tabs
npm install --save ionic2-super-tabs@4.1.4
```
