### ISSUE TITLE
swipeBackEnabled attribute

### ISSUE THREAD

**Issue by benharpers** [zyra/ionic2-super-tabs#24]
If you have a chance, it should be pretty easy to pass the swipeBackEnabled attribute from super-tab to the nav. In some apps there just may be too many swipe-able elements.

https://ionicframework.com/docs/api/components/nav/Nav/

**Comment by ihadeed** [comment]
Sure I can add this. In the new version `super-tab` is a `nav` instance, it just needs an input to set the property.

**Comment by ihadeed** [comment]
This is now added in `ionic2-super-tabs@2.3.0`
