### ISSUE TITLE
Page Content Blank Ionic Super Tabs 

### ISSUE THREAD

**Issue by deltamish** [zyra/ionic2-super-tabs#240]
Hey,

I have been trying to use super tabs for quite sometime. But I seem to face this weird problem of Pages not being displayed / Pages being blank and empty 

![image](https://user-images.githubusercontent.com/9283808/34320171-70ba27f4-e819-11e7-991e-2658fef6848b.png)

## 
With Regular ion-tabs this is what i get 

![image](https://user-images.githubusercontent.com/9283808/34320188-03c70166-e81a-11e7-992d-742fa2f41f5f.png)

**Tabs.html**
![image](https://user-images.githubusercontent.com/9283808/34320156-562a0486-e819-11e7-8755-53205dd159fe.png)

**Tabs.ts**
![image](https://user-images.githubusercontent.com/9283808/34320179-b7207748-e819-11e7-977e-a2a6432a9d42.png)

**ionic info**
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.6.0
    npm  : 5.3.0 
    OS   : Linux 4.10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by eudennis** [comment]
Got a similar error while trying to use it.

**Comment by Zokor** [comment]
Got the same issue.

With my own installation and also with the sample project.

**Comment by Zokor** [comment]
Solution:

Copy -> https://raw.githubusercontent.com/zyra/ionic2-super-tabs/master/src/components/super-tabs.scss 

To -> node_modules/ionic2-super-tabs/dist/components

**Comment by elbidone** [comment]
thanks @Zokor works for me

**Comment by eduardoRoth** [comment]
Version 4.1.5 doesn't copy super-tabs.scss for production build, a pull request has been sent by @gvhuyssteen based on comments of @allanpoppe

https://github.com/zyra/ionic2-super-tabs/pull/248

**Comment by gvhuyssteen** [comment]
I added a temporary solution for now in the comments of my PR #248.
This will allow you to save the solution to GitHub as part of your repository.

**Comment by ihadeed** [comment]
Will be fixed in next release tonight.
