### ISSUE TITLE
swipe not working

### ISSUE THREAD

**Issue by Muthunayake** [zyra/ionic2-super-tabs#242]
hi
i'm new to super tabs.
i set up all the thing and working well except swipe functionality.
is there any thing to add to my code 

my ionic version is 3.19

here is my code
 <super-tabs  id="mainTabs" (tabSelect)="onTabSelect($event)">
  <super-tab [root]="page1" title="First page" id="tab1"></super-tab>
  <super-tab [root]="page2" title="Second page" id="tab2"></super-tab>
  <super-tab [root]="page3" title="Third page" id="tab3"></super-tab>
</super-tabs>

**Comment by Unkn0wn0x** [comment]
Can You provide us more information/s, to be able to help You debugging? Like a short video, code snippets, or something else?

**Comment by Muthunayake** [comment]
thanks for replay..

it's working with mobile app.but it's not working with web browser.

**Comment by ihadeed** [comment]
Desktop support isn't implemented yet. Follow #21
