### ISSUE TITLE
Header title clumped together

### ISSUE THREAD

**Issue by sevekim** [zyra/ionic2-super-tabs#244]
I got a fresh Ionic installed and ionic2-super-tabs and nothing else.

I also followed a temporary solution of [saving super-tabs.scss file ](https://github.com/zyra/ionic2-super-tabs/issues/240).

When the "scrollable" in <super-tabs> is enabled, all the titles are clumped up together:

![scrollable](https://user-images.githubusercontent.com/11042584/34591276-81125a18-f179-11e7-9295-e1de028b3958.JPG)

With a fresh install, there isn't much to show
![code](https://user-images.githubusercontent.com/11042584/34591316-af6def30-f179-11e7-8ec9-894e0689c98f.JPG)

Does anyone know what the issue here is??

**Comment by ihadeed** [comment]
https://github.com/zyra/ionic2-super-tabs/issues/108

**Comment by ihadeed** [comment]
Fixed in recent commit and will be available in the next release.
