### ISSUE TITLE
Issues with scrollTabs 

### ISSUE THREAD

**Issue by duy205711** [zyra/ionic2-super-tabs#245]
Hello, i'm try using super-tabs with scrollTabs, but it not work.
my code: 
`<super-tabs [config]="{ sideMenu: 'left' }" scrollTabs="true">
    <super-tab *ngFor="let tab of listTabCategory" title="{{tab.title}}" [root]="tab.page" ></super-tab>
  </super-tabs>`
out put screen:

[http://sv1.upsieutoc.com/2018/01/05/Screenshot-from-2018-01-05-15-49-45.png](http://sv1.upsieutoc.com/2018/01/05/Screenshot-from-2018-01-05-15-49-45.png)

I use ionic: 3.19.0,  "ionic2-super-tabs": "^4.0.1"
Please help me. Thanks!

**Comment by eduardoRoth** [comment]
Can you try with fixed `super-tab` components,

```
<super-tabs [config]="{ sideMenu: 'left' }" scrollTabs="true">
    <super-tab [title]="Title1" [root]="Tab1"></super-tab>
    <super-tab [title]="Title2" [root]="Tab2"></super-tab>
    <super-tab [title]="Title3" [root]="Tab3"></super-tab>
    <super-tab [title]="Title4" [root]="Tab4"></super-tab>
    <super-tab [title]="Title5" [root]="Tab5"></super-tab>
    <super-tab [title]="Title6" [root]="Tab6"></super-tab>
    <super-tab [title]="Title7" [root]="Tab7"></super-tab>
</super-tabs>
```

Just to be sure it's nothing to do with dynamically creating the tabs components.

**Comment by duy205711** [comment]
Thank @eduardoRoth I think i Have same issue with [https://github.com/zyra/ionic2-super-tabs/issues/251](251)

**Comment by ihadeed** [comment]
Fixed in recent commit. Fix will be available in next release.
