### ISSUE TITLE
Not working with tabs template

### ISSUE THREAD

**Issue by mikemichaelis** [zyra/ionic2-super-tabs#246]
ionic start tabs tabs
cd tabs
npm install ionic2-super-tabs --save
ionic cordova prepare

edit app.module.ts
import { SuperTabsModule } from 'ionic2-super-tabs';
imports [ ... SuperTabsModule.forRoot() ]

edit tabs.html
<super-tabs>
  <super-tab [root]="tab1Root" title="Home" icon="home"></super-tab>
  <super-tab [root]="tab2Root" title="About" icon="information-circle"></super-tab>
  <super-tab [root]="tab3Root" title="Contact" icon="contacts"></super-tab>
</super-tabs>

ionic serve
![screenshot from 2018-01-07 18-39-44](https://user-images.githubusercontent.com/1304122/34655595-307095da-f3da-11e7-8e83-fd7dda896ca0.png)

**Comment by eduardoRoth** [comment]
Hi @mikemichaelis , if you're installing version 4.1.5 it currently has a missing file, install version 4.1.4 with `npm i ionic2-super-tabs@4.1.4 --save` or in the ionic2-super-tabs inside node_modules paste the file super-tabs.scss in the following route: `node_modules/ionic2-super-tabs/dist/components`.

That'll work. There's already a pull request for this problem: https://github.com/zyra/ionic2-super-tabs/pull/248

**Comment by gvhuyssteen** [comment]
I added a temporary solution for now in the comments of my PR #248.
This will allow you to save the solution to GitHub as part of your repository.

**Comment by ihadeed** [comment]
Will be fixed in the next release, tonight.
