### ISSUE TITLE
The tab title is overwriting.

### ISSUE THREAD

**Issue by dharmendrasingh1983** [zyra/ionic2-super-tabs#249]
The tab title is overwriting on add scrollTabs. Please fixed issue
![capture](https://user-images.githubusercontent.com/35372045/34876749-fa3d749a-f7c8-11e7-9a64-0bdf04e8b9a3.JPG)

**Comment by eduardoRoth** [comment]
I had this problem, a quick workaround is to modify the `super-tab-button` font-size:
```
super-tab-button {
        text-transform: none!important;
        font-size: 0.65em!important;
}
```
*I also hate the uppercase title hahaha*

Size it to your liking. Hope this helps

**Comment by dharmendrasingh1983** [comment]
It gets very small buttons. it is not well. Please give more idea.

**Comment by eduardoRoth** [comment]
Well, you can change font size for your liking, probably 0.8em will fit without overlapping.

Also, for this case when you have a lot of tabs, it's better to have scrollTabs attribute set to true.

```
scrollTabs
(optional) Set to true to enable tab bar swiping. Useful if you have lots of tabs.
```

**Comment by ihadeed** [comment]
Fixed in recent commit. Fix will be available in next release.
