### ISSUE TITLE
Error loading with lazy loading

### ISSUE THREAD

**Issue by duckls** [zyra/ionic2-super-tabs#250]
![wx20180115-212433](https://user-images.githubusercontent.com/17420479/34944433-82f98db4-fa3a-11e7-8aaf-32caff0f1989.png)

In the module.ts file used, demo shared. module.ts.

**Comment by eduardoRoth** [comment]
Hi @duckls , can you please paste your `module.ts` code? It seems you're trying to inject SuperTabsController in one of your components without importing SuperTabsModule in your module.

**Comment by eduardoRoth** [comment]
Problem was that SuperTabsModule wasn't been imported in app.module.ts

**Comment by ihadeed** [comment]
You need to import `SuperTabsModule.forRoot()` somewhere..
Either in your app's root module, or in the module containing that page (recommended only if you have a single instance of `super-tabs`)
