### ISSUE TITLE
Broken layout when scrollTabs is enabled

### ISSUE THREAD

**Issue by leotleal** [zyra/ionic2-super-tabs#251]
I need to set scrollTabs to true because I have many items to show as tabs but my tab's names are a little long and the title of the tab is broken in a device.

I think it's because this configurations bellow:

toolbar.toolbar.scroll-tabs .tab-buttons-container .tab-buttons super-tab-button {
    min-width: 50px;
    max-width: 100%;
    width: auto;
    display: inline-table;
    overflow: visible;
}

(min-width: 50px) is not sufficient for to show my title

How can I fixed this issue?

**Comment by leotleal** [comment]
I think just removing min-width: 50px and leaving width: auto fixed this issue.

**Comment by duy205711** [comment]
@leotleal  I have same issue [245](https://github.com/zyra/ionic2-super-tabs/issues/245) and I change min-width: 50px to width: auto

**Comment by ihadeed** [comment]
Fixed in recent commit. Fix will be available in next release.
