### ISSUE TITLE
The layout from the basic example is not the proper one with the same code

### ISSUE THREAD

**Issue by dndonev** [zyra/ionic2-super-tabs#252]
Hey, I'm having an issue to load the basic example... I literally don't know why this is happening, i followed 3 different examples for super-tabs but i get the same thing
1. when I put SuperTabsModule.forRoot() in the imports of app.module.ts i get broken layout
    ( https://imgur.com/a/LwJTn )
2. when i put SuperTabsModule (only) there I get [SuperTabsController] error
    ( https://imgur.com/a/QbRUP )

**Comment by ihadeed** [comment]
Try the latest version .. you're probably using that one version with the missing SCSS File.

**Comment by dndonev** [comment]
@ihadeed  Yes, I digged up some previous threads and saw for the mising SCSS and copied it manually in 4.1.5 (i think this is the latest version), but the solution for me was downgrading to 4.1.4 where the package is all good and running npm install gets the SCSS file as expected. Thank you. Nice job!
