### ISSUE TITLE
Unexpected value SuperTabsModule

### ISSUE THREAD

**Issue by lucapale** [zyra/ionic2-super-tabs#255]
After upgrading from 4.1.4 to 4.2.1 I get this error:
"unexpected value SuperTabsModule in ComponentsModule please add ngmodule annotation"

I have a shared Components module for lazy loading of pages.
Any idea how to fix it?
Thanks
Luca

**Comment by leonardosalles** [comment]
I have the same issue, ionic 3.9.2 and super tabs 4.2.1 even for lazy loading and forRoot method.

**Comment by silverio** [comment]
I have the same problem

**Comment by ihadeed** [comment]
Thanks for reporting this.

Just published 4.2.2 with a fix. Please let me know if you still have issues.
