### ISSUE TITLE
Feature: Swipeable segments followed by tabs (not a bug)

### ISSUE THREAD

**Issue by Chethannp** [zyra/ionic2-super-tabs#257]
Hey Hi… First of all thank you so much for this solution on swipeable tabs…!!! very useful…

I need some suggestions on the following:
I am stuck in a situation where the Home page tab has segments in it. Now when the user swipes left it should switch the segments and once the end of segment is reached then the next swipe should switch the tabs. Please let me know if this is achievable with your above solution. Badly in need of a solution for this requesting you to please help me…
[https://forum.ionicframework.com/t/ionic-swipeable-tabs-are-now-here/84266/134](url) 

I have posted the same on the ionic forum.

Thanks in advance!

**Comment by ihadeed** [comment]
Can you post a video of what you're trying to do? 
I'm having a hard time imagining this scenario.

**Comment by Chethannp** [comment]
![2018_01_29_16_58_33_ionic_app](https://user-images.githubusercontent.com/7566931/35512593-4d76dc40-0526-11e8-9698-22b7549b290b.png)

**Comment by Chethannp** [comment]
1. I have a segments menu in the home tab. 
2. When I swipe the tabs are being switched ( as per super tabs) my requirement is when I swipe if the tab page has a segment then it should switch that and then when the end of the segment is reached that is after the last segment if I try to swipe it should then switch the tab.
3. ion-scroll is not working

**Comment by ihadeed** [comment]
Ok, I understand now.

This isn't something that I can support with this module since it's a rare use case, and probably out of the project's scope.

However, you can still achieve this functionality with the methods that this module exposes. You can add functionality in your Home page to enable/disable swiping of `super-tabs` based on the selected segment. Take a look at https://github.com/zyra/ionic2-super-tabs#enabletabsswipe ...

Not sure how to make the segments swipeable though.. you might have to use super-tabs inside of that tab, or write custom code that listens to swipe events & changes the segment for you. 

I hope that helps.

**Comment by Chethannp** [comment]
Oh ok..thanks for the feedback :)

**Comment by Chethannp** [comment]
@ihadeed - I am trying your suggestion, using supertabs inside supertabs, Any idea how do I switch the to the footer tab (i.e Second Page) as soon as top tabs has reached the last position?

Also in this attached image is there a way I can make the top tabs and left hamburger menu align inline (i.e to appear in the same line). please help!
![2018_01_29_23_07_25_ionic_app](https://user-images.githubusercontent.com/7566931/35525142-a91f6ddc-0549-11e8-9291-0c1680148115.png)

**Comment by Chethannp** [comment]
Fyi: I did add them like this to make it inline. 

<super-tabs item-right toolbarBackground="primary" scrollTabs="true" tabsPlacement="top" selectedTabIndex="1" indicatorColor="dark" (tabSelect)="onSegmentSelection($event)">
      <super-tab [root]="tab1Root" icon="menu"></super-tab> **(Clicking on this should open the left menu)**
![approach](https://user-images.githubusercontent.com/7566931/35526874-f23298fa-054e-11e8-9a3b-ff5cc34a1518.png)

      <super-tab [root]="tab1Root" title="You" id="homeTab"></super-tab>
      <super-tab [root]="tab2Root" title="Financial Literacy" id="locationTab"></super-tab>
      <super-tab [root]="tab3Root" title="Healthy Reads" id="favouritesTab"></super-tab>
      <super-tab [root]="tab2Root" title="Topic1" id="locationTab"></super-tab>
      <super-tab [root]="tab3Root" title="Topic2" id="favouritesTab" (ionSelect)="slideToIndex()"></super-tab>
    </super-tabs>

**Comment by ihadeed** [comment]
You can assign an ID for each `super-tabs` element. See https://github.com/zyra/ionic2-super-tabs#id

Then control them with `SuperTabsController`.

Listen to the `(tabSelect)` event on the inner `super-tabs`.. when the selected tab is === to last tab, you can enable swiping for the lower tabs, and when it's not, disable the swiping.
