### ISSUE TITLE
"enableTabSwipe" not taken into consideration when using "*ngIf"

### ISSUE THREAD

**Issue by slung** [zyra/ionic2-super-tabs#27]
## HTML
```html
<super-tabs [*ngIf]="isOnline" height="100%" tabsColor="dark" electedTabIndex="1" toolbarColor="light" toolbarBackground="dark" indicatorColor="light" badgeColor="light" [config]="{ sideMenu: 'left' }">
    <super-tab [root]="tab1Root" title="Map" icon="map" id="mapTab"></super-tab>
    <super-tab [root]="tab2Root" title="List" icon="list" id="listTab"></super-tab>
  </super-tabs>
```

## JS
```js
this.superTabsCtrl.enableTabSwipe("mapTab", false);
```

If you use "_ngIf_" it initially works but if the super tabs component **does not comply** with the if condition and is removed from the DOM and then the if condition **does comply** and the super tabs component is re-introduced in the DOM then it will not work anymore.

The workaround was to use _[hidden]_ instead of _ngIf_ in order to keep it in the DOM.

**Comment by ihadeed** [comment]
`*ngIf` creates and destroys the component depending on the value it gets. The `SuperTabsController` provider cannot find your `SuperTabs` instance if it's not created. You need to use `[hidden]`, or call `enableTabSwipe` after you set `isOnline` value to `true`.
