### ISSUE TITLE
All tabs data loading at the same time 

### ISSUE THREAD

**Issue by tejas008** [zyra/ionic2-super-tabs#277]
Hey..
I want to load the data of the tab after clicking on it or after swipe.How can i do it. Following is the view of my app.
![capture scheme](https://user-images.githubusercontent.com/34152354/37270202-f3a61bb0-25f3-11e8-8251-c2f68f9e0d1a.PNG)

When i push this page ,data of both tabs load at the same time and i want to load the data after clicking on tab.By using this (tabSelect)="onTabSelect($event)" function i tried to load data of the activa tab.
//on supertabs page
onTabSelect(ev: any) {
    console.log('Tab selected', 'Index: ' + ev.index, 'Unique ID: ' + ev.id);
    if(ev.index == 1)
    {
      console.log("tab 2 is selected")
      this.events.publish('tabselected:tabselected2');
    }
  }

//on second tab i have subscribed the event and tried to load the data ,By this method i am able to load the data by clicking on that tab,but sometimes it load twice.

events.subscribe('tabselected:tabselected2', () => {
      let loader = this.loadingCtrl.create({
        content: this.loader_text,
      });
      loader.present().then(() => {
        this.scheme_provider.scheme_Details(this.scheme_id, 'reader').subscribe(
          result => {
            this.reader_info = result.scheme_reader;
            console.log("Success : ", this.reader_info);
          })
      })
      loader.dismiss()
    });

Please tell me solution on this problem or tell me another way to do that.Thanks

**Comment by eduardoRoth** [comment]
Hi @tejas008 , please edit your post and follow Markdown tags to prettify your code.

SuperTabs loads the closest tab before you enter it, for example, lets say you have four tabs, when you run your app, SuperTabs will load tab 1 and 2, when you swipe to tab 2, it will load tab 3 and so on.

If you want to load your data only when the user enters the tab, then you need to move the code that calls the API to the `ionViewWillEnter` or `ionViewDidEnter` event.

```
ionViewDidEnter(){
   this.api.get('readers').subscribe(readers => {
      // do something
   }, err => {});
}
```
_The above code is only for the purpose of my example._
