### ISSUE TITLE
Navbar and status bar are merged when using ionic 2 super tabs on ios version.

### ISSUE THREAD

**Issue by keochom** [zyra/ionic2-super-tabs#279]
Hi!
Thanks for making good tabs for Ionic Framework.
I have an issue. When I use this, I found an issue that navbar and status bar are merged a little.
![navbar](https://user-images.githubusercontent.com/28514445/37515052-2ffcff2a-293c-11e8-8ca6-32ecac00e520.PNG)
Anyone can help me how to fix this issue?
thank you!

**Comment by eduardoRoth** [comment]
Hi @keochom , do you have the latest version of `cordova-plugin-statusbar` installed in your project? It seems to be related to it being not installed.

Please run the following command to make sure it's installed, you should get details after the process finishes:
`ionic cordova plugin add cordova-plugin-statusbar`

After that, build your project and run it again

```
ionic cordova build ios
ionic cordova run ios
```

**Comment by keochom** [comment]
Thank you for your advice.
But it doesn't help me :(
same issue here.

**Comment by eduardoRoth** [comment]
@keochom could you share your HTML code so I can take a look?

**Comment by keochom** [comment]
This is Ionic 3 project.

**Comment by keochom** [comment]
<ion-header>
  <ion-navbar color="primary">
    <ion-buttons left>
      <button ion-button (click)="search()">
        <img src="assets/imgs/search.png" style="width: 45%;"/>
      </button>
    </ion-buttons>
    <ion-title *ngIf="!city" style="text-align: center;"><img id="title-img" src="assets/imgs/title.png" /></ion-title>
    <ion-title *ngIf="city" style="text-align: center;">Events in {{city}}</ion-title>
    <ion-buttons right>
      <button ion-button (click)="location()">
        <img src="assets/imgs/location.png" style="width: 49%;"/>
      </button>
    </ion-buttons>
  </ion-navbar>
  <div id="segment">
    <ion-segment [(ngModel)]="sep" style="width: 80%; margin: 0 auto;">
      <ion-segment-button class="seg" value="1">
        <img class="seg-icon" src="assets/imgs/msg.png">
      </ion-segment-button>
      <ion-segment-button class="seg" value="2">
        <img class="seg-icon" src="assets/imgs/heart.png">
      </ion-segment-button>
      <ion-segment-button class="seg" value="3">
        <img class="seg-icon" src="assets/imgs/notification.png">
      </ion-segment-button>
    </ion-segment>
  </div>
</ion-header>

**Comment by eduardoRoth** [comment]
@keochom images are not showing, could you update your post and use markdown guidelines to prettify your code, please?
