### ISSUE TITLE
Tabs Not Showing

### ISSUE THREAD

**Issue by donsplash** [zyra/ionic2-super-tabs#284]
Just Installed Super tabs The tabs are not showing when i inspect Element there is a hidden attribute attached to it

<super-tabs-toolbar ng-reflect-badge-color="primary" ng-reflect-scroll-tabs="false" ng-reflect-indicator-color="primary" ng-reflect-selected-tab="0" ng-reflect-config="[object Object]" ng-reflect-tabs-placement="top" hidden>

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.5
    npm  : 3.10.10
    OS   : Windows 7

**Comment by donsplash** [comment]
@eduardoRoth  Can you please help

**Comment by eduardoRoth** [comment]
Hi @donsplash , can you paste your code here so I can take a look and see what's happening?
