### ISSUE TITLE
Ionic 3 tabs issue

### ISSUE THREAD

**Issue by tushar-69** [zyra/ionic2-super-tabs#286]
Uncaught Error: Template parse errors:
Can't bind to 'tabRoot' since it isn't a known property of 'super-tab'.
1. If 'super-tab' is an Angular component and it has 'tabRoot' input, then verify that it is part of this module.
2. If 'super-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <super-tabs height="100%">

  <super-tab [ERROR ->][tabRoot]="tab1Root" title="Home"></super-tab>

  <super-tab [tabRoot]="tab2Root" title="About"></sup"): ng:///AppModule/BeginPage.html@20:13
Can't bind to 'tabRoot' since it isn't a known property of 'super-tab'.
1. If 'super-tab' is an Angular component and it has 'tabRoot' input, then verify that it is part of this module.
2. If 'super-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <super-tab [tabRoot]="tab1Root" title="Home"></super-tab>

  <super-tab [ERROR ->][tabRoot]="tab2Root" title="About"></super-tab>

  <super-tab [tabRoot]="tab3Root" title="Contact"></"): ng:///AppModule/BeginPage.html@22:13
Can't bind to 'tabRoot' since it isn't a known property of 'super-tab'.
1. If 'super-tab' is an Angular component and it has 'tabRoot' input, then verify that it is part of this module.
2. If 'super-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <super-tab [tabRoot]="tab2Root" title="About"></super-tab>

  <super-tab [ERROR ->][tabRoot]="tab3Root" title="Contact"></super-tab>

</super-tabs>
"): ng:///AppModule/BeginPage.html@24:13
    at syntaxError (compiler.js:466)
    at TemplateParser.parse (compiler.js:24329)
    at JitCompiler._parseTemplate (compiler.js:33757)
    at JitCompiler._compileTemplate (compiler.js:33732)
    at compiler.js:33634
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:33634)
    at compiler.js:33504
    at Object.then (compiler.js:455)
    at JitCompiler._compileModuleAndComponents (compiler.js:33503)

**Comment by eduardoRoth** [comment]
@tushar-69 `SuperTabs` doesn't use the attribute `tabRoot` it uses `root`:

**Quick Example** *(from the docs)*
```
<super-tabs>
  <super-tab [root]="page1" title="First page"></super-tab>
  <super-tab [root]="page2" title="Second page"></super-tab>
  <super-tab [root]="page3" title="Third page"></super-tab>
</super-tabs>
```

Change that and it'll work.

**Comment by tushar-69** [comment]
ohk thanks bro.
