### ISSUE TITLE
super-tabs-toolbar not showing

### ISSUE THREAD

**Issue by ultimatelocal** [zyra/ionic2-super-tabs#288]
Hi I'm having an issue displaying the toolbar-tabs I didn't know what's the issue since I'm strictly following the documentation and examples.  I don't know what goes wrong on my implementation.

I'm using ionic-cli : 3.20.0
ionic2-super-tabs:  4.2.2

here's my events.html : 

```
 <!--
  Generated template for the EventsPage page.

  See http://ionicframework.com/docs/components/#navigation for more info on
  Ionic pages and navigation.
-->

<ion-header>

  <ion-navbar color="uapRed">
    <ion-title>Events</ion-title>
  </ion-navbar>

</ion-header>

<ion-content no-bounce>

  <super-tabs toolbarColor="dark"
  indicatorColor="dark"
  scrollTabs
  toolbarBackground="dark"
  (tabSelect)="onTabSelect($event)">

    <super-tab [swipeBackEnabled]="false" [root]="page1" [title]="Home" id="page1" [icon]=""></super-tab>
    <super-tab [root]="page2" [title]="Event" id="page2" [icon]=""></super-tab>

  </super-tabs>

</ion-content>

```

and on my  events.ts : 
```
import { Component, ViewChild } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { SuperTabs, SuperTabsController } from "ionic2-super-tabs"
/**
 * Generated class for the EventsPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-events',
  templateUrl: 'events.html',
})
export class EventsPage {

  @ViewChild(SuperTabs) superTabs: SuperTabs;


  page1: any = 'EventTabsPage';
  page2: any = 'EventTabsPage';

  constructor(public navCtrl: NavController, public navParams: NavParams, private superTabsCtrl: SuperTabsController) {

  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad EventsPage');
  }

  ngAfterViewInit() {

  }

  onTabSelect(tab: { index: number; id: string; }) {
    console.log(`Selected tab: `, tab);
  }

}

```

**Comment by bgcc93** [comment]
I'm getting the same issue. 
Starting a new tabs project via Ionic CLI, the tabs don't show when following the Quick Example. 
The `super-tabs-toolbar` seems to render with a `.hide` class, that applies a `display: none!important;` to it.
When I remove the  `display: none` on the browser inspector, the toolbar appears on top of the ion-header and, even though the icons and titles for the buttons don't show, you can click on them and they navigate to other pages.

![](https://i.imgur.com/Rk1KQx5.gif)

The project uses `"@angular/core": "5.2.9"`, `"ionic-angular": "3.9.2"` and `"@ionic-native/core": "4.6.0"`

**Comment by eduardoRoth** [comment]
@ultimatelocal 

Modify your code to set scrollTabs to true:

```
<super-tabs toolbarColor="dark"
  indicatorColor="dark"
  scrollTabs="true"
  toolbarBackground="dark"
  (tabSelect)="onTabSelect($event)">
```

@bgcc93 , could you share your code so I can take a look at it?

**Comment by ultimatelocal** [comment]
Hi @bgcc93  I was able to solve this issue by replacing the `[title]=Event` to `title= Event` only.

**Comment by bgcc93** [comment]
Thanks @ultimatelocal , I just tested and it works. Forgot to change the `tabTitle` to `title` and `tabIcon` to `icon`

**Comment by ultimatelocal** [comment]
Nice to hear it works @bgcc93 ! Cheers!

**Comment by eduardoRoth** [comment]
@bgcc93 great to know that it works, I didn't see that you were using Ionic Tab attributes instead of Super Tab ones.

@ultimatelocal, the reason that replacing `[title]="Event"` with `title="Event"` worked was that when you use square brackets the right side is evaluated in code, so Angular was looking for a variable called "Event" to get it's value. `[title]="'Event'"` will work because on the right side you're using a string.
