### ISSUE TITLE
Overlapping tabs

### ISSUE THREAD

**Issue by zubliquzaini** [zyra/ionic2-super-tabs#291]
I tried to achieve this in my project, 

![96589e54-2038-11e7-88d7-efa68b1f109c](https://user-images.githubusercontent.com/16085445/38973461-8548b440-43d8-11e8-9374-6be3d9c9d5f3.gif)

However, I am facing this issue where the tabs become overlapping and not scrollable.

![screenshot_2018-04-19-13-37-26](https://user-images.githubusercontent.com/16085445/38973480-a32c29c4-43d8-11e8-8f92-20c6d9b3fcf9.png)

I am using the latest version of super-tabs. Is there any solution for the tabs to become like one above? Help! Thank you in advance..

**Comment by ihadeed** [comment]
Are you using the scrollTabs attribute?

**Comment by shri1983** [comment]
Having same issue and not using scrollTabs property. Please help me out. Thanks in advance.

**Comment by zubliquzaini** [comment]
@ihadeed thank you for your reply, so sorry I didn't read the documentation well enough.. Thank you for your time. Really appreciate!
