### ISSUE TITLE
ERROR Error: Uncaught (in promise): invalid views to insert

### ISSUE THREAD

**Issue by Jmunapo** [zyra/ionic2-super-tabs#293]
I'm trying to implement this on lazy loading and this is what I'm getting
`core.js:1448 ERROR Error: Uncaught (in promise): invalid views to insert
    at c (polyfills.js:3)
    at polyfills.js:3
    at rejected (super-tabs.js:4)`

main.ts
`import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

/**
 * 
 */

@IonicPage()
@Component({
  selector: 'page-main',
  templateUrl: 'main.html',
})
export class MainPage {
  main1Root: any = 'MessagesPage';
  main2Root: any = 'SubscribePage';
  main3Root: any = 'ReadMessagePage';
  constructor(public navCtrl: NavController, public navParams: NavParams) {
  }

}
`

main.html
`<super-tabs height="100%">
  <super-tab [root]="tab1Root" title="Home"></super-tab>
  <super-tab [root]="tab2Root" title="About"></super-tab>
  <super-tab [root]="tab3Root" title="Contact"></super-tab>
</super-tabs>`

component.ts
`import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { MainPage } from './main';
import { SuperTabsModule } from 'ionic2-super-tabs';

@NgModule({
  declarations: [
    MainPage,
  ],
  imports: [
    SuperTabsModule,
    IonicPageModule.forChild(MainPage),
  ],
})
export class MainPageModule {}
`

What am I missing..?

**Comment by eduardoRoth** [comment]
@Jmunapo Your tabs variables have the `main` prefix, while on your code you're using the `tab` prefix:

```
main1Root: any = 'MessagesPage';
main2Root: any = 'SubscribePage';
main3Root: any = 'ReadMessagePage';
```

```
<super-tabs height="100%">
    <super-tab [root]="tab1Root" title="Home"></super-tab>
    <super-tab [root]="tab2Root" title="About"></super-tab>
    <super-tab [root]="tab3Root" title="Contact"></super-tab>
</super-tabs>
```

So, your tabs root is undefined and hence invalid views, change your code to:

```
<super-tabs height="100%">
    <super-tab [root]="main1Root" title="Home"></super-tab>
    <super-tab [root]="main2Root" title="About"></super-tab>
    <super-tab [root]="main3Root" title="Contact"></super-tab>
</super-tabs>
```

And it should work
