### ISSUE TITLE
Different Content in single View

### ISSUE THREAD

**Issue by magic-77** [zyra/ionic2-super-tabs#294]
Hi, is it possible to have Super Tabs with one view but load different content?
I'm using Ionic with Shopify.
Therefore i have some Categories with several Articles.
From "Home" you can choose a Category, then the view "product-lister" is loaded.
Now i would like to have super tabs included here. So when choosing another category, its content will be loaded into this View.

**Comment by eduardoRoth** [comment]
@magic-77 let me see if I got you, what you want is to change the `SuperTabs` elements so if you choose a category it will change tabs to show all of its subcategories?

Home --> Cars --> Accesories | Tires | etc...
Home --> Kids --> Shirts | Pants | Shorts | etc...

So when you choose "Kids" from your `ion-select` (or some other component) it'll replace the `SuperTabs` component to show the subcategories of your selected one?

If that's the case, you'll need to fetch your categories and subcategories prior, and create one `SuperTabs` component per category that you'll show or hide based on your selected category.

The reason of this little `hack` is that, at this time, `SuperTabs` component doesn't work well with dynamically generated tabs.

Hope this helps

**Comment by magic-77** [comment]
@eduardoRoth: Thanks for your answer.
Let me explain my Problem with Images

![home](https://user-images.githubusercontent.com/10066784/39140271-5444cf1a-4724-11e8-82bf-1f10501826a0.png)
![cat-1](https://user-images.githubusercontent.com/10066784/39140213-30401426-4724-11e8-940a-8b77e901dae9.png)
![cat-2](https://user-images.githubusercontent.com/10066784/39140214-305a4832-4724-11e8-89d5-d0aa85c46976.png)

I have no subcategories. All of them are Main Cats.
From Home i get to the "product-lister" view. Now i would like to load the other Articles from the other Cats inside this view.

**Comment by magic-77** [comment]
@eduardoRoth Many Thanks for your detailed Answer. But i'm stuck with integrating the Tabs into the Lister View. Sorry, but i'm really new to ionic.

This is my Code:

Home.html ( type is page )
```
...
<ion-col col-6 col-sm-4 *ngFor="let item of collections">
  <div class="home__image">
    <img (click)="openCollection(item)" [src]="setImage(item)">
  </div>
  <div (click)="openCollection(item)">{{item.attrs.title}}</div>
 </ion-col>
...
```

Home.ts
```
import {Component} from '@angular/core';
import {IonicPage, NavController, NavParams} from 'ionic-angular';
import {ShopifyClientProvider} from '../../providers/shopify-client/shopify-client';
@IonicPage()
@Component({
    selector: 'page-home',
    templateUrl: 'home.html',
})
export class HomePage {
    collections: any;
    pages: any;
    constructor(
        public navCtrl: NavController,
        public navParams: NavParams,
        public shopifyClientProvider: ShopifyClientProvider
    ) {
        shopifyClientProvider.getCollections()
            .then(data => {
                this.collections = data;
                this.pages = data;
            })
            .catch(err => {
            });
    }

    ionViewDidLoad() {
        console.log('ionViewDidLoad HomePage');
    }

    openCollection(item) {
        let id = item.attrs.collection_id;
        this.shopifyClientProvider.getCollection(id)
            .then(data => {
                this.navCtrl.push(ProductListPage, {products: data, collection: item})
            })
    }
}
```

Product-List.html ( type is Page, this is the Lister View  )
```
<ion-col col-6 col-sm-4 *ngFor="let item of allItems">
   <ion-card (click)="openProduct(item)">
     <div class="lister-image">
        <img [src]="item.attrs.images[0].src">
      </div>
      <ion-card-content>
          <ion-card-title>
              {{item.attrs.title}}
           </ion-card-title>
             <p>
                 <span>Preis: </span><span>{{item.variants[0].price}} €</span>
              </p>
          </ion-card-content>
       </ion-card>
 </ion-col>
```

Product-List.ts
```
import {Component, ViewChild} from '@angular/core';
import {IonicPage, NavController, NavParams} from 'ionic-angular';
import {ProductDetailPage} from "../product-detail/product-detail";
@IonicPage()
@Component({
    selector: 'page-product-list',
    templateUrl: 'product-list.html',
})
export class ProductListPage {
    allItems: any;
    realItems: any = [];
    title: any;
    constructor(
        public navCtrl: NavController,
        public navParams: NavParams
    ) {
        let collection = this.navParams.get('collection');
        this.allItems = this.navParams.get('products');
        this.title = collection.attrs.title;
    }

    ionViewDidLoad() {
        console.log('ionViewDidLoad ProductListPage');
    }

    openProduct(item) {
        this.navCtrl.push(ProductDetailPage,
            {item: item}
        )
    }
}
```
Do i have to generate Tabs as a Component or as a Page. Tried both. But it does not work for me

**Comment by eduardoRoth** [comment]
@magic-77 

You can make this change in your `home.html` to make the whole column to be clickable:
```
<ion-col col-6 col-sm-4 *ngFor="let item of collections" tappable (click)="openCollection(item)">
  <div class="home__image">
    <img [src]="setImage(item)">
  </div>
  <div>{{item.attrs.title}}</div>
 </ion-col>
```

As for your main concern, you need to create a `TabsPage` that will be shown when you click on an image:

```
openCollection(item) {
        let id = item.attrs.collection_id;
        this.shopifyClientProvider.getCollection(id)
            .then(data => {
                this.navCtrl.push(TabsPage, {products: data, collection: item})
            })
    }
```

The thing is that you need to see it this way:

You have your HomePage, your user can see every category of products that you have, then they choose one to see the products but by doing so, they will not be sent to a `ProductsListPage`, they will be sent to a `TabsPage` that have one tab per category and from there, the app will select the right tab based on the category your user chose.

1. Your user opens the app
2. Your app shows the `HomePage` and shows every category
3. User taps on a category
4. Your app checks which category, and show the `TabsPage` on the right tab (be it the selected category).
    1. The `TabsPage` is an array of the `ProductListPage` each one loading the proper collection of items
5. Your user can move between tabs in `TabsPage` using the `SuperTabs` component

Hope this clarifies the issue 😄

**Comment by magic-77** [comment]
@eduardoRoth Ok, theoretically i unterstand what you mean. Doing the changes to home give me now an error
```
Uncaught (in promise): Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.
Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.
```

**Comment by eduardoRoth** [comment]
@magic-77 can you post your updated code? It seems that the value that your `*ngFor` is getting is an object `{}` instead of an array if items `[]`

**Comment by magic-77** [comment]
@eduardoRoth Ok, now i've change the openCollection Function:
```
openCollection(item) {
        let id = item.attrs.collection_id;
        // BEFORE
        // this.shopifyClientProvider.getCollection(id)
        //     .then(data => {
        //         this.navCtrl.push(TabsPage, {products: data, collection: item})
        //     })

        // NOW
        this.shopifyClientProvider.getCollections()
            .then(data => {
                this.navCtrl.push(TabsPage, {collections: data})
            });
    }
```
Tabs.ts
```
export class TabsPage {
    @ViewChild(SuperTabs) superTabs: SuperTabs;
    public rootTab: string = 'ProductListPage';
    public categories: Array<any>;
    public selectedCat: any;
    constructor(
        public navCtrl: NavController,
        public navParams: NavParams,
        private superTabsCtrl: SuperTabsController
    ) {
        this.categories = navParams.get('collections');
        console.log('categories tabs: ',this.categories);
        //this.selectedCat = navParams.get('selected');
    }

    ionViewDidLoad() {
        console.log('ionViewDidLoad TabsPage');
    }
}
```

So, i get an Array of Elements at "Tabs.ts"
but also an Error.
```
TypeError: Cannot set property 'rootNavCtrl' of undefined
```

**Comment by magic-77** [comment]
Ok, i look like that "[rootParams]="category.params"" is wrong

**Comment by magic-77** [comment]
This is the Array i'm getting
![collections](https://user-images.githubusercontent.com/10066784/39214265-2f743630-4814-11e8-8fc5-8e46db8e6876.png)

**Comment by eduardoRoth** [comment]
@magic-77 For your `[rootParams]`you would need to send your `collection_id` so that in your `ProductListPage` you'll fetch all the items of that collection:

```
<super-tabs>
    <super-tab *ngFor="let category of categories" [root]="rootTab" [title]="category.attrs.title" [rootParams]="{collection_id:category.attrs.collection_id}"></super-tab>
</super-tabs>
```

**ProductListPage**
```
export class ProductListPage{
   public collection_id : number;
   constructor(private _navParams : NavParams) {
       this.collection_id = _navParams.get('collection_id');
       // then you can fetch your items
   }
}
```

**Comment by magic-77** [comment]
@eduardoRoth pushing id this way
home.ts
```
 openCollection(item) {
        let id = item.attrs.collection_id;
        this.shopifyClientProvider.getCollections()
            .then(data => {
                this.navCtrl.push(TabsPage, {collections: data, collection_id: id})
            });
    }
```
receiving id at "tabs.ts", but now this error is thrown
```
Uncaught (in promise): Error: Type ProductListPage is part of the declarations of 2 modules: AppModule and ProductListPageModule! Please consider moving ProductListPage to a higher module that imports AppModule and ProductListPageModule. You can also create a new NgModule that exports and includes ProductListPage then import that NgModule in AppModule and ProductListPageModule.
Error: Type ProductListPage is part of the declarations of 2 modules: AppModule and ProductListPageModule! Please consider moving ProductListPage to a higher module that imports AppModule and ProductListPageModule. You can also create a new NgModule that exports and includes ProductListPage then import that NgModule in AppModule and ProductListPageModule.
```

**Comment by magic-77** [comment]
Ah, changing this
```
public rootTab: string = 'ProductListPage';
```
to
```
public rootTab: any = ProductListPage;
```
is loading the page

**Comment by eduardoRoth** [comment]
@magic-77 
It seems you're importing twice your ProductListPage, remove it from `AppModule` because you're using `lazy loading`, hence your `@IonicPage()` attribute

```
Uncaught (in promise): Error: Type ProductListPage is part of the declarations of 2 modules: AppModule and ProductListPageModule! Please consider moving ProductListPage to a higher module that imports AppModule and ProductListPageModule. You can also create a new NgModule that exports and includes ProductListPage then import that NgModule in AppModule and ProductListPageModule.
Error: Type ProductListPage is part of the declarations of 2 modules: AppModule and ProductListPageModule! Please consider moving ProductListPage to a higher module that imports AppModule and ProductListPageModule. You can also create a new NgModule that exports and includes ProductListPage then import that NgModule in AppModule and ProductListPageModule.
```

**Comment by eduardoRoth** [comment]
@magic-77 

### _So how to get Tabs under the Header. Tried to place the Header in Tabs.html and also in app.html. Both does not work. When i place the Header in app.html, Tabs disappear. Placing inside Tabs.html i get an blank screen._

As your `ProductListPage` will go "inside" your `TabsPage` add your `<ion-header>` tag in `TabsPage` like this:

**TabsPage.html**
```
<ion-header>
    <ion-title>Title for Tabs Page</ion-title>
    // <ion-toolbar></ion-toolbar> // I suppose you want the shopping cart button above the tabs so it should be here instead of ion-title
</ion-header>
<ion-content>
    <ion-supertabs>
        <ion-supertab ...></ion-supertab>
    </ion-supertabs>
</ion-content>
```

### _The "product-list" view is being loaded twice. can't find the issue with that._

That's because of how `SuperTabs` work, when you enter a tab, it preloads the previous and next tab, firing the `ionViewWillLoad` and `ionViewDidLoad` of each. That's why you get two calls with different `collection_id`'s

### _And some strange behavior with the Tabs indicator_

The reason for that is that `SuperTabs` component doesn't fully support dynamically generated tabs, I'm working in a fix for that. In the meantime, just add an `*ngIf` in your `<ion-supertabs>` component that is false and only changes to true until you have fully loaded your categories. That way, when Angular adds the component to the DOM it'll already have the tabs and will get the right width for the tabs indicator.

**Comment by magic-77** [comment]
@eduardoRoth Hi, have so many thank for this!!!
Now the Tabs view and Header/Footer Position are fine. I forgot the "<ion-content>" wrapper.
The misbehavior with the Tab Indicator ist gone, after placing Tabs inside "<ion-content>" :-)

One last Question: Where is the Donate Button :-)

**Comment by eduardoRoth** [comment]
@magic-77 great to know that it worked! 😄 

As for how you can help @ihadeed with Ionic2-Super-Tabs, ask him because I don't think he has a public `donate button`, as for other ways to support his project:

### Support this project **as README.md states*
If you find this project useful, please star the repo to let people know that it's reliable. Also, share it with friends and colleagues that might find this useful as well. Thank you 😄

As for me, I currentrly don't have a donate button hahaha 😆

**Comment by magic-77** [comment]
@eduardoRoth Ok. What about distributing an example App with Super Tabs and Shopify for your examples?

**Comment by eduardoRoth** [comment]
@magic-77 I think that would be great! Lets wait to what @ihadeed has to say 😄

**Comment by magic-77** [comment]
@eduardoRoth Fine. Let me know. Cheers

**Comment by magic-77** [comment]
@eduardoRoth Sorry, but i need your Help one more time.
My Problem is, that when i'm in Lister View (product-list.html) which is loaded inside Tabs.html and i click on a Product, the Product Detail View is also loaded within Tabs. How to leave that

tried with from product-list.ts
```
openProduct(item): void {
        this.navCtrl.setRoot(ProductDetailPage).then(() =>{
            this.navCtrl.popToRoot();
            this.navCtrl.push(ProductDetailPage, {
                    item: item
                }
            )
        });
    }
```

but then i get an Error:
```
Uncaught (in promise): TypeError: Cannot read property 'images' of undefined
TypeError: Cannot read property 'images' of undefined
```

**Comment by eduardoRoth** [comment]
@magic-77 That can be solved in two ways,

1. You inject AppController into your page so you can get the root navigation element, or
2. Just get the parents of your nav controller: `this._navCtrl.parent.parent.push(PAGE)`

**Comment by magic-77** [comment]
@eduardoRoth Ahh, two parents are needed. So many thanks for your Help!

**Comment by eduardoRoth** [comment]
@magic-77 the reason that two parents are needed is that the first one is the `SuperTabsContainer` and then the next parent is the view in which the `SuperTabsContainer` is placed.
