### ISSUE TITLE
change ion-title in navbar dynamically when changing tabs 

### ISSUE THREAD

**Issue by leemerlas** [zyra/ionic2-super-tabs#297]
I'm trying to find a solution just like this answer [https://stackoverflow.com/questions/37471612/how-can-i-change-ion-title-programmatically-in-ionic2?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](url)

Basically I want to be able to change my ion-title in my navbar whenever I switch tabs. supertabs won't let me work with ionSelect, so does anyone have a fix for this?

**Comment by magic-77** [comment]
Did you tried with the "tabSelect" Function?
```
<super-tabs (tabSelect)="onTabSelect($event)">
  <super-tab [root]="page1" title="First page" icon="home" id="homeTab"></super-tab>
  <super-tab [root]="page2" title="Second page" icon="pin" id="locationTab"></super-tab>
  <super-tab [root]="page3" title="Third page" icon="heart" id="favouritesTab"></super-tab>
</super-tabs>
```

In your Page Class you can capture the Event
```
onTabSelect(ev: any) {
    console.log('Tab selected', 'Index: ' + ev.index, 'Unique ID: ' + ev.id);
  }
```
So for the Title it could be ( should work, but i did not tried it )
```
onTabSelect(ev: any) {
    console.log('Tab Title',ev.title);
  }
```

**Comment by leemerlas** [comment]
@magic-77 yes I did try the tabSelect function and it works. But what I want to change is my ion-title whenever I switch tabs. My bad I didn't include the code I have so it's a bit confusing. 

Here's my code: 
`<ion-header>
    <ion-navbar color="dark">
        <button ion-button menuToggle>
            <ion-icon name="menu"></ion-icon>
        </button>
  
      <ion-title>{{title}}</ion-title>
    </ion-navbar>
  </ion-header>


<super-tabs toolbarBackground="dark" toolbarColor="main" tabsPlacement="bottom" indicatorColor="main" [config]="{ sideMenu: 'left' }" (tabSelect)="onTabSelect($event)">
  <super-tab [root]="tab1Root" icon="icon-ai-announce" id="Home" (ionSelect)="this.title ='Home'"></super-tab>
  <super-tab [root]="tab2Root" icon="icon-ai-rules" id="Rules" (ionSelect)="this.title ='Rules'"></super-tab>
  <super-tab [root]="tab3Root" icon="icon-ai-prison-visit" id="Visit" (ionSelect)="this.title ='Visit'"></super-tab>
  <super-tab [root]="tab4Root" icon="icon-ai-comments" id="Comment" (ionSelect)="this.title ='Comment'"></super-tab>
</super-tabs>
`

**Comment by magic-77** [comment]
This will not work
```
(ionSelect)="this.title ='Home'"
```
Just define it this way
```
 <super-tab [root]="page1" title="First page" icon="home" id="homeTab"></super-tab>
```
then on the "onTabSelect" console.log, if title is available ( should be )

inside "onTabSelect"
```
this.title = ev.title
```

**Comment by leemerlas** [comment]
@magic-77 yep that's what I realized. supertabs doesn't work with ionSelect.

but I don't want to have a title for my tabs because it'll look weird. It should look like this. Do you suppose I can hide the title but still assign a value to it? 

![screenshot_1](https://user-images.githubusercontent.com/31193012/39380074-e5e6ab00-4a8f-11e8-9e22-7c7d317d7d12.png)

**Comment by magic-77** [comment]
The dirty way would be to "display:none" the title Element inside the Button

**Comment by leemerlas** [comment]
Well I managed to solve the problem by declaring using the id element instead. Found it in the supertabs documentation. 

    onTabSelect(ev: any) {
        console.log('Tab selected', 'Index: ' + ev.index, 'Unique ID: ' + ev.id);
        this.title = ev.id;
     }

The only problem left now is that it won't change on initialize. At first the navbar title is blank, but when I navigate to other tabs only then will it change.

**Comment by leemerlas** [comment]
Nevermind, fixed it by applying this code, since I know the on initialize the 'Home' tab should be first.

    ngAfterViewInit() {
  
    // must wait for AfterViewInit if you want to modify the tabs instantly
    this.title = 'Home';
  
    }
