### ISSUE TITLE
Add ability to navigate to a specific tab + page

### ISSUE THREAD

**Issue by benharpers** [zyra/ionic2-super-tabs#3]
Suggest creating a controller that could be used to change the active tab, and navigate to specific page at the same time:

```
import { SuperTabsController } from 'ionic2-super-tabs';
import { SettingsPage } from './settings.page';

@Component({
  selector: 'page-home',
  template: '<ion-content><button (click)="goToSettings()">Settings</button></ion-content>',
})
export class HomePage {

  constructor(private tabsCtrl: SuperTabsController) {}

  goToSettings() {

    this.tabsCtrl.push('optional tab ID', SettingsPage, { userid: this.user.id }, { animate: true });
  }
}
```

Basically, if that tab was already the active tab then it just goes to the new page. If not, then it goes to the new page and then slides the tab into place.

This is an awesome project btw. 👍

**Comment by ihadeed** [comment]
Good idea, I will add it when I get a chance.
