### ISSUE TITLE
Html no update when I change another view and I come back

### ISSUE THREAD

**Issue by edu526** [zyra/ionic2-super-tabs#30]
I have a list of Youtube Api videos. When I use ionic 2-super-tabs v1.1.1, fine. But when I use ionic2-super-tabs v2.2.2 and change another tab, my list does not change when I come back and I'm searching for another video.

V1.1.1
http://granadillacompany.com/super_tabs_v1.gif

V2.2.2
http://granadillacompany.com/super_tabs_v2.gif

**Comment by ihadeed** [comment]
Hey there,

Can you please upgrade to `ionic2-super-tabs@2.3.0` and let me know if this issue has been solved?

**Comment by edu526** [comment]
The error persists. I will try to upload a copy of my project.

**Comment by edu526** [comment]
Hi, thanks for your time.

I managed to upload a part of the project to github and the server to Heroku.
The server might take awhile, for the initialization time.

I've created a project from scratch.
`git clone https://github.com/edu526/super-tabs-test.git`

**Comment by slung** [comment]
I can confirm. I upgraded to 2.3.0 and I have 2 tabs: a list and a map. All bindings are lost on the list's template if I go to the map tab and then come back to the list. The app starts with the list tab selected.

**Comment by ihadeed** [comment]
Could you please update to `ionic2-super-tabs@2.3.2` and let me know if this issue is fixed?

**Comment by edu526** [comment]
I upgrade to `ionic2-super-tabs@2.3.2` and The error persists. In `ionic2-super-tabs@2.4.1` is the same.

Thanks for your time!!!

**Comment by plusCubed** [comment]
Occurs on my end on 2.4.1 as well. The event bindings seem to work fine, but the interpolation bindings don't work.

**Comment by ihadeed** [comment]
The issue was caused as a consequence of firing `didEnter` and `didLeave` events. I disabled them for now as a hot fix. I will find out what the problem is and try to bring the view events back. 

Upgrade to `2.4.2` and it should work well.
```
npm i --save ionic2-super-tabs@latest
```

**Comment by ihadeed** [comment]
Update: I just published `2.5.0` that brings back the view events. The problem occurred because I didn't fire the `willEnter` view event, which is the event that brings change detection back to life.

**Comment by edu526** [comment]
This is already resolved. Thanks for all your help. 👍 :D
