### ISSUE TITLE
performance concern

### ISSUE THREAD

**Issue by Anujmoglix** [zyra/ionic2-super-tabs#31]
When I rotate mobile then its performance is very lazy ,and screen menu is not looking good on landscape mode,
![selection_007](https://cloud.githubusercontent.com/assets/26056096/25335125/4656ea84-290f-11e7-98b6-c8780b3a53c0.png)

Other thing is that tab touch performance is very bad when i am getting response from api :(

**Comment by ihadeed** [comment]
Hey @Anujmoglix 

Thanks for the feedback

I did experience the bad performance when using `scrollTabs` attribute. There are too many things moving at once. Also, when having many tabs, there are many pages active at the same time.

In the next release I'm adding functionality to disable change detection in tabs that aren't active. This should help with the memory usage.

I also plan on finding and using a better way to animate the component. I'm personally not satisfied yet with it's performance (with scrollTabs on). It needs to feel more native like (smooth).

I will keep you posted on any updates that will affect this issue.

**Comment by Anujmoglix** [comment]
Thanks !!! Waiting for your best UI this this . I am using it in my official project so i want to feel like native . I use only 5 tabs.

**Comment by ihadeed** [comment]
Hey there,

Can you please upgrade to `ionic2-super-tabs@2.3.0` and let me know if this issue has been solved?

**Comment by Anujmoglix** [comment]
Oh Great !! you have updated it . I will use it and let you know for sure .

**Comment by Anujmoglix** [comment]
can you create file with ionic setup ?

**Comment by ihadeed** [comment]
@Anujmoglix sorry I'm not sure what you mean?

**Comment by Anujmoglix** [comment]
I want to pull full code and use it in new ipnic project or if i can use this code in previously created one .

**Comment by Anujmoglix** [comment]
Want to know steps to use in my existing project which i used in super tab previous version .

**Comment by ihadeed** [comment]
@Anujmoglix you just need to run `npm i --save ionic2-super-tabs@latest` and that will update it to the latest version.

**Comment by Anujmoglix** [comment]
Performance is better now but  i am facing weird situations .  I want to show data from api to each tab but after upgrating it data is not showing on page . It is showing on console but not on page ,,  :( 
I am using event for this 
`  this.events.subscribe('user:loggedIn', (data) => {
      console.log(data);
    });`

**Comment by karlvd** [comment]
@Anujmoglix possibly related to this
#36

**Comment by Anujmoglix** [comment]
Ya .I checked that issue, I am facing same issue ,Please fix this :( .

**Comment by ihadeed** [comment]
@Anujmoglix #36  is fixed now, can you check if you're still experiencing issues? If not, please close this issue.

**Comment by Anujmoglix** [comment]
I modified my package.json as  "ionic2-super-tabs": "^2.3.3",  and did npm install . I checked it but  performance is again not good. It is same as we start discussion .

**Comment by ihadeed** [comment]
@Anujmoglix 

Latest version is 2.4.1

**Comment by Anujmoglix** [comment]
yeeh ,, it is better now , Thanks ihadeed . Can you do it little more faster :) if you can . But still it is good

**Comment by ihadeed** [comment]
@Anujmoglix yes, I'm working on some fixes right now with the goal of improving performance and fixing all the binding/change detection issues. I'm publishing those small releases for now, but I will publish a big release soon.

**Comment by Anujmoglix** [comment]
Hi,  Ihadeed . Have you done any release ? Sometime it's performance become not good .On swiping it stop for 1-2 second . That is the problem :(

**Comment by Anujmoglix** [comment]
Any update ?

**Comment by ihadeed** [comment]
@Anujmoglix I published a few versions since this conversation.. See https://github.com/zyra/ionic2-super-tabs/releases

The performance seem to be very good now. Specially if you use Crosswalk / WKWebView.

**Comment by Anujmoglix** [comment]
thanks. I didn't check .Is Crosswalk mandatory ? Will it not create any issue on my current app ?

**Comment by ihadeed** [comment]
No they're not mandatory but I find that animations in general work better within Crosswalk/WKWebView.

**Comment by Anujmoglix** [comment]
Ok I will try with Crosswalk

**Comment by Anujmoglix** [comment]
I did following` ionic plugin add cordova-plugin-crosswalk-webview` and changed` <uses-sdk android:minSdkVersion="20" android:targetSdkVersion="24" />   ` but didn't feel too much  difference in first time load .When i scroll to all tab then performance is better.

**Comment by Anujmoglix** [comment]
Can you check one of my issue that badge 0 is not working
