### ISSUE TITLE
Typescript Error Super tabs

### ISSUE THREAD

**Issue by Dharma404** [zyra/ionic2-super-tabs#313]
<img width="1245" alt="screen shot 2018-06-15 at 11 22 50" src="https://user-images.githubusercontent.com/40294508/41463764-8a77398a-708f-11e8-88fb-0d5a4bd310d6.png">

**Comment by magic-77** [comment]
Take a look here:
https://github.com/zyra/ionic2-super-tabs/issues/310

**Comment by Dharma404** [comment]
It worked @magic-77 Thanks

**Comment by tamilm47** [comment]
What is the fix for this issue...I am using 
typescript - 3.5.3
ionic - 3.9.2
