### ISSUE TITLE
Ionic 4 support?

### ISSUE THREAD

**Issue by ThomasLohmann** [zyra/ionic2-super-tabs#315]
Hi everyone,

are there any plans to support super-tabs in Ionic 4?

Kind regards,
Thomas

**Comment by ihadeed** [comment]
Yes. When it's in late beta / stable stage.

**Comment by ihadeed** [comment]
Please watch the following branch for updates on Ionic 4 development: https://github.com/zyra/ionic2-super-tabs/tree/master
