### ISSUE TITLE
avoid-super-tabs="true" not working

### ISSUE THREAD

**Issue by spyman143** [zyra/ionic2-super-tabs#319]
Hi,
i'm using supertabs in my apps. In super tabs page i have ion-scroll too. To avoid conflict with scrolling i had added **avoid-super-tabs="true"** attribute. But its not working. i had installed supertab  with following code
npm i --save ionic2-super-tabs.

if anyone have same issue?  Can you please fix this issue @ihadeed ?

**Comment by ihadeed** [comment]
It's not published yet.. i'll publish it now.

**Comment by ihadeed** [comment]
Done. Please update to 4.8.0

**Comment by spyman143** [comment]
Thank you @ihadeed
