### ISSUE TITLE
Ion-tabs scrollable issue

### ISSUE THREAD

**Issue by gadelaanil** [zyra/ionic2-super-tabs#322]
Hi
Hi,
App.module.ts

import { ScrollableTabs } from '../components/scrollable-tabs/scrollable-tabs';
@NgModule({
  declarations: [
myApp,
    ScrollableTabs
  ],
  imports: [
    BrowserModule,
    HttpModule,
    IonicModule.forRoot(myApp, {
      preloadModules: true
    }),
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [Http]
    }),
    IonicStorageModule.forRoot()
  ],
  bootstrap: [IonicApp],
  exports: [TranslateModule],
  entryComponents: [
    myApp
  ],
  providers: [
    { provide: ErrorHandler, useClass: IonicErrorHandler },
    InAppBrowser,
    SplashScreen,
  ]
})
export class AppModule { }

tabs.html
========
<ion-tabs #ionTabs [scrollable-tabs]="ionTabs" name="main">
  <ion-tab [root]="tab1Root" tabTitle="Home" tabIcon="fa-home"></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="People" tabIcon="fa-users"></ion-tab> 
  <ion-tab [root]="tab3Root" tabTitle="folder" tabIcon="fa-reserve" show="{{reservationsaddRights}}"></ion-tab>
  <ion-tab [root]="tab4Root" tabTitle="Events" tabIcon="fa-events" show="{{eventsaddRights}}"></ion-tab>
  <ion-tab [root]="tab5Root" tabTitle="test" tabIcon="fa-register" show="{{registrationsaddRights}}"></ion-tab>
  <ion-tab [root]="tab6Root" tabTitle="Maps" tabIcon="fa-map"></ion-tab>
  
</ion-tabs>
---------
scroollable-tabs.ts
========
import { Directive, AfterViewInit, ElementRef, Renderer, Input } from '@angular/core';
import { Tabs, Tab } from 'ionic-angular'
declare var window: any;
@Directive({
  selector: '[scrollable-tabs]',
  host: {
    '(window:resize)': 'onResize($event)'
  }
})
export class ScrollableTabs implements AfterViewInit {
  @Input('scrollable-tabs') ionTabs: Tabs;
  @Input('opts') opts: any = {};

  currentTabIndex: number;
  tabs: Tab[] = [];
  nativeTabbar: HTMLElement;

  constructor(public elemRef: ElementRef, public renderer: Renderer) {
  }

  ngOnChanges(changes: any) {
    if (changes.hasOwnProperty('opts')) {
      if (changes['opts'].currentValue.refresh) {
        setTimeout(() => {
          this.setAnchorStyles();
          this.scrollToselectedTab();
        }, 300);
      }
    }
  }

  ngAfterViewInit() {
    this.nativeTabbar = this.ionTabs._tabbar.nativeElement;
    this.tabs = this.ionTabs._tabs;
    this.currentTabIndex = typeof (this.ionTabs.selectedIndex) === 'undefined' ? 0 : this.ionTabs.selectedIndex;

    this.ionTabs.ionChange.subscribe(() => {
      this.scrollToselectedTab();
    })

    for (let i = 0; i < this.tabs.length; i++) {
      this.tabs[i].ionSelect.subscribe(() => {
        this.currentTabIndex = i;
      });
    }

    // set tabbar overflow-x: scroll
    this.renderer.setElementStyle(this.nativeTabbar, 'overflow-x', 'scroll');

    // set tabbar overflow-y: hidden
    this.renderer.setElementStyle(this.nativeTabbar, 'overflow-y', 'hidden');

    this.setAnchorStyles();

    this.scrollToselectedTab();
  }

  onResize(event: Event) {
    this.setAnchorStyles();
    setTimeout(() => {
      this.scrollToselectedTab();
    }, 300);
  }

  setAnchorStyles() {
    if (typeof (this.nativeTabbar) !== 'undefined') {
      const tabBar_width = this.nativeTabbar.clientWidth;
      const numOfTabs = this.tabs.length;
      let numOfVisibleAnchors = 0;
      let sumOfVisibleAnchorWidth = 0;

      // loop through tab elements in tabs
      for (let i = 0; i < numOfTabs; i++) {
        const element = this.nativeTabbar.children[i];
        // when Tab visible (effecting show property)
        if (this.tabs[i]._isShown) {
          numOfVisibleAnchors++;
          // set <a> display: inline-table
          this.renderer.setElementStyle(element, 'display', 'inline-table');
          // set <a> width: 6rem
          this.renderer.setElementStyle(element, 'width', '6rem');
          // extra padding for title-only tags only
          if (element.classList.contains('has-title-only')) {
            // set <a> padding-top: 1.5rem
            this.renderer.setElementStyle(element, 'padding-top', '1.5rem');
          }
          sumOfVisibleAnchorWidth += element.clientWidth;
        } else {
          // set <a> display: none
          this.renderer.setElementStyle(element, 'display', 'none');
        }
      }

      // to prevent extra space at end
      if (sumOfVisibleAnchorWidth < tabBar_width) {
        const anchorWidth = tabBar_width / numOfVisibleAnchors;
        for (let i = 0; i < numOfTabs; i++) {
          const element = this.nativeTabbar.children[i];
          // when Tab not not visible effecting show property
          if (!element.classList.contains('tab-hidden')) {
            this.renderer.setElementStyle(element, 'width', anchorWidth + 'px');
          }
        }
      }
    }
  }

  scrollToselectedTab() {
    if (typeof this.nativeTabbar !== 'undefined') {
      const tabBar_width = this.nativeTabbar.clientWidth;
      const selectedTab = this.nativeTabbar.children[this.currentTabIndex];
      const selectedTab_Width = selectedTab.clientWidth;
      const selectedTab_LeftOffset = document.getElementById(selectedTab.id).offsetLeft;
      const selectedTab_mid = selectedTab_LeftOffset + (selectedTab_Width / 2);
      const newScrollLeft = selectedTab_mid - (tabBar_width / 2);

      this.scrollXTo(newScrollLeft, 300).then(() => { });
    }
  }

  scrollXTo(x: number, duration: number = 300): Promise<any> {
    // scroll animation loop w/ easing
    const tabbar = this.nativeTabbar;

    if (!tabbar) {
      // invalid element
      return Promise.resolve();
    }
    x = x || 0;
let originalRaf;
     originalRaf = (window[window['Zone']['__symbol__']('requestAnimationFrame')]
    || window[window['Zone']['__symbol__']('webkitRequestAnimationFrame')]);
    const nativeRaf = originalRaf !== undefined ? originalRaf['bind'](window) : window.requestAnimationFrame.bind(window);
    const fromX = tabbar.scrollLeft;
    const maxAttempts = (duration / 16) + 100;

    return new Promise(resolve => {
      let startTime: number;
      let attempts = 0;
      let isPlaying: boolean;

      // scroll loop
      function step() {
        attempts++;

        if (!tabbar || !isPlaying || attempts > maxAttempts) {
          isPlaying = false;
          resolve();
          return;
        }

        let time = Math.min(1, ((Date.now() - startTime) / duration));

        // where .5 would be 50% of time on a linear scale easedT gives a
        // fraction based on the easing method
        const easedT = (--time) * time * time + 1;

        if (fromX !== x) {
          tabbar.scrollLeft = Math.floor((easedT * (x - fromX)) + fromX);
        }

        if (easedT < 1) {
          nativeRaf(step);
        } else {
          // done
          resolve();
        }
      }

      // start scroll loop
      isPlaying = true;

      // chill out for a frame first
      nativeRaf(() => {
        startTime = Date.now();
        nativeRaf(step);
      });

    });
  }

}
====================

Runtime Error
Uncaught (in promise): Error: Template parse errors: Can't bind to 'scrollable-tabs' since it isn't a known
property of 'ion-tabs'. 1. If 'ion-tabs' is an Angular component and it has 'scrollable-tabs' input, then verify that
it is part of this module. 2. If 'ion-tabs' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the
'@NgModule.schemas' of this component to suppress this message. 3. To allow any property add
'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" </ion-toolbar> </ion-footer> <iontabs
#ionTabs [ERROR ->][scrollable-tabs]="ionTabs" name="main"> <ion-tab [root]="tab1Root"
tabTitle="Home" tabIcon="fa-hom"): ng:///TabsModule/TabsPage.html@22:19 Error: Template parse errors:
Can't bind to 'scrollable-tabs' since it isn't a known property of 'ion-tabs'. 1. If 'ion-tabs' is an Angular
component and it has 'scrollable-tabs' input, then verify that it is part of this module. 2. If 'ion-tabs' is a Web
Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to
suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas'
of this component. (" </ion-toolbar> </ion-footer> <ion-tabs #ionTabs [ERROR ->][scrollable-tabs]="ionTabs"
name="main"> <ion-tab [root]="tab1Root" tabTitle="Home" tabIcon="fa-hom"):
ng:///TabsModule/TabsPage.html@22:19 at syntaxError (http://localhost:8100/build/vendor.js:71352:34) at
TemplateParser.parse (http://localhost:8100/build/vendor.js:81843:19) at JitCompiler._compileTemplate
(http://localhost:8100/build/vendor.js:95594:39) at http://localhost:8100/build/vendor.js:95518:62 at
Set.forEach (<anonymous>) at JitCompiler._compileComponents
(http://localhost:8100/build/vendor.js:95518:19) at createResult
(http://localhost:8100/build/vendor.js:95403:19) at t.invoke (http://localhost:8100/build/polylls.js:3:14976)
at Object.onInvoke (http://localhost:8100/build/vendor.js:4509:37) at t.invoke
(http://localhost:8100/build/polylls.js:3:14916)
Stack
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'scrollable-tabs' since it isn't a known property of 'ion-tabs'.
1. If 'ion-tabs' is an Angular component and it has 'scrollable-tabs' input, then verify that it is part of this mo
2. If 'ion-tabs' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
 </ion-toolbar>
</ion-footer>
<ion-tabs #ionTabs [ERROR ->][scrollable-tabs]="ionTabs" name="main">
 <ion-tab [root]="tab1Root" tabTitle="Home" tabIcon="fa-hom"): ng:///TabsModule/TabsPage.html@22:19
Error: Template parse errors:
Can't bind to 'scrollable-tabs' since it isn't a known property of 'ion-tabs'.
1. If 'ion-tabs' is an Angular component and it has 'scrollable-tabs' input, then verify that it is part of this mo
2. If 'ion-tabs' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
 </ion-toolbar>
</ion-footer>
<ion-tabs #ionTabs [ERROR ->][scrollable-tabs]="ionTabs" name="main">
 <ion-tab [root]="tab1Root" tabTitle="Home" tabIcon="fa-hom"): ng:///TabsModule/TabsPage.html@22:19
 at syntaxError (http://localhost:8100/build/vendor.js:71352:34)
 at TemplateParser.parse (http://localhost:8100/build/vendor.js:81843:19)
 at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:95594:39)
 at http://localhost:8100/build/vendor.js:95518:62
 at Set.forEach (<anonymous>)
 at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:95518:19)
 at createResult (http://localhost:8100/build/vendor.js:95403:19)
 at t.invoke (http://localhost:8100/build/polyfills.js:3:1497

Please provide any solution.

**Comment by danielsogl** [comment]
I have to close your issue because I don't read that much code without further explanation of your problem.
