### ISSUE TITLE
Super Tabs for Ionic 4 ?

### ISSUE THREAD

**Issue by Chethannp** [zyra/ionic2-super-tabs#329]

**Comment by eduardoRoth** [comment]
As soon as there's an official release of Ionic 4, we'll work on it.

**Comment by eduardogiorgio** [comment]
Excellent

**Comment by ThomasLohmann** [comment]
@victorjatoba +1. The community really needs it!

**Comment by chelinho139** [comment]
@victorjatoba +1

**Comment by SteveKennedy** [comment]
+1 Would the recent Angular 5 support commits enable support for Ionic 4?

**Comment by mariusbolik** [comment]
+1

**Comment by ASHFAQPATWARI** [comment]
@eduardoRoth We have a RC release of ionic v4 now. Can you guys start looking into it now ?

**Comment by aravind14feb** [comment]
+1 Eagerly waiting for some update on this!

**Comment by YamanSehzade** [comment]
+1 looking forward for Ionic 4 support

**Comment by S0me1ne** [comment]
+1

**Comment by jemliF** [comment]
+1

**Comment by pipoa** [comment]
+1

**Comment by CL4RSEN** [comment]
@eduardoRoth there is now an official Ionic 4 release. I am hoping you will look into adding Ionic 4 support - Keep up the good work 👍

**Comment by eduardoRoth** [comment]
We'll start working soon in an official release for Ionic 4.

**Comment by SteveKennedy** [comment]
I'm pretty sure that's today, just announced....  😃

**Comment by NgYueHong** [comment]
Ionic 4 is now official released. Really hope to see the support for it soon.

**Comment by eduardoRoth** [comment]
My wording caused a little confusion; what I meant is that, now that Ionic 4 is officially released, we're going to work in an official release of SuperTabs for it.

**Comment by lincolnthree** [comment]
@eduardoRoth I'll be interested to see the approach you guys end up taking. I'm not sure if you saw my PRs on master (still open), but I got fairly deep into this module recently. I have also been trying to use Ionic 4 and ... it's quite different in approach, so I've been struggling to feel like there's really a good way to build non-trivial app-like UI functionality in V4. At least without a LOT of custom work.

When you start working on it, I'll be happy to take a look and pitch in as I have time/applicable knowledge.

**Comment by ihadeed** [comment]
thanks @lincolnthree -- we'll make sure to stay in touch!

**Comment by lincolnthree** [comment]
Just sharing something I thought might be useful for this:

https://blog.angularindepth.com/dynamically-loading-components-with-angular-cli-92a3c69bcd28

Could be useful for providing super tabs functionality that supports lazy-loading without having to define routes. You'd still need to do some configuration, but it wouldn't need to be in the Router.

Also related, a bit closer to the metal:

https://blog.angularindepth.com/here-is-what-you-need-to-know-about-dynamic-components-in-angular-ac1e96167f9e

Just in case it's useful to anyone. I haven't gotten to try this yet but it looks solid/uses supported APIs (unless you get to the bottom of article 2)

**Comment by lincolnthree** [comment]
If you just want to see the example code: https://github.com/devboosts/dynamic-component-loader

**Comment by maedewiza** [comment]
How are the work on support for ionic 4 going? Can you give an approximate release date?

**Comment by ihadeed** [comment]
Please watch the following branch for updates on Ionic 4 development: https://github.com/zyra/ionic2-super-tabs/tree/master
