### ISSUE TITLE
Scrolling list inside tab

### ISSUE THREAD

**Issue by PavlezT** [zyra/ionic2-super-tabs#33]
Vertical list scrolling make tabs don't swipeable.
It need to click on item to enable swiping again.
![xd9mkpotdb](https://cloud.githubusercontent.com/assets/15145855/25375461/6dd7a7ac-29a9-11e7-8a33-fe0891f0b202.gif)

And if it "super" tabs, it will be better to add customization for each tab (not for whole super-tabs component) to make it possible to change color of badge and icon.

**Comment by ihadeed** [comment]
Is that a regular `ion-list` or a VirtualScroll?

**Comment by PavlezT** [comment]
It is ion-list. This issue appears on emulator. I have tested this on real device and all was okay. I don`t think  that all devices will work properly when there is several scroll items on screen.

**Comment by ihadeed** [comment]
If it works well in the browser and on real devices, I don't think it's an issue with the module.
