### ISSUE TITLE
How do I push a page with Super Tabs with a preselected tab index?

### ISSUE THREAD

**Issue by johndouglas3** [zyra/ionic2-super-tabs#331]
Hi, 

How can I open up a page that has super tabs in it with a predetermined tab index?

For example, I want to open a page with the 3rd tab already selected

Is this possible?

**Comment by Nick-lab** [comment]
`<super-tabs height="100%" selectedTabIndex="1" indicatorColor="dark" >
  <super-tab [root]="tab1Root" id="ShopNav"></super-tab>
  <super-tab [root]="tab2Root" id="HomeNav"></super-tab>
  <super-tab [root]="tab3Root" id="InveNav"></super-tab>
</super-tabs>`
