### ISSUE TITLE
^5.0.2 Version 

### ISSUE THREAD

**Issue by nvsu** [zyra/ionic2-super-tabs#343]
I'm using 5.0.2 Version  and implemented as below:

1. app.module.ts file : 
import { SuperTabsModule } from 'ionic2-super-tabs';
...
  imports: [
    BrowserModule,
    HttpClientModule,
    SuperTabsModule.forRoot(),

2. tag.ts file 
import { SuperTabsController } from 'ionic2-super-tabs';
export class TabsPage {
  tab1Root: any = PageTab1;
  tab2Root: any = PageTab2;

3. tab.html file
<super-tabs>  
	  <super-tab [root]="tab1Root" title="tab1Title" icon="call"></super-tab>
	  <super-tab [root]="tab2Root" title="tab2Title" icon="md-contacts"></super-tab>
</super-tabs>

It is raised error while running:
vendor.js:1823 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'root' since it isn't a known property of 'super-tab'.
1. If 'super-tab' is an Angular component and it has 'root' input, then verify that it is part of this module.
2. If 'super-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

Can you help me to explain about this error ?

Thank you very much for your help.

**Comment by magic-77** [comment]
in tab.ts include this
```
@ViewChild(SuperTabs) superTabs: SuperTabs;
```

**Comment by nvsu** [comment]
it is ok now, thank you very much @magic-77 .
