### ISSUE TITLE
Property 'parent' in type 'SuperTabsComponent' is not assignable to the same property in base type 'NavigationContainer'.

### ISSUE THREAD

**Issue by dilanfdo** [zyra/ionic2-super-tabs#359]
Im using supertabs in my application and it was working fine but im upgrading my ionic 3 app to ionic 4. but im getting the following error

`ERROR in node_modules/ionic2-super-tabs/dist/components/super-tabs.d.ts(153,5): error TS2416: Property 'parent' in type 'SuperTabsComponent' is not assignable to the same property in base type 'NavigationContainer'.
  Type 'NavControllerBase' is not assignable to type 'NavController'.
    Types of property 'config' are incompatible.
      Type 'import("E:/Work/Projects/COJ/ConsumerApp/node_modules/ionic-angular/umd/config/config").Config' is not assignable to type 'import("E:/Work/Projects/COJ/ConsumerApp/node_modules/ionic-angular/config/config").Config'.
        Types have separate declarations of a private property '_c'.`

The type script versions that i am using is mentioned below

`+-- @angular-devkit/build-angular@0.12.4
| `-- @angular-devkit/build-optimizer@0.12.4
|   `-- typescript@3.2.4
+-- @angular/cli@7.2.4
| `-- @schematics/angular@7.2.4
|   `-- typescript@3.2.2
+-- @ionic/angular-toolkit@1.3.0
| `-- typescript@3.3.1
`-- typescript@3.1.6`

Isn't this supporting for ionic 4? 
Thanks in advance for the solutions.

**Comment by ihadeed** [comment]
This library is not compatible with Ionic 4 yet. Please watch the following branch for updates: https://github.com/zyra/ionic2-super-tabs/tree/master
