### ISSUE TITLE
Content via http only gets loaded on the first tab

### ISSUE THREAD

**Issue by karlvd** [zyra/ionic2-super-tabs#36]
v2.1.0
- Tabs working
- Provider/Http content displayed in tabs

v2.2.2
- Tabs stopped working

v2.3.0
- Tabs working
- Provider/Http content not displayed on second tab

To reproduce
- Use the tabs starter template
- Add super tabs with 2 tabs
- Add list in both tabs
```
<ion-list no-padding no-margin>
  <ion-item *ngFor="let item of stuff?.stuff" >
    Item
  </ion-item>  
</ion-list>
```
Grab some data from a povider using http
```
ionViewDidLoad() {    
    this.loadData();
  }

  loadData() {
    this.stuffProvider.getStuff().subscribe((response) => {
      this.stuff = {
        stuff: response.data
      };      
    });
  }

```
On the second tab the data from the provider is null

![image](https://cloud.githubusercontent.com/assets/3678047/25401651/92c3fba4-29f6-11e7-8fae-5be34a72dbc7.png)

Here is a simple repo, downgrading to 2.1.0 makes it work
[repo](https://github.com/karlvd/tabstest)

Thanks again for all the great work you have done with this project!

**Comment by palbaladejo** [comment]
Yes, I have the same issue. It is loaded, but no displayed at the template.

Thanks @karlvd, downgrading to 2.1.0 solved the issue for now.

**Comment by Anujmoglix** [comment]
same issue for me . @palbaladejo  how you downgrade it ? share command

**Comment by karlvd** [comment]
@palbaladejo to downgrade, just update your package.json to
`"ionic2-super-tabs": "2.1.0"`

run
`npm install`

**Comment by karlvd** [comment]
@ihadeed I have done a few more tests related to this issue and updated the repo to cover more scenarios
[repo](https://github.com/karlvd/tabstest)

The page for the second tab contains various scenarios for loading data, my conclusions so far:
- Any data set in ionViewDidLoad() doesn´t bind to the template, including just assigning a value to a var, the event fires but the data can´t be accessed by the template
- Data such as assigning a value to a var works using ngOnInit() instead of ionViewDidLoad()
- Calling a provider from ngOnInit() fires the success callback but any data set in it is not accessible by the template
- Based on this, the problem is not related to http, rather something related to scope and binding

```
ionViewDidLoad() {
    console.log('load tab2');
    this.anything3 = 'Anthing set in ionViewDidLoad()';
    // Any data set here is not accessible
    this.stuff1 = {
      stuff: ['x', 'y', 'z']
    }

    this.stuffProvider.getStuff().subscribe((response) => {
      // Any data set here is not accesible
      this.stuff2 = {
        stuff: response.data
      };
      // This fires correctly
      console.log('provider success 1');
      // This log is printed
      console.log(this.stuff2);
    }, (error) => {
      console.log('provider error 1 : ' + error);
    });

  }

  ngOnInit() {
    this.anything4 = 'Anthing set in ngOnInit()';
    // Any data set here is accessible
    this.stuff3 = {
      stuff: ['x', 'y', 'z']
    };

    this.stuffProvider.getStuff().subscribe((response) => {
      // Any data set here is not accesible
      this.stuff4 = {
        stuff: response.data
      };
      // Not even this
      this.stuff5 = {
        stuff: ['x', 'y', 'z']
      };
      // This fires correctly
      console.log('provider success 2');

    }, (error) => {
      console.log('provider error 2 : ' + error);
    });
  }

```

**Comment by ihadeed** [comment]
Could you please update to `ionic2-super-tabs@2.3.2` and let me know if this issue is fixed?

**Comment by karlvd** [comment]
Same result unfortunately :(

**Comment by mforloni** [comment]
I have the same problem! please, fix it on time :(

**Comment by ihadeed** [comment]
Fixed in 2.3.3

**Comment by mforloni** [comment]
rootParams not work!! How can I pass parameter to tabs?

**Comment by karlvd** [comment]
Fantastic work, thank you!

@mforloni works for me

Create an object to pass on as rootParams
```
this.rootParams = {
   myVar: 'someValue'
};
```
Add it to the super-tab element
`<super-tab [root]="'SomePage'" [rootParams]="rootParams" title="Title" id="myTab"></super-tab>`

Pick it up in the constructor on the tab page
`this.myVar = navParams.get('myVar');`

**Comment by Anujmoglix** [comment]
In my app performance is still not good :(

**Comment by mforloni** [comment]
@karlvd I have a big problem. 
After the fix, the component work but I can change  the content on the tab only at the first loading and I don't change the tab. Why?
Example, if I open the new tab and then I came back on the previous tab and I change its content (ex. one icon) this not display the modify.

Can you help me?

**Comment by kodeine** [comment]
#61 i guess its related to this?

**Comment by ihadeed** [comment]
@kodeine no I don't think they're related. This issue here is fixed.
