### ISSUE TITLE
 Property 'parent' in type 'SuperTabsComponent' is not assignable to the same property in base type 'NavigationContainer'.

### ISSUE THREAD

**Issue by phamconganh** [zyra/ionic2-super-tabs#365]
My project was just update to angular 7.x and ionic 4.x and typescript 3.2.4
I read some solution in issues which closed, they said install lower typescript version.
Because  The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0, so i can't install typescript lower 3.1.1
are there other solution? Or i must wait for next version of ionic2-super-tabs version?

**Comment by ihadeed** [comment]
This library still doesn't support Ionic 4. You can track the status of it here: https://github.com/zyra/ionic2-super-tabs/tree/master
