### ISSUE TITLE
Allowing SwipeBack (IOS) within child nav

### ISSUE THREAD

**Issue by robholden** [zyra/ionic2-super-tabs#4]
I discovered that it wasn't allowing SwipeBack on ios when navigating within the child ion-nav. If you have more than 1 active ion-nav it doesn't allow it.

I made the following changes to super-tabs.js to enable it:

1. Add a new property:
`this.sliding = false;`

2. Turn this flag when we're dragging:
`
SuperTabsComponent.prototype.onDrag = function (ev) {
        ...
        this.sliding = true;
};
`

3. Turn off once it's stopped:
`
SuperTabsComponent.prototype.onSlideDidChange = function () {
        ...
        this.sliding = false;
};
`

4. Hide navs if not active:
`<ion-nav *ngIf=\"sliding || selectedTabIndex == i || (selectedTabIndex > (tabs.length - 1) && i == (tabs.length - 1))\" [root]=\"tab.tabRoot\" [rootParams]=\"tab.navParams\"></ion-nav>\n`

**Comment by ihadeed** [comment]
This approach isn't optimal. 

1. scroll position will no longer be saved when swiping between tabs
2. the `ion-nav` and all it's page contents are being re-rendered every time the user is swiping between tabs, which uses lots of GPU memeory

Swipeable tabs aren't meant to be main navigation for your app. They are used to display different sections of a page (e.g categories, labels, genres... etc). Therefore, I think this feature isn't really needed. I will add swipe-back abilities for the main page but not for the child pages.

If you have a common use-case where you think this feature is needed, then I can consider adding it (perhaps with a different approach).
