### ISSUE TITLE
hiding bottom border and shadow

### ISSUE THREAD

**Issue by kodeine** [zyra/ionic2-super-tabs#41]
Hello,
i tried to add no-border on ion-header but it looks like its overriding the bottom border and shadow, is there a way to remove shadow/border?

Thanks

**Comment by ihadeed** [comment]
`<ion-header no-shadow no-border>` should work

**Comment by kodeine** [comment]
i tried ```<ion-header no-shadow no-border>``` but doesnt work. 
![image](https://cloud.githubusercontent.com/assets/8620059/25730542/2afb82c6-3103-11e7-8e0e-a63da5001c1f.png)

**Comment by ihadeed** [comment]
Oh I didn't realize this is what you meant. I thought you had the header above `super-tabs`. In this case just add add `no-shadow` to `super-tabs` as follows:
```html
<super-tabs no-shadow>
  ...
</super-tabs>
```

**Comment by kodeine** [comment]
works great :))
