### ISSUE TITLE
super-tab http get the data  *ngFor is not working

### ISSUE THREAD

**Issue by kongdewen1994** [zyra/ionic2-super-tabs#45]
two super-tab( selectedTabIndex="0" ), other super-tab( Tab selected Index="1" ) use http get the data  *ngFor is not working

data:any = [];

getforkdata() {
    var _that = this;
    
    let url = "http://www.devonhello.com/chihu/share";

    var headers = new Headers();
    headers.append('Content-Type', 'application/x-www-form-urlencoded');
    
    this.data = [1,2,3,4];   // now data has changed *ngFor is ok

    this.http.post(url, "len=1", {
      headers: headers
    })
      .subscribe((res) => {
        //alert(JSON.stringify(res.json()));
        _that.data = res.json();      // now *ngFor is not working,Even if the data has changed
        //alert(_that.forkdata.length);
      });
  }

**Comment by borisgastelu** [comment]
The same problem here. I just tried the following:

The first page works using *ngFor because it loads first.

page1.ts
```
getItems(): void {
    this._itemsSrv.getItems()
        .subscribe(items => this.items = items);
}
```

But when I change tab does not show nothing even with array of primitive values

page2.ts
`let numbers = [1, 2, 3];`

page2.html
```
<ion-content>
    <ion-list>
        <ion-item *ngFor="let number of numbers">{{ number }}</ion-item>
    <ion-list>
</ion-content>
```
So, I don't think is a problem retrieving data, it's just an super-tab issue loading the next page.

**Comment by ihadeed** [comment]
Are you guys using the latest version?

**Comment by kongdewen1994** [comment]
ionic2-super-tabs@2.3.0

**Comment by borisgastelu** [comment]
I just updated to the latest version 2.5.2, now it works! Thanks!

**Comment by kongdewen1994** [comment]
update the latest version is normal ! Thanks!

**Comment by rahul635** [comment]
ionic2-super-tabs@4.1.4 same problem , and version 2.5.2 not working now
