### ISSUE TITLE
On page initialization icon is not highlighted 

### ISSUE THREAD

**Issue by yatingodse** [zyra/ionic2-super-tabs#5]
Hi,
When first time i open my page t takes me desired tab as mentioned in selectedtabindex but icon for that tab is not getting highlighted.
But if i start sliding the tabs it works perfectly.

**Comment by ihadeed** [comment]
Hey there,

Do you experience this issue on all platforms/devices? or specific ones?

I'm not having this issue but I can look into it if you can give me more details.
