### ISSUE TITLE
tabs scrollable [new feature needed]

### ISSUE THREAD

**Issue by ccgitgit** [zyra/ionic2-super-tabs#51]
I like super-tabs ,   can you add scrollable tabs feature to it  ?    
such as:   [Ionic2-ScrollableTabs ](https://github.com/SinoThomas/Ionic2-ScrollableTabs)  
[react-native-scrollable-tab-view](https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/ScrollableTabsExample.js)

**Comment by darron1217** [comment]
@ccgitgit Did you tried the feature implemented?
https://github.com/zyra/ionic2-super-tabs#scrolltabs

**Comment by ccgitgit** [comment]
@darron1217  thank you and sorry for my carelessness.  I thank this issue could be closed because it is now the same as #49.

P.S  The examples above have a very good detail: when you click a tab, it will animate to the center position unless the tabs reach the boundary. This makes users easily notice that there are more tabs. 

Because I haven't tried successfully, I hope super-tabs also act like that.
