### ISSUE TITLE
Runtime Error Uncaught (in promise): invalid views to insert

### ISSUE THREAD

**Issue by vanessasoutoc** [zyra/ionic2-super-tabs#52]
I have erro in page to tags:
Runtime Error
Uncaught (in promise): invalid views to insert

My version ionic:
 Ionic Framework: 3.2.1
Ionic App Scripts: 1.3.7
Angular Core: 4.1.0
Angular Compiler CLI: 4.1.0
Node: 6.10.3
OS Platform: Linux 4.4
Navigator Platform: Linux x86_64

**Comment by vanessasoutoc** [comment]
Path page caused the error.
Solved!! Thank

**Comment by MikePaer** [comment]
@vanessasoutoc, can you elaborate on this? What is "path page" and what caused the error? Thanks.

**Comment by vanessasoutoc** [comment]
@MikePaer path of view page!

**Comment by LuukPrins** [comment]
Can you probably write down the specific path and how you changed it?

**Comment by webdesignsbymike** [comment]
added '/' before the path name

before
```
{ path: 'dashboard', component: DashboardComponent },
{ path: '**', component: NotfoundpageComponent }


```
after: 
```
 { path: '/dashboard', component: DashboardComponent },
 { path: '**', component: NotfoundpageComponent }
```

**Comment by vivekpratapsingh** [comment]
@webdesignsbymike I am 'getting path can not start with /'

**Comment by annuranjan** [comment]
Not working for me too. Can anyone provide us the solution for this?

**Comment by CR7LOVE** [comment]
@vivekpratapsingh    I also getting 'path cannot start with a slash'. Have you solved this problem?

**Comment by CR7LOVE** [comment]
I solved this problem by adding a module for the page.
Before: 
I do not import a module for a page.In app.module, I declare the page in 'declarations'.
After:
I import a module for every page. In app.module, I declare the module in 'imports'.
In app.routing.module,I  do not use lazy loading, like this:
`{ path: 'chart', component:  ChartPage }`
