### ISSUE TITLE
scrollTabs not Working

### ISSUE THREAD

**Issue by danielehrhardt** [zyra/ionic2-super-tabs#56]
Hi,

i created a new project and added many tabs and enabled scrollTabs but it is not working

can you reproduce?

**Comment by danielehrhardt** [comment]
ah okay it scrolls when i change the tabs. It is possible to add a swiper?

**Comment by ihadeed** [comment]
Please elaborate, what is the expected behaviour? and what is the issue you are having?. Also, what versions are you using of: `ionic-angular` and `ionic2-super-tabs` ?

**Comment by danielehrhardt** [comment]
Hi,

sorry for the bad Description of my Problem.
`ionic-angular 3.2.1`
`ionic2-super-tabs 2.6.2`

![image](https://cloud.githubusercontent.com/assets/19570043/26369898/65e47aee-3ff6-11e7-90e8-16f7ecc9d703.png)


if i have many pages i can set `scrollTabs` this is cool but two other things would be awesome.
This css Effect on the right side:
![image](https://cloud.githubusercontent.com/assets/19570043/26369917/75acb54a-3ff6-11e7-8a81-2dff9cf7d755.png)
that the user knows that there are other pages
```
.tab-buttons-container {
            &::after {
                content: '';
                position: absolute;
                right: 0;
                top: 0;
                width: 80px;
                height: 100%;
                background: linear-gradient(to left, #F4F7F7 0%, rgba(244, 247, 247, 0.94) 30%, rgba(244, 247, 247, 0) 100%);
            }
        }
```

and the second one that the user can scroll Horizontal in the tabs

thank you
Daniel

**Comment by ihadeed** [comment]
This CSS effect should stay as a customization in your app as it's not a standard. My goal for this project is to fully implement the [material specs here](https://material.io/guidelines/components/tabs.html#tabs-specs). 

I will be adding an option to align the tabs as follows: 
![image](https://cloud.githubusercontent.com/assets/13794420/26374445/6207c50c-3fd3-11e7-8923-2e8925977d85.png)


I will also add an option for large displays to show arrows on the side for the user to click on them: 
![image](https://cloud.githubusercontent.com/assets/13794420/26374472/73bc52ea-3fd3-11e7-8339-2f9c0e35e494.png)


I think the effect you have there is very nice though, I might reference it in the docs for people to see it.

**Comment by danielehrhardt** [comment]
Yes your changes would be awesome!! Thank you!! 
The idea to implement the material guidelines is good.
