### ISSUE TITLE
slideTo() does not display page

### ISSUE THREAD

**Issue by Chris1234567899** [zyra/ionic2-super-tabs#60]
Seems to be a bug:
when using the slideTo function, the tab bar reacts accordingly, but the content of the selected page does not display. The selected page neither shows up in the DOM.

(I'm using lazy loading btw, if that might be of an issue here)

Clicking directly in the tabbar or sliding between tabs works fine though.

Would be nice if you can have a look at this.

**Comment by Chris1234567899** [comment]
I just tried it without lazy loading the tab page, but the issue remains the same.

**Comment by FilipMatys** [comment]
Experiencing the same issue. Using provider to hold data between two tab pages. When i use slideTo, the page does not rerender with actual data. Sliding works.

**Comment by FilipMatys** [comment]
Well, managed to work around that using:
```
@ViewChild(SuperTabs) tabs: SuperTabs;

this.tabs.slideTo(index);
this.tabs.onTabChange(index);
```

Seems to work with no issues.

**Comment by Chris1234567899** [comment]
Thanks a lot, the `this.tabs.onTabChange(index);` indeed does the trick.

Nonetheless, I had a look into the code and it seems the slideTo function does not check whether the tab was loaded or not. Some small edit like this pseudo code might already fix that bug.
```
if(tab != loaded){
    tab.load(true)
}
slideTo(tab)
```

**Comment by ihadeed** [comment]
This should be fixed in the latest releases.
