### ISSUE TITLE
get super-tab datas from network, it does't work.

### ISSUE THREAD

**Issue by longdw** [zyra/ionic2-super-tabs#68]
when I set static datas like this, it can work normal.

```
<super-tab [root]="pageContent" badge="5" [title]="showTitles? 'Trending' : ''" [icon]="showIcons? 'trending-up' : ''" id="page2"></super-tab>
<super-tab [root]="pageContent" [title]="showTitles? 'Favorites' : ''" [icon]="showIcons? 'heart' : ''" id="page3"></super-tab>
```

but when I get datas from network, like this, can see nothing.
`<super-tab *ngFor="let item of menus" [swipeBackEnabled]="false" [root]="pageContent" [title]="showTitles? 'Home' : ''" [icon]="showIcons? 'home': ''" id="page1" [rootParams]="testParams()">
</super-tab>`

the `menus` I got it from network.

**Comment by ihadeed** [comment]
Check my comment here https://github.com/zyra/ionic2-super-tabs/issues/46#issuecomment-302667371

**Comment by longdw** [comment]
@ihadeed perfect! thank you very much.
