### ISSUE TITLE
swipable tabs for Ionic3

### ISSUE THREAD

**Issue by YasirPanjsheri** [zyra/ionic2-super-tabs#7]
Is possible to make this work for ionic 3 ?

**Comment by ihadeed** [comment]
What issues are you experiencing with Ionic 3?

I tested it and it works well. You just need to make sure it's imported in a shared module, or in your page's module.

**Comment by ihadeed** [comment]
The new version `v2.0.0` is built with Ionic 3, checkout the new README and/or release notes for more details.
