### ISSUE TITLE
Always black background, pages not visible.

### ISSUE THREAD

**Issue by jans-y** [zyra/ionic2-super-tabs#71]
Hi,

I wasn't successful at implementing your plungin.

When inspecting through DOM, I was able to see, that pages were loaded but weren't visible.

Ionic 3.3.0, Chrome 58, Mac OS Sierra

**Comment by ihadeed** [comment]
Could you please provide steps to reproduce this issue?

Doe the example project work fine for you?

**Comment by karimessouabni** [comment]
Having the same problem but just for Ios on Ionic Lab. Works fine fore Android. 

![capture d ecran 2017-10-18 a 01 32 17](https://user-images.githubusercontent.com/1681953/31694390-4f2951cc-b3a4-11e7-8d68-5fc869593eee.png)

my ionic info : 
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v8.4.0
    npm   : 5.3.0 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b 

Misc:

    backend : legacy

**Comment by elmartino** [comment]
See: https://github.com/zyra/ionic2-super-tabs/issues/218

**Comment by stegithub** [comment]
I had this problem on iOS (black background). I solved it putting all the html content into a ion-content component. (<ion-content>  ...mypage...    </ion-content>).
