### ISSUE TITLE
superTabs is not working in my project

### ISSUE THREAD

**Issue by gitpuja** [zyra/ionic2-super-tabs#74]
I have imported  it in my app.module.ts as
import { SuperTabsModule } from 'ionic2-super-tabs';
...
imports: [
    BrowserModule,
    SuperTabsModule,
    IonicModule.forRoot(MyApp)

  ]

but its showing error as 

![image](https://user-images.githubusercontent.com/28949674/26928329-624198e8-4c73-11e7-9fd9-224c8fbefd03.png)

Module '"F:/ionic2/ionic2Demo/node_modules/ionic-angular/index"' has no exported member 'RootNode'.

What's wrong I am doing.Can some please help me out.

**Comment by ihadeed** [comment]
What version of Ionic Framework are you using?

This version of the module supports only Ionic Framework 3.x and has no backward compatibility for 2.x.

**Comment by gitpuja** [comment]
ok . Actually I am using ionic 2.0.0 .Is there anything related like super tabs which i can use

**Comment by ihadeed** [comment]
You can install `ionic2-super-tabs@1.1.1` .. it's an older version of this module. Works well, as far as I can remember. You can find the docs here for that version: https://github.com/zyra/ionic2-super-tabs/blob/872966c8620ee2c5f330a6ccbca3ba637893f283/README.md

**Comment by gitpuja** [comment]
Thanks Its working nicely .But I also needed tab bar swiping , i think that property is not included here.

**Comment by ihadeed** [comment]
Yeah that feature wasn't available in the old version. You will need to update your app to Ionic 3 and use the latest version of this module.

**Comment by gitpuja** [comment]
Ok  thank you so much for your help it is working nicely now.
