### ISSUE TITLE
Performance issues on Android

### ISSUE THREAD

**Issue by JaneDawson** [zyra/ionic2-super-tabs#77]
Thank you very much for great module. I love the super tabs and really appreciate the work you're doing! Great job!

However, using the most current version of Ionic, I experience some performance issues with the super-tabs v2.6.2 on Android (device: OnePlus X). Didn't try on other devices, so far. Using ionic-serve everything works fine.

I have 4 tabs (not using scrollTabs). When I slide from one tab to another it "stops" in between for like 0.5 seconds before the slide is continued. If I click on the tabs I don't experience any delay.

Any idea where this could come from and what I could try to improve it?

**Comment by ihadeed** [comment]
Does it happen only the first time you swipe into that tab, or every time?

**Comment by JaneDawson** [comment]
Every time, every tab, unfortunately.

**Comment by JaneDawson** [comment]
I think my issues may be connected to some database requests. I'm using Firebase with AngularFire2 and just added offline support, by using [AngularFire2 Offline](https://github.com/adriancarriger/angularfire2-offline). It became much better now. 

However, it's still very sluggish when swiping to a tab that performs an authentication database-request to get the current userId.

Any suggestions here?

**Comment by ihadeed** [comment]
Are you performing these things inside `ionViewWillEnter` or `ionViewDidEnter`? 

If you have some blocking code in there, that will cause the transition between slides to be delayed.

**Comment by JaneDawson** [comment]
I perform it in `ionViewDidLoad()`. 

I'm fetching the userId and some user data from the database there.
How would you suggest to do it instead?

**Comment by ihadeed** [comment]
`didLoad` should have no effect, this module doesn't deal with that directly.
