### ISSUE TITLE
Title and Icon logged to console at every init

### ISSUE THREAD

**Issue by JaneDawson** [zyra/ionic2-super-tabs#78]
Just a suggestion: In your `super-tab-button.js` you have this part:
```
SuperTabButton.prototype.ngOnInit = function () {
        console.log(this.title, this.icon);
    };
```
Whenever the app loads it loggs the title and name of the icon of each tab to the console. I don't see what this would be necessary for and it just fills the console. Could be deleted, couldn't it?

**Comment by ihadeed** [comment]
Sorry about that, that's not supposed to be there.

I'll get rid of it in the next release.
