### ISSUE TITLE
Can't scroll with super-tab

### ISSUE THREAD

**Issue by goyexin** [zyra/ionic2-super-tabs#80]
Thanks for creating the great module.

After I switched to the super-tab component, I've the scroll bar on my page.
Have you met something similar before? 

My case is very simple:
<ion-content no-bounce>
  <super-tabs id="mainTabs" scrollTabs toolbarColor="light" toolbarBackground="danger" (tabSelect)="onTabSelect($event)">
    <super-tab [root]="page1" title="xxx" id="page1"></super-tab>
    <super-tab [root]="page2" title="xx" id="page2"></super-tab>
  </super-tabs>
</ion-content>

**Comment by ihadeed** [comment]
Is this with the latest Ionic Framework 3.4.0? I haven't tested the module with that version yet.

If not, please provide me with more details to reproduce this issue.

**Comment by goyexin** [comment]
It's actually 3.0.0
My code:

import { Component } from '@angular/core';
import { NavController,NavParams } from 'ionic-angular';
import { PostsList } from '../posts-list/posts-list';
import { SuperTabsController } from 'ionic2-super-tabs';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  page1: any = PostsList;
  page2: any = PostsList;

  showIcons: boolean = false;
  showTitles: boolean = true;
  pageTitle: string = 'Full Height';

  constructor(public navCtrl: NavController, private navParams: NavParams, private superTabsCtrl: SuperTabsController) {

    const type = navParams.get('type');
    switch (type) {
      case 'icons-only':
        this.showTitles = false;
        this.pageTitle += ' - Icons only';
        break;

      case 'titles-only':
        this.showIcons = false;
        this.pageTitle += ' - Titles only';
        break;
    }
  }

  ngAfterViewInit() {
    // this.superTabsCtrl.increaseBadge('page1', 10);
    // this.superTabsCtrl.enableTabSwipe('page3', false);
    // this.superTabsCtrl.enableTabsSwipe(false);
  }

  onTabSelect(tab: { index: number; id: string; }) {
    console.log(`Selected tab: `, tab);
  }

}
