### ISSUE TITLE
SuperTabsController

### ISSUE THREAD

**Issue by ankurgarach** [zyra/ionic2-super-tabs#81]
No provider for SuperTabsController!

**Comment by philipgriffin** [comment]
I also received this error and added it myself but not sure if that is the correct approach.

Have you tried adding it yourself to the providers? 

```
import { SuperTabsController } from 'ionic2-super-tabs';


  providers: [
      AuthData,
      SuperTabsController,
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
```

**Comment by ihadeed** [comment]
Make sure that you are importing `SuperTabsModule.forRoot()` in your `app.module.ts`.

If you're still having issues, please provide steps to reproduce this problem.

**Comment by arulyan** [comment]
> Make sure that you are importing `SuperTabsModule.forRoot()` in your `app.module.ts`.
> 
> If you're still having issues, please provide steps to reproduce this problem.

yes don't forget to add ".forRoot()" along with "SuperTabsModule"
