### ISSUE TITLE
Super Tabs Placement at bottom

### ISSUE THREAD

**Issue by AppSphere** [zyra/ionic2-super-tabs#82]
First of all a big thanks for creating this super tabs. The app I am developing requires the same look and feel on iOS and Android for Tabs Placement. I need the Tabs to be placed bottom.

I tried setting the {tabsPlacement: 'bottom'} but with no change. Can you please let me know how to configure placement of Super Tabs?

**Comment by ihadeed** [comment]
Did you use `tabsPlacement` input? https://github.com/zyra/ionic2-super-tabs#tabsplacement

Or did you pass that value to the `config` input?

**Comment by ankurgarach** [comment]
i have same problem.
i have pass the value in config but don't set tabs in bottom

**Comment by ankurgarach** [comment]
Solution
i have solve this problem remove from config and put it in super-tabs tag

**Comment by tamilm47** [comment]
@ankurgarach  could you explain how u fix it?
