### ISSUE TITLE
Hide Ion-fab along with ion-tabs in ionic 2

### ISSUE THREAD

**Issue by gitpuja** [zyra/ionic2-super-tabs#90]
<ion-tabs tabsPlacement="bottom" [selectedIndex]='tabIndex' #myTabs>
  <div class="overlay"></div>
  <ion-fab #fab1 bottom left >
    <button ion-fab mini color="light" class="arrow">
      <ion-icon ios="ios-arrow-dropleft" md="md-arrow-dropleft"></ion-icon>
    </button>
  </ion-fab>

  <ion-tab></ion-tab>
  <ion-tab [root]="tab1Root"  tabIcon="home"></ion-tab>
  <ion-tab [root]="tab2Root" tabIcon="add"></ion-tab>
  <ion-tab [root]="tab3Root"  tabIcon="calendar"></ion-tab>
  <ion-tab></ion-tab>

  <ion-fab #fab2 id="more-fab" bottom right>
    <button ion-fab mini color="light" (click)="next()" class="arrow">
      <ion-icon ios="ios-arrow-dropright" md="md-arrow-dropright"></ion-icon>
    </button>
  </ion-fab>
</ion-tabs>

I have ion-tabs like this.I have already hidden tabs on subpages by including IonicModule.forRoot(MyApp, {
      tabsHideOnSubPages: true
    })
in app.component but the ion-fab button are still showing.

Can anyone please help me how to hide ion-fab button on load of subpages like ion-tabs

**Comment by ihadeed** [comment]
You're asking a question about the Ionic Framework's tabs. This repo is a third party module for Swipeable tabs. It has nothing to do with Ionic's tabs.

I suggest you open a thread on the forums to get help.

Here's a quick tip:
You can use the Events provider from Ionic to communicate between the different pages.
