### ISSUE TITLE
Supertabs component start loading at the same time

### ISSUE THREAD

**Issue by MiLL10N** [zyra/ionic2-super-tabs#92]
First, thanks for creating this super tabs for us developer to use.
Application I'm developing now using your supertabs to for generate user order in different category.
(Example 1st tab : Electronic Device, 2nd tab : Cloth, 3rd : other)
I'm using only "one" component for all tabs and send different parameter to generate different order detail and the problem is when this page is loading. All components will start loading at the same time and I'm using LoadingController to generate loading screen when the page is loading so this loading screen stack up multiple times and very noticeable.

[Loading 1 time]
![image](https://user-images.githubusercontent.com/15230452/27531024-45c3ca7c-5a85-11e7-8004-292b63407d14.png)

[Loading stacked 2 times]
![image](https://user-images.githubusercontent.com/15230452/27531006-3053ef6e-5a85-11e7-936b-9458b50f0294.png)

Is there anyway to prevent other components (same component but send different parameter) start loading when that page not swap to yet?

PS. Sorry for bad grammar

**Comment by ihadeed** [comment]
The current tab loads, as well was the tab before and after. This way when the user partially swipes, they will see loaded content instead of a blank page (if swiping into the for the first time). 

What I recommend doing here, is not using the loading dialog.

**Comment by VlnRbn** [comment]
@ihadeed Please inform if there a way to stop loading other tabs. Thanks.

**Comment by eduardoRoth** [comment]
@MiLL10N @VlnRbn .
Change your loading into your ionViewWillEnter instead of ionViewWillLoad and only open it if your variable is empty.

**Comment by nemchand123** [comment]
@eduardoRoth 
I don't want to load my page again when i come back to the same page.. In this case what to do?

**Comment by magic-77** [comment]
@MiLL10N Hey, the only way to stop preloading neighbour tabs is patching the component itself
Open node_modules/ionic2-super-tabs/dist/components/super-tabs.js" and go to Line 460.

Change
```
return tab.load(Math.abs(_this.selectedTabIndex - i) < 2);
```

to
```
return tab.load(Math.abs(_this.selectedTabIndex - i) === 0);
```
