### ISSUE TITLE
using slideTo when you're on the actual page

### ISSUE THREAD

**Issue by parkbroom** [zyra/ionic2-super-tabs#93]
Hi All,

Is it possible to use slideTo when you're on the actual page? (NOT tabs.html)  
I need to create a button on HomePage to slide to the AboutPage

Here is my tabs.html

<super-tabs id="mainTabs" selectedTabIndex="0" (tabSelect)="onTabSelect($event)">
  <super-tab [root]="HomePage" title="First page" icon="home" id="homeTab"></super-tab>
  <super-tab [root]="AboutPage" title="Second page" icon="pin" id="locationTab"></super-tab>
  <super-tab [root]="ContactPage" title="Third page" icon="heart" id="favouritesTab"></super-tab>
</super-tabs>

Here is my home.html.  I need it to slide to AboutPage. 
<button (click)="slideToAboutPage()"></button>

I tried using various ViewChild decorators but it will doesn't work for me.  Does anyone have a working example?

**Comment by ihadeed** [comment]
You can use the `SuperTabsController`. See https://github.com/zyra/ionic2-super-tabs#supertabscontroller-provider
